community/ocrmypdf: disable on riscv64
tests fails

FAILED tests/test_acroform.py::test_digital_signature - ocrmypdf.exceptions.M...
FAILED tests/test_image_input.py::test_img2pdf_fails - ocrmypdf.exceptions.Mi...
FAILED tests/test_main.py::test_input_file_not_a_pdf - ocrmypdf.exceptions.Mi...
FAILED tests/test_main.py::test_blank_input_pdf - ocrmypdf.exceptions.Missing...
FAILED tests/test_graft.py::test_links - ocrmypdf.exceptions.MissingDependenc...
FAILED tests/test_main.py::test_repeat_ocr - ocrmypdf.exceptions.MissingDepen...
FAILED tests/test_main.py::test_input_file_not_found - ocrmypdf.exceptions.Mi...
FAILED tests/test_main.py::test_tesseract_config_valid - ocrmypdf.exceptions....
FAILED tests/test_main.py::test_pdfa_n[3] - ocrmypdf.exceptions.MissingDepend...
FAILED tests/test_main.py::test_oversample[hocr] - ocrmypdf.exceptions.Missin...
FAILED tests/test_main.py::test_jbig2_passthrough - ocrmypdf.exceptions.Missi...
FAILED tests/test_main.py::test_pagesegmode[sandwich] - ocrmypdf.exceptions.M...
FAILED tests/test_main.py::test_skip_ocr - ocrmypdf.exceptions.MissingDepende...
FAILED tests/test_main.py::test_ocr_timeout[sandwich] - ocrmypdf.exceptions.M...
FAILED tests/test_main.py::test_tesseract_thresholding[auto] - ocrmypdf.excep...
FAILED tests/test_main.py::test_pdfa_n[1] - ocrmypdf.exceptions.MissingDepend...
FAILED tests/test_main.py::test_sidecar_pagecount - ocrmypdf.exceptions.Missi...