community/kio-extras: rebuild against kdsoap 1.9.1
Disable arches s390x, ppc64le due to missing khtml-dev.

Fix for:
  ERROR: unable to select packages:
    so:libkdsoap.so.1.9.0 (no such package):
      required by: kio-extras-20.08.1-r0[so:libkdsoap.so.1.9.0]