community/py3-send2trash: fix installer .whl filename
Fix packaging error due to changed .whl filename.

```
FileNotFoundError: [Errno 2] No such file or directory: '.dist/Send2Trash*.whl'
```