community/subtitlecomposer: disable on aarch64
Revert "community/subtitlecomposer: enable on aarch64"

Failing in builders:

  [180/191] Building CXX object src/tests/CMakeFiles/test-core-richdocumentlayout.dir/richdocumentlayouttest.cpp.o
  [181/191] Building CXX object src/tests/CMakeFiles/test-core-richdocumentlayout.dir/test-core-richdocumentlayout_autogen/mocs_compilation.cpp.o
  ninja: job failed: /usr/bin/c++ -DKCOREADDONS_LIB -DKGUIADDONS_LIB -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QML_LIB -DQT_TESTCASE_BUILDDIR=\"/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/build/src/tests\" -DQT_TESTCASE_SOURCEDIR=\"/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/src/tests\" -DQT_TESTLIB_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -D_DEFAULT_SOURCE -D_LARGEFILE64_SOURCE -I/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/build/src/tests -I/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/src/tests -I/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/build/src/tests/test-core-richcss_autogen/include -I/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/src -I/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/src/widgets -I/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/build/src -I/usr/include/AL -isystem /usr/include/qt6/QtTest -isystem /usr/include/qt6 -isystem /usr/include/qt6/QtCore -isystem /usr/lib/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtWidgets -isystem /usr/include/qt6/QtGui -isystem /usr/include/qt6/QtDBus -isystem /usr/include/qt6/QtWidgets/6.11.0 -isystem /usr/include/qt6/QtWidgets/6.11.0/QtWidgets -isystem /usr/include/qt6/QtCore/6.11.0 -isystem /usr/include/qt6/QtCore/6.11.0/QtCore -isystem /usr/include/qt6/QtGui/6.11.0 -isystem /usr/include/qt6/QtGui/6.11.0/QtGui -isystem /usr/include/qt6/QtQml -isystem /usr/include/qt6/QtQmlIntegration -isystem /usr/include/qt6/QtNetwork -isystem /usr/include/KF6/KCoreAddons -isystem /usr/include/KF6/KWidgetsAddons -isystem /usr/include/KF6/KTextWidgets -isystem /usr/include/KF6/SonnetUi -isystem /usr/include/KF6/Sonnet -isystem /usr/include/KF6/KI18n -isystem /usr/include/KF6/KCodecs -isystem /usr/include/KF6/SonnetCore -isystem /usr/include/KF6/KIOCore -isystem /usr/include/KF6/KIO -isystem /usr/include/KF6/KIOFileWidgets -isystem /usr/include/KF6/KIOWidgets -isystem /usr/include/KF6/KIOGui -isystem /usr/include/KF6/KConfig -isystem /usr/include/KF6/KConfigCore -isystem /usr/include/KF6/KService -isystem /usr/include/KF6/KJobWidgets -isystem /usr/include/KF6/KCompletion -isystem /usr/include/KF6/KBookmarks -isystem /usr/include/qt6/QtXml -isystem /usr/include/KF6/KItemViews -isystem /usr/include/KF6/Solid -isystem /usr/include/KF6/KXmlGui -isystem /usr/include/KF6/KConfigWidgets -isystem /usr/include/KF6/KConfigGui -isystem /usr/include/KF6/KColorScheme -isystem /usr/include/KF6/KGuiAddons -isystem /usr/include/qt6/QtOpenGLWidgets -isystem /usr/include/qt6/QtOpenGL -isystem /usr/include/qt6/QtCore5Compat -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -fno-operator-names -fno-exceptions -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Werror=init-self -Wvla -Wdate-time -Wsuggest-override -Wlogical-op -fdiagnostics-color=always -Os -DNDEBUG -std=gnu++20 -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT src/tests/CMakeFiles/test-core-richcss.dir/richcsstest.cpp.o -MF src/tests/CMakeFiles/test-core-richcss.dir/richcsstest.cpp.o.d -o src/tests/CMakeFiles/test-core-richcss.dir/richcsstest.cpp.o -c /home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/src/tests/richcsstest.cpp
  In file included from [01m[K/usr/include/c++/15.2.0/chrono:51[m[K,
                   from [01m[K/usr/include/qt6/QtCore/qobject.h:24[m[K,
                   from [01m[K/usr/include/qt6/QtCore/QObject:1[m[K,
                   from [01m[K/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/src/core/richtext/richcss.h:12[m[K,
                   from [01m[K/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/src/tests/richcsstest.h:10[m[K,
                   from [01m[K/home/buildozer/aports/community/subtitlecomposer/src/subtitlecomposer-0.8.2/src/tests/richcsstest.cpp:8[m[K:
  [01m[K/usr/include/c++/15.2.0/sstream:462:7:[m[K [01;31m[Kerror: [m[K'[01m[Kstruct std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs[m[K' redeclared with different access [[01;31m[K-Wtemplate-body[m[K]
    462 |       [01;31m[Kstruct[m[K __xfer_bufptrs
        |       [01;31m[K^~~~~~[m[K
  ninja: subcommand failed
  >>> ERROR: subtitlecomposer: build failed

This reverts commit a57df16384c849e687a3dd41c47b0b587131a332.