community/grml-zsh-config: upgrade to 0.19.1
Move zshrc to /etc/zsh/zshrc.d to fix compatibility with the default
zshrc introduced in zsh 5.8.1-r1.

Fix for:
  (8/8) Installing grml-zsh-config (0.17.4-r0)
  ERROR: grml-zsh-config-0.17.4-r0: trying to overwrite etc/zsh/zshrc owned by zsh-5.8.1-r1.