testing/domoticz: disable on arm
Fails with:
domoticz-0_git20160214/hardware/PiFace.cpp: In member function 'int CPiFace::Read_Write_SPI_Byte(unsigned char*, int)':
domoticz-0_git20160214/hardware/PiFace.cpp:1011:23: error: '_IOC_SIZEBITS' was not declared in this scope
   return ioctl (m_fd, SPI_IOC_MESSAGE(1), &spi) ;

probably missing include