main/xen: upgrade to 4.20.0
don't package s390-netboot.img nor s390-ccw.img in the xen-qemu
subpackage, as they contain textrels

  >>> xen-qemu*: Running postcheck for xen-qemu
  >>> ERROR: xen-qemu*: Found textrels:
  TEXTREL  /builds/alpine/aports/main/xen/pkg/xen-qemu/usr/share/qemu-xen/qemu/s390-netboot.img
  TEXTREL  /builds/alpine/aports/main/xen/pkg/xen-qemu/usr/share/qemu-xen/qemu/s390-ccw.img
  >>> ERROR: xen*: prepare_subpackages failed
  >>> ERROR: xen: rootpkg failed

found by Daniel Néri to have been introduced to QEMU in

  https://gitlab.com/qemu-project/qemu/-/commit/7cd50cbe4ca3e2860b31b06ec92c17c54bd82d48

and solved in

  https://gitlab.com/qemu-project/qemu/-/commit/3259b4424a85d9cdfd1a33ed6030a6c51c1b9b8b

s390-ccw.img can be found in the qemu subpackage qemu-s390x-firmware