community/mitmproxy: add missing dependency
  > mitmproxy --mode regular -p 8888
  Traceback (most recent call last):
    File "/usr/bin/mitmproxy", line 5, in <module>
      from mitmproxy.tools.main import mitmproxy
    File "/usr/lib/python3.14/site-packages/mitmproxy/tools/main.py", line 15, in <module>
      from mitmproxy import master
    File "/usr/lib/python3.14/site-packages/mitmproxy/master.py", line 5, in <module>
      from .addons import termlog
    File "/usr/lib/python3.14/site-packages/mitmproxy/addons/__init__.py", line 20, in <module>
      from mitmproxy.addons import proxyauth
    File "/usr/lib/python3.14/site-packages/mitmproxy/addons/proxyauth.py", line 20, in <module>
      from mitmproxy.utils import htpasswd
    File "/usr/lib/python3.14/site-packages/mitmproxy/utils/htpasswd.py", line 13, in <module>
      import bcrypt
  ModuleNotFoundError: No module named 'bcrypt'