community/polkit: fix upgrading from polkit-elogind < 0.118
(84/885) Installing polkit-elogind-libs (0.119-r6)
ERROR: polkit-elogind-libs-0.119-r6: trying to overwrite usr/lib/libpolkit-agent-1.so.0 owned by polkit-elogind-0.118-r1.
ERROR: polkit-elogind-libs-0.119-r6: trying to overwrite usr/lib/libpolkit-agent-1.so.0.0.0 owned by polkit-elogind-0.118-r1.
ERROR: polkit-elogind-libs-0.119-r6: trying to overwrite usr/lib/libpolkit-gobject-1.so.0 owned by polkit-elogind-0.118-r1.
ERROR: polkit-elogind-libs-0.119-r6: trying to overwrite usr/lib/libpolkit-gobject-1.so.0.0.0 owned by polkit-elogind-0.118-r1.