community/grommunio-admin-web: temporarily disable on 32-bit arm
Fails to rebuild on the 3.24 arm* builders despite increasing node
memory limit.

```
REACT_APP_BUILD_VERSION="4.0.0-0" yarn run build
yarn run v1.22.22
$ react-scripts build
(node:20554) [DEP0176] DeprecationWarning: fs.F_OK is deprecated, use fs.constants.F_OK instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

<--- Last few GCs --->

[20554:0xa4de1000]     2038 ms: Mark-Compact (reduce) 9.6 (14.6) -> 8.9 (11.1) MB, pooled: 0 MB, 15.83 / 0.00 ms  (average mu = 0.992, current mu = 0.992) last resort; GC in old space requested
[20554:0xa4de1000]     2059 ms: Mark-Compact (reduce) 8.9 (11.1) -> 8.9 (10.6) MB, pooled: 0 MB, 20.78 / 0.00 ms  (average mu = 0.982, current mu = 0.001) last resort; GC in old space requested

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
----- Native stack trace -----
```