unmaintained/ocaml-topkg: move from testing - fails to build
    Error: Unbound module Topkg_string
    File "./pkg/pkg.ml", line 29, characters 5-10:
    29 | open Topkg
              ^^^^^
    Error: Unbound module Topkg