community/py3-outcome: add asyncio provider to checkdepends
Add an asyncio provider to complete test_async.py tests.

```
________________________________ test_acapture _________________________________
async def functions are not natively supported.
You need to install a suitable plugin for your async framework, for example:
  - anyio
  - pytest-asyncio
  - pytest-tornasync
  - pytest-trio
  - pytest-twisted

[...]

=========================== short test summary info ============================
FAILED tests/test_async.py::test_acapture - Failed: async def functions are n...
FAILED tests/test_async.py::test_asend - Failed: async def functions are not ...
FAILED tests/test_async.py::test_traceback_frame_removal - Failed: async def ...
```