community/libksane: disable on armhf due to deps
ERROR: unsatisfiable constraints:
  extra-cmake-modules (missing):
    required by: .makedepends-libksane-20200129.143650[extra-cmake-modules]
  ki18n-dev (missing):
    required by: .makedepends-libksane-20200129.143650[ki18n-dev]
  kwidgetsaddons-dev (missing):
    required by: .makedepends-libksane-20200129.143650[kwidgetsaddons-dev]
  ktextwidgets-dev (missing):
    required by: .makedepends-libksane-20200129.143650[ktextwidgets-dev]
  kwallet-dev (missing):
    required by: .makedepends-libksane-20200129.143650[kwallet-dev]
>>> ERROR: libksane: builddeps failed
>>> libksane: Uninstalling dependencies...