Revert "community/fractal: upgrade to 12"
	error: rustc 1.87.0 is not supported by the following packages:
	...

This fractal version would be important to have since it supports room
version 12 and fixes a security issue
(https://matrix.org/blog/2025/08/security-release/) but if it requires
the a very new Rust compiler, that doesn't work for us.

This reverts commit 2f9495cbcee530b1c9bb9c4d43eae33eefb811cc.