community/xdg-desktop-portal: add missing dependency on cmd:fusermount3
    $ /usr/libexec/xdg-document-portal                                                                                                                                                                                                            00:56:31
    fuse: failed to exec fusermount3: No such file or directory
    error: fuse init failed: Can't mount path /run/user/1000/doc