main/py3-html5lib: fix build with python 3.14 and setuptools 82
Fix `AttributeError: module 'ast' has no attribute 'Str'` error due to
the removal of `ast.Str` in python 3.14.

Fix `ModuleNotFoundError: No module named 'pkg_resources'` error due to
the removal of `pkg_resources` in setuptools 82.