community/nxp-mfgtools: fix dependency error by renaming split function
Without this change `depends="$subpackages"` does not work correctly and
causes a dependency error for this package:

	ERROR: unable to select packages:
	  nxp-mfgtools-uuu:_uuu (no such package):
	    required by: nxp-mfgtools-1.4.72-r1[nxp-mfgtools-uuu:_uuu]

This is just a dirty hotfix to resolve the dependency error, I think
this package could generally benefit from a cleanup.

See #13173