community/gnome-colors: set builddir
Set `builddir` so the working directory path can be found.

```
>>> gnome-colors: Unpacking /var/cache/distfiles/v3.23/gnome-colors-5.5.1.tar.gz...
mv: can't rename 'src': Invalid argument
>>> ERROR: gnome-colors: prepare failed
```