testing/yosys: add missing dependency to abc
And also drop downloading the vendored-in abc (which was just built
but not installed, anyway).

This fixes:

    2.23.17.5. Executing ABC9.
    Running ABC command: "abc" -s -f <abc-temp-dir>/abc.script 2>&1
    ABC: sh: abc: not found
    ERROR: ABC: execution of command ""abc" -s -f /tmp/yosys-abc-opgndO/abc.script 2>&1" failed: return code 127.