community/timblserver: rebuild against icu 78
Resolve build error with dependent mbt on loongarch64, where abuild
traced a dependency on icu solibs.

```
>>> mbt: Analyzing dependencies...
ERROR: unable to select packages:
  so:libicui18n.so.76 (no such package):
    required by: timblserver-1.19-r1[so:libicui18n.so.76]
  so:libicuio.so.76 (no such package):
    required by: timblserver-1.19-r1[so:libicuio.so.76]
  so:libicuuc.so.76 (no such package):
    required by: timblserver-1.19-r1[so:libicuuc.so.76]
  .makedepends-mbt-20260115.162304:
    masked in: cache
    satisfies: world[.makedepends-mbt=20260115.162304]
```