community/speakersafetyd: add system user to audio group
If this user is not in the audio group, then it's unable to use the
sound card:

    INFO  [speakersafetyd] Starting up
    ...
    INFO  [speakersafetyd] Found 4 speakers
    INFO  [speakersafetyd] Opening control device
    ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for AppleJ413
    thread 'main' panicked at src/helpers.rs:11:13:
    hw:AppleJ413: Could not open sound card! Error: ALSA function 'snd_ctl_open' failed with error 'No such device (19>

This also changes the home dir, since I guess the original path was a
mistake (according to the pkg maintainer.)

This adds a pre-upgrade install script to fix existing installs