community/py3-pdm-backend: fix tests with editables 0.6
Update demo `.pth` filenames in `tests/test_api.py` to fix tests. Path
files are renamed to `_editable_impl<project>.pth` by default in
editables 0.6.

```
______________________ test_build_editable[demo-package] _______________________

dist = PosixPath('/tmp/pytest-of-buildozer/pytest-12/test_build_editable_demo_packa0/dist')
fixture_project = PosixPath('/tmp/pytest-of-buildozer/pytest-12/test_build_editable_demo_packa0/demo-package')

    @pytest.mark.parametrize("name", ["demo-package"])
    def test_build_editable(dist: Path, fixture_project: Path) -> None:
        wheel_name = api.build_editable(dist.as_posix())
        assert api.get_requires_for_build_editable() == []
        with zipfile.ZipFile(dist / wheel_name) as zf:
            namelist = zf.namelist()
>           assert "demo_package.pth" in namelist
E           AssertionError: assert 'demo_package.pth' in ['.gitignore', '_editable_impl_demo_package.pth','_editable_impl_demo_package.py', 'demo_package-0.1.0.dist-info/METADATA', 'demo_package-0.1.0.dist-info/WHEEL', 'demo_package-0.1.0.dist-info/entry_points.txt', ...]

/home/buildozer/aports/community/py3-pdm-backend/src/pdm-backend-2.4.4/tests/test_api.py:302: AssertionError
```

```
FAILED tests/test_api.py::test_build_editable[demo-package] - AssertionError:...
FAILED tests/test_api.py::test_build_editable_src[demo-src-package-include]
FAILED tests/test_api.py::test_build_editable_pep420[demo-pep420-package] - A...
```