testing/swaylock-effects: disable on armhf armv7 x86 - fails to build
    [36/37] Linking static target libclient_protos.a
    ninja: job failed: gcc -Iswaylock.p -I. -I.. -Iinclude -I../include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -Wno-unused-parameter -Wno-unused-result -Wundef -Wvla -fopenmp -mtune=native '-DSYSCONFDIR="//etc"' '-DSWAYLOCK_VERSION="v3.15.0_alpha20210804-1662-g8ce8e72754 (" __DATE__ ", branch '"'"'master'"'"')"' -Os -fomit-frame-pointer -Os -fomit-frame-pointer -fPIE -MD -MQ swaylock.p/fade.c.o -MF swaylock.p/fade.c.o.d -o swaylock.p/fade.c.o -c ../fade.c
    ../fade.c: In function 'fade_prepare':
    ../fade.c:83:26: error: implicit declaration of function 'malloc' [-Werror=implicit-function-declaration]
       83 |  fade->original_buffer = malloc(size);
          |                          ^~~~~~
    ../fade.c:83:26: error: incompatible implicit declaration of built-in function 'malloc' [-Werror]
    ../fade.c:8:1: note: include '<stdlib.h>' or provide a declaration of 'malloc'
        7 | #include <string.h>
      +++ |+#include <stdlib.h>
        8 |
    ../fade.c: In function 'fade_destroy':
    ../fade.c:126:2: error: implicit declaration of function 'free' [-Werror=implicit-function-declaration]
      126 |  free(fade->original_buffer);
          |  ^~~~
    ../fade.c:126:2: error: incompatible implicit declaration of built-in function 'free' [-Werror]
    ../fade.c:126:2: note: include '<stdlib.h>' or provide a declaration of 'free'
    cc1: all warnings being treated as errors