community/system-config-printer: add missing dependencies
otherwise, it fails to run:

> Traceback (most recent call last):
>   File "/usr/share/system-config-printer/system-config-printer.py", line 37, in <module>
>     gi.require_version('GdkPixbuf', '2.0')
> AttributeError: module 'gi' has no attribute 'require_version'