testing/opa: fix test with go 1.26.1
Update patch to fix test error with runtime/metrics.

```
--- FAIL: TestJSONSerialization (0.02s)
    prometheus_test.go:197: unexpected extra metrics, expected 125, got 138
    prometheus_test.go:208: unexpected metric: go_sched_goroutines_running_goroutines (type: map[help:Approximate count of goroutines executing. Always less than or equal to /sched/gomaxprocs:threads. Not guaranteed to add up to /sched/goroutines:goroutines with other goroutine metrics. Sourced from /sched/goroutines/running:goroutines. metric:[map[gauge:map[value:3]]] name:go_sched_goroutines_running_goroutines type:GAUGE])
    prometheus_test.go:208: unexpected metric: go_sched_threads_total_threads (type: map[help:The current count of live threads that are owned by the Go runtime. Sourced from /sched/threads/total:threads. metric:[map[gauge:map[value:7]]] name:go_sched_threads_total_threads type:GAUGE])
    prometheus_test.go:208: unexpected metric: go_godebug_non_default_behavior_htmlmetacontenturlescape_events_total (type: map[help:The number of non-default behaviors executed by the html/template package due to a non-default GODEBUG=htmlmetacontenturlescape=... setting. Sourced from /godebug/non-default-behavior/htmlmetacontenturlescape:events. metric:[map[counter:map[createdTimestamp:2026-03-07T06:11:47.361230056Z value:0]]] name:go_godebug_non_default_behavior_htmlmetacontenturlescape_events_total type:COUNTER])

[...]

FAIL	github.com/open-policy-agent/opa/internal/prometheus	0.026s
```