community/py3-pyocd: fix checksum
Update checksum to fix checksum mismatch error on the 3.24 builders.
Upstream re-tagged the release archive.

```
sha512sum: WARNING: 1 of 1 computed checksums did NOT match
Because the remote file above failed the sha512sum check it will be renamed.
Rebuilding will cause it to re-download which in some cases may fix the problem.
Renaming: py3-pyocd-0.43.1.tar.gz to py3-pyocd-0.43.1.tar.gz.65cfff28
>>> ERROR: py3-pyocd: Use 'abuild checksum' to generate/update the checksum(s)
```

```
diff -rupN a/.git_archival.txt b/.git_archival.txt
--- a/.git_archival.txt 2026-03-05 11:25:14.000000000 +0000
+++ b/.git_archival.txt 2026-03-05 11:25:14.000000000 +0000
@@ -1,4 +1,4 @@
 node: d9672375e024707c554670d8430f94eb1f6271ed
 node-date: 2026-03-05T12:25:14+01:00
 describe-name: v0.43.1
-ref-names: HEAD -> main, tag: v0.43.1
+ref-names: tag: v0.43.1
```