community/horust: re-enable on loongarch64
as the libc upstream has already fixed issue

Last time loongarch64 was disabled, it was likely because of the following error log:
Ref: https://github.com/bytecodealliance/rustix/issues/1007
```
error[E0609]: no field `st_atime` on type `&libc::stat`
   --> /builds/williamdes/aports/community/horust/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-0.38.44/src/fs/mod.rs:173:14
    |
173 |         self.st_atime as i64
    |              ^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
173 -         self.st_atime as i64
173 +         self.st_atim as i64
```

This is a known issue upstream in libc, which has been fixed since libc 0.2.181.

Ref:
https://github.com/rust-lang/libc/issues/4939
https://github.com/rust-lang/libc/releases/tag/0.2.181
https://github.com/FedericoPonzi/Horust/blob/v0.1.14/Cargo.lock#L1111