testing/babeltrace: disable on mips(64)
Due to test failures:

> ERROR: plugins/sink.ctf.fs/succeed/test_succeed - too few tests run (expected 14, got 0)
> ERROR: plugins/sink.ctf.fs/succeed/test_succeed - exited with status 14
> ERROR: ctf-writer/test_ctf_writer 326 - Babeltrace could read the resulting trace # UNPLANNED
> ERROR: ctf-writer/test_ctf_writer - too many tests run (expected 325, got 326)
> ERROR: plugins/src.ctf.fs/succeed/test_succeed - exited with status 1
> ERROR: cli/test_trace_copy - exited with status 70
>
> ============================================================================
> Testsuite summary for babeltrace2 2.0.3
> ============================================================================
> # TOTAL: 21091
> # PASS:  21008
> # SKIP:  0
> # XFAIL: 0
> # FAIL:  76
> # XPASS: 0
> # ERROR: 7
> ============================================================================