testing/netsink: modernize APKBUILD and fix depends
py-setuptools is a required dependency to use netsink, otherwise
netsink fails with error:
ImportError: No module named pkg_resources