community/zathura-pdf-mupdf: rebuild with girara-0.4.3-r0
zathura-pdf-mupdf is built with an older version of girara which is gone:

    # apk add zathura-pdf-mupdf
    ERROR: unable to select packages:
      so:libgirara-gtk3.so.3 (no such package):
        required by: zathura-pdf-mupdf-0.4.1-r13[so:libgirara-gtk3.so.3]