testing/swi-prolog: disable on riscv64
ERROR: unable to select packages:
  libunwind-dev (no such package):
    required by: .makedepends-swi-prolog-20211124.181630[libunwind-dev]