community/melonds: fix build with qt6 6.10.0
Add `Qt6GuiPrivate` target which is required for
`qpa/qplatformnativeinterface.h` header include to build with qt6 6.10.0.

```
ninja: job failed: /usr/bin/c++ -DARCHIVE_SUPPORT_ENABLED -DMELONDS_VERSION=\"0.9.5\" -DOGLRENDERER_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -I/home/buildozer/aports/community/melonds/src/melonDS-0.9.5/build/src/frontend/qt_sdl/melonDS_autogen/include -I/home/buildozer/aports/community/melonds/src/melonDS-0.9.5/src/frontend/qt_sdl -I/home/buildozer/aports/community/melonds/src/melonDS-0.9.5/src/frontend/qt_sdl/.. -I/home/buildozer/aports/community/melonds/src/melonDS-0.9.5/src/frontend/qt_sdl/../.. -isystem /usr/include/SDL2 -isystem /usr/include/slirp -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtGui -isystem /usr/include/qt6/QtWidgets -isystem /usr/include/qt6/QtNetwork -isystem /usr/include/qt6/QtMultimedia -isystem /usr/include/qt6/QtOpenGL -isystem /usr/include/qt6/QtOpenGLWidgets -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -O3 -DNDEBUG -std=gnu++17 -flto=auto -fno-fat-lto-objects -fPIE -D_REENTRANT -MD -MT src/frontend/qt_sdl/CMakeFiles/melonDS.dir/main.cpp.o -MF src/frontend/qt_sdl/CMakeFiles/melonDS.dir/main.cpp.o.d -o src/frontend/qt_sdl/CMakeFiles/melonDS.dir/main.cpp.o -c /home/buildozer/aports/community/melonds/src/melonDS-0.9.5/src/frontend/qt_sdl/main.cpp
/home/buildozer/aports/community/melonds/src/melonDS-0.9.5/src/frontend/qt_sdl/main.cpp:47:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   47 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```