community/py3-mpi4py: upgrade to 4.1.1
https://github.com/mpi4py/mpi4py/blob/master/CHANGES.rst#release-411-2025-10-10

4.1.1 includes support for python 3.14.
4.0.1 updates python 3.13 support, changes license to BSD-3-Clause.

Resolves `TypeError: new_compiler() got an unexpected keyword argument
'dry_run'` error when building with setuptools >=81.

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025