community/py3-munch: fix tests with python 3.14
Fix test errors with python 3.14.

Example error:

```
__________________ test_reserved_attributes[__firstlineno__] ___________________

attrname = '__firstlineno__'

    @pytest.mark.parametrize("attrname", dir(Munch))
    def test_reserved_attributes(attrname):
        # Make sure that the default attributes on the Munch instance are
        # accessible.

[...]

        # ...and that the attr is of the correct original type.
        attr = getattr(empty_munch, attrname)
        if attrname == '__doc__':
            assert isinstance(attr, str)
        elif attrname in ('__hash__', '__weakref__'):
            assert attr is None
        elif attrname == '__module__':
            assert attr == 'munch'
        elif attrname == '__dict__':
            assert attr == {}
        else:
>           assert callable(attr)
E           assert False
E            +  where False = callable(48)

tests/test_munch.py:229: AssertionError
```

```
FAILED tests/test_munch.py::test_reserved_attributes[__firstlineno__] - asser...
FAILED tests/test_munch.py::test_reserved_attributes[__static_attributes__]
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025