community/gallery-dl: upgrade to 1.32.0
https://codeberg.org/mikf/gallery-dl/releases/tag/v1.32.0

Also resolves test errors, found after a checksum mismatch error on the
3.24 builders.

```
ERROR: setUpClass (test_postprocessor.ZipTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "[...]/gallery-dl-1.31.10/test/test_postprocessor.py", line 83, in setUpClass
    cls.job = FakeJob()
              ~~~~~~~^^
  File "[...]/gallery-dl-1.31.10/test/test_postprocessor.py", line 35, in __init__
    extr.directory_fmt = ("{category}",)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'directory_fmt' and no __dict__ for setting new attributes

----------------------------------------------------------------------
Ran 247 tests in 0.397s

FAILED (errors=46, skipped=7)
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18143