community/gcc-cross-embedded: fix use of libstdc++ with newlib
Without this patch, linking any C++ software against libstdc++ fails
with an undefined reference to getentropy(3). This is due to the fact
that newlib declares a getentropy function prototype without providing
the symbol.

This patch fixes the issue by backporting a non-upstreamed GCC fix from
the SDK for the Zephyr operating system.

See: https://github.com/zephyrproject-rtos/gcc/pull/8