testing/php7-tideways_xhprof: disable on aarch64 due to build failure
     gcc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2 -DPHP_ATOM_INC -I/home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/include -I/home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/main -I/home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2 -I/usr/include/php7 -I/usr/include/php7/main -I/usr/include/php7/TSRM -I/usr/include/php7/Zend -I/usr/include/php7/ext -I/usr/include/php7/ext/date/lib -Os -DHAVE_CONFIG_H -Os -c /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/tideways_xhprof.c  -fPIC -DPIC -o .libs/tideways_xhprof.o
    In file included from /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/tracing.h:1:0,
                     from /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/tracing.c:11:
    /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/tracing.c: In function 'tracing_enter_root_frame':
    /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/timer.h:79:13: error: impossible constraint in 'asm'
                 asm volatile("rdtsc" : "=a" (a), "=d" (d));
                 ^~~
    /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/timer.h:79:13: error: impossible constraint in 'asm'
                 asm volatile("rdtsc" : "=a" (a), "=d" (d));
                 ^~~
    In file included from /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/tracing.h:1:0,
                     from /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/tideways_xhprof.c:13:
    /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/tideways_xhprof.c: In function 'tideways_xhprof_execute_ex':
    /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/timer.h:79:13: error: impossible constraint in 'asm'
                 asm volatile("rdtsc" : "=a" (a), "=d" (d));
                 ^~~
    /home/buildozer/aports/testing/php7-tideways_xhprof/src/php-xhprof-extension-5.0-beta2/timer.h:79:13: error: impossible constraint in 'asm'
                 asm volatile("rdtsc" : "=a" (a), "=d" (d));
                 ^~~
    make: *** [Makefile:196: tracing.lo] Error 1