community/py3-augeas: upgrade to 1.2.0, build with gpep517
Resolves build warning:
```
/usr/lib/python3.14/site-packages/setuptools/__init__.py:92: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.

        This deprecation is overdue, please update your project and remove deprecated
        calls to avoid build errors in the future.
        ********************************************************************************
```

Resolves test failure with python 3.14:
```
file augeas.py (for module augeas) not found
generating cffi module 'build/lib/augeas.py'
Traceback (most recent call last):
  File "/tmp/src/python-augeas-1.1.0/test/test_augeas.py", line 257, in <module>
    __result = __testRunner.run(getsuite())
                                ~~~~~~~~^^
  File "/tmp/src/python-augeas-1.1.0/test/test_augeas.py", line 252, in getsuite
    suite = unittest.makeSuite(TestAugeas, 'test')
            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/unittest/__init__.py", line 80, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'unittest' has no attribute 'makeSuite'
```

Removed patch, dlopen not used in this release.

Ref: #18025