Revert "main/fontconfig: don't update font-cache as root"
This broke builders with the error:

fontconfig-2.15.0-r4.trigger: /usr/share/fonts/opensans: failed to write cache
ERROR: fontconfig-2.15.0-r4.trigger: exited with error 9

This reverts commit 8f0a949bce597b1e9174a81e3bab560b768e28a6.