community/ghc: fix docs build with sphinx 9.1.0
Update the users guide theme layout to build with sphinx 9.1.0.

Error found on the 3.24 builders.

```
Traceback
=========

      File "/usr/lib/python3.14/site-packages/sphinx/builders/html/__init__.py", line 1238, in handle_page
        raise ThemeError(msg) from exc
    sphinx.errors.ThemeError: An error happened in rendering the page 9.10.1-notes.
    Reason: TypeError("argument of type '_CascadingStyleSheet' is not a container or iterable")

The full traceback has been saved in:
/tmp/sphinx-err-cmoa3rpt.log

To report this error to the developers, please open an issue at <https://github.com/sphinx-doc/sphinx/issues/>. Thanks!
Please also report this if it was a user error, so that a better error message can be provided next time.
Running Sphinx v9.1.0
```