main/mkinitfs: Add busybox to makedepends_host
When bootstrapping aarch64, mkinitfs fails to build with the following
error

```
+ apkbuildname mkinitfs
+ local repo=mkinitfs
+ local pkg=mkinitfs
+ [ mkinitfs = mkinitfs ]
+ repo=main
+ echo /home/builder/aports-edge/main/mkinitfs/APKBUILD
+ CHOST=aarch64 BOOTSTRAP=bootimage APKBUILD=/home/builder/aports-edge/main/mkinitfs/APKBUILD abuild -r
>>> mkinitfs: abuild 3.0.2-r0
>>> mkinitfs: Checking sanity of /home/builder/aports-edge/main/mkinitfs/APKBUILD...
>>> mkinitfs: Analyzing dependencies...
ERROR: unsatisfiable constraints:
  /bin/sh (virtual):
    provided by: busybox
    required by: kmod-24-r0[/bin/sh]
                 kmod-24-r0[/bin/sh]
  .makedepends-mkinitfs-0:
    masked in: cache
    satisfies: world[.makedepends-mkinitfs]
>>> ERROR: mkinitfs: all failed
>>> mkinitfs: Uninstalling dependencies...
```

Adding busybox to makedepends_host fixes this issue.

Signed-off-by: Rajiv Ranganath <rajiv.ranganath@atihita.com>