community/shfmt: upgrade to 3.6.0
Remove the 1.18 compatibility fix as it actually causes breakage now.

# mvdan.cc/sh/v3/cmd/shfmt [mvdan.cc/sh/v3/cmd/shfmt.test]
cmd/shfmt/main_test.go:28:3: unknown field 'RequireExplicitExec' in struct literal of type testscript.Params
ok  	mvdan.cc/sh/v3/cmd/gosh	0.006s
FAIL	mvdan.cc/sh/v3/cmd/shfmt [build failed]
ok  	mvdan.cc/sh/v3/expand	0.004s
?   	mvdan.cc/sh/v3/fileutil	[no test files]
ok  	mvdan.cc/sh/v3/interp	0.179s
ok  	mvdan.cc/sh/v3/pattern	0.004s
ok  	mvdan.cc/sh/v3/shell	0.024s
ok  	mvdan.cc/sh/v3/syntax	0.713s
ok  	mvdan.cc/sh/v3/syntax/typedjson	0.022s
FAIL
>>> ERROR: shfmt: check failed

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>