community/virt-manager: depend on py3-libvirt, use HTTPS for url
py3-libvirt is required for launch, otherwise one gets the following
error upon launching virt-manager

ImportError: no module named libvirt^