testing/otf: upgrade to 0.5.17
https://github.com/leg100/otf/releases/tag/v0.5.17
https://github.com/leg100/otf/compare/v0.4.9...v0.5.17
https://github.com/leg100/otf/releases/tag/v0.5.0

0.5.13 includes go 1.26 support.

Resolves `TestGetRepoTarball` test error.

```
--- FAIL: TestGetRepoTarball (0.01s)
    client_test.go:60:
          Error Trace:  github.com/leg100/otf/internal/github/client_test.go:60
          Error:        Received unexpected error:
                        unexpected status code: 307 Temporary Redirect
          Test:         TestGetRepoTarball
FAIL
FAIL  github.com/leg100/otf/internal/github 0.418s
```