community/py3-rencode: upgrade to 1.0.8, build with gpep517
https://github.com/aresch/rencode/releases/tag/v1.0.8
https://github.com/aresch/rencode/releases/tag/v1.0.7

1.0.7 introduced a new build file for the cython extension and
`pyproject.toml` which replaced `setup.py`. Switch to build with gpep517
accordingly.

Upgrade resolves cython build error.

```
Error compiling Cython file:
------------------------------------------------------------
...
cdef object MAX_SIGNED_LONGLONG = int(2**63)
cdef object MIN_SIGNED_LONGLONG = -MAX_SIGNED_LONGLONG

cdef encode(char **buf, unsigned int *pos, data):
    t = type(data)
    if t == int or t == long:
                        ^
------------------------------------------------------------

rencode/rencode.pyx:278:24: undeclared name not builtin: long
Compiling rencode/rencode.pyx because it changed.
[1/1] Cythonizing rencode/rencode.pyx
Traceback (most recent call last):
  File "/home/buildozer/aports/community/py3-rencode/src/rencode-1.0.6/setup.py", line 53, in <module>
    ext_modules = cythonize(ext_modules)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1150, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1294, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: rencode/rencode.pyx
```