community/clazy: depend on clang
This is necessary as correct translation units otherwise may fail:

```
% podman run -it alpine:3.21
/ # apk add -q clazy
/ # echo '#include "xmmintrin.h"' > /tmp/a.cpp
/ # clazy-standalone /tmp/a.cpp
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "/tmp/a.cpp"
No compilation database found in /tmp or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
/tmp/a.cpp:1:10: fatal error: 'xmmintrin.h' file not found
    1 | #include "xmmintrin.h"
      |          ^~~~~~~~~~~~~
1 error generated.
Error while processing /tmp/a.cpp.
```