community/py3-syncer: fix tests with python 3.14
Replace `asyncio.get_event_loop` to fix tests with python 3.14.

Upstream issue: https://github.com/miyakogi/syncer/issues/3

```
 ________________________ TestSyncerPY35.test_deco_async ________________________

 self = <tests.test_syncer.TestSyncerPY35 testMethod=test_deco_async>

     def test_deco_async(self):
         @sync
         async def a():
             return 1
 >       self.assertEqual(a(), 1)
                          ^^^

 tests/test_syncer.py:38:
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 syncer.py:32: in run
     return asyncio.get_event_loop().run_until_complete(f(*args, **kwargs))
            ^^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <asyncio.unix_events._UnixDefaultEventLoopPolicy object at 0x7fa637fd2120>

    def get_event_loop(self):
        """Get the event loop for the current context.

        Returns an instance of EventLoop or raises an exception.
        """
        if self._local._loop is None:
>           raise RuntimeError('There is no current event loop in thread %r.'
                               % threading.current_thread().name)
E           RuntimeError: There is no current event loop in thread 'MainThread'.

/usr/lib/python3.14/asyncio/events.py:715: RuntimeError
```

```
FAILED tests/test_syncer.py::TestSyncerPY35::test_deco_async - RuntimeError: ...
FAILED tests/test_syncer.py::TestSyncerPY35::test_deco_async_args - RuntimeEr...
FAILED tests/test_syncer.py::TestSyncerPY35::test_deco_method - RuntimeError:...
FAILED tests/test_syncer.py::TestSyncerPY35::test_deco_method_args - RuntimeE...
FAILED tests/test_syncer.py::TestSyncerPY35::test_deco_testmethod - RuntimeEr...
FAILED tests/test_syncer.py::TestSyncerPY35::test_failure - RuntimeError: The...
FAILED tests/test_syncer.py::TestSyncerPY35::test_future - RuntimeError: Ther...
FAILED tests/test_syncer.py::TestSyncerPY35::test_wrap_async - RuntimeError: ...
FAILED tests/test_syncer.py::TestSyncerPY35::test_wrap_async_args - RuntimeEr...
FAILED tests/test_syncer.py::TestSyncerPY35::test_wrap_method - RuntimeError:...
FAILED tests/test_syncer.py::TestSyncerPY35::test_wrap_method_args - RuntimeE...
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025