community/appstream: trigger: fix missing exit 0
Turn appstream.post-upgrade and appstream.trigger into symlinks to
appstream.post-install.

Fix for:
  Executing appstream-0.14.6-r1.trigger
  The AppStream system cache was updated, but some components were ignored. Refer to the verbose log for more information.
  ERROR: appstream-0.14.6-r1.trigger: script exited with error 2