community/py3-geotiler: add asyncio provider to checkdepends
Add an asyncio provider to complete `test_tile_io.py` tests.

```
_______________________________ test_fetch_tile ________________________________
[gw33] linux -- Python 3.12.12 /home/buildozer/aports/community/py3-geotiler/src/geotiler-0.15.1/.testenv/bin/python3
async def functions are not natively supported.
You need to install a suitable plugin for your async framework, for example:
  - anyio
  - pytest-asyncio
  - pytest-tornasync
  - pytest-trio
  - pytest-twisted

[...]

FAILED geotiler/tests/test_tile_io.py::test_fetch_tile - Failed: async def fu...
FAILED geotiler/tests/test_tile_io.py::test_fetch_tiles - Failed: async def f...
FAILED geotiler/tests/test_tile_io.py::test_fetch_tile_error - Failed: async ...
```