main/xf86-input-libinput: add missing make dependency
Add eudev-dev as a make dependency to fix build error:
libinput.h:34:21: fatal error: libudev.h: No such file or directory