testing/galera: disable on x86 due to failure to compile tests
galera/tests/defaults_check.cpp: In function 'void fill_in_expected(DefaultsMap&, const char**)':
galera/tests/defaults_check.cpp:129:34: error: too many arguments for format [-Werror=format-extra-args]
  129 |         fail_if(it == map.end(), "Failed to insert KV pair: %s = %s",
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galera/tests/defaults_check.cpp: In function 'void fill_in_real(DefaultsMap&, wsrep_t&)':
galera/tests/defaults_check.cpp:148:34: error: too many arguments for format [-Werror=format-extra-args]
  148 |         fail_if(it == map.end(), "Failed to insert KV pair: %s = %s",
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galera/tests/defaults_check.cpp: In function 'void* recv_func(void*)':
galera/tests/defaults_check.cpp:224:30: error: too many arguments for format [-Werror=format-extra-args]
  224 |     fail_if(WSREP_OK != ret, "recv() returned %d", ret);
      |                              ^~~~~~~~~~~~~~~~~~~~
galera/tests/defaults_check.cpp: In function 'void defaults_fn(int)':
galera/tests/defaults_check.cpp:276:30: error: too many arguments for format [-Werror=format-extra-args]
  276 |     fail_if(WSREP_OK != ret, "connect() returned %d", ret);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~
galera/tests/defaults_check.cpp:299:34: error: too many arguments for format [-Werror=format-extra-args]
  299 |         fail_if(WSREP_OK != ret, "disconnect() returned %d", ret);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
galera/tests/defaults_check.cpp:302:27: error: too many arguments for format [-Werror=format-extra-args]
  302 |         fail_if(0 != ret, "Could not join thread: %d (%s)", ret, strerror(ret));
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galera/tests/defaults_check.cpp:349:34: error: too many arguments for format [-Werror=format-extra-args]
  349 |     fail_if (!err.str().empty(), "Defaults discrepancies detected:\n%s",
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~