testing/zapzap: disable on armv7 due to missing py3-pyqt6-webengine
The dependency is currently unavailable on armv7.

```
ERROR: unable to select packages:
  .makedepends-zapzap-20260524.141830:
    masked in: cache
    satisfies: world[.makedepends-zapzap=20260524.141830]
  py3-pyqt6-webengine (no such package):
    required by: .makedepends-zapzap-20260524.141830[py3-pyqt6-webengine]
```