community/fluidsynth: add depends_libs to makedepends to fix build order
otherwise soundfont-timgm is not guaranteed to exist when setting up new builders:
    >>> carla: Analyzing dependencies...
    ERROR: unable to select packages:
      soundfont-timgm (no such package):
        required by: fluidsynth-libs-2.4.4-r2[soundfont-timgm]