main/git: use system's perl-error
this fixes file conflict:
ERROR: perl-error-0.17021-r0: trying to overwrite usr/share/perl5/vendor_perl/Error.pm owned by perl-git-1.8.5.3-r0.