community/docuum: disable on s390x due to build failure in nix crate
    error[E0428]: the name `fs_type_t` is defined multiple times
      --> /home/buildozer/.cargo/registry/src/index.crates.io-d11c229612889eed/nix-0.27.1/src/sys/statfs.rs:68:1
       |
    66 | type fs_type_t = libc::c_uint;
       | ------------------------------ previous definition of the type `fs_type_t` here
    67 | #[cfg(all(target_os = "linux", target_env = "musl"))]
    68 | type fs_type_t = libc::c_ulong;
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `fs_type_t` redefined here