community/c2rust: upgrade to 0.21.0
https://github.com/immunant/c2rust/releases/tag/v0.21.0

0.21.0 sets cmake minimum version to 3.5 to rebuild with cmake >= 4 and
includes support for llvm 20 and 21.

Add samurai to makedepends due to abuild setting ninja as default cmake
generator and build with llvm 21.

Refresh `0001-link-clang-dynamic.patch` for 0.21.0.

Fixes cmake build error:

```
error: failed to run custom build command for `c2rust-ast-exporter v0.20.0 (/home/buildozer/aports/community/c2rust/src/c2rust-0.20.0/c2rust-ast-exporter)`

Caused by:
  process didn't exit successfully: `/home/buildozer/aports/community/c2rust/src/c2rust-0.20.0/target/release/build/c2rust-ast-exporter-82bf8a990209a687/build-script-build` (exit status: 101)
  --- stdout

  [...]

  -- Configuring incomplete, errors occurred!

  --- stderr
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 has been removed from CMake.

    Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
    to tell CMake that the project requires at least <min> but has been updated
    to work with policies introduced by <max> or earlier.

    Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```