community/py3-dns-lexicon: add missing dependency on py3-dnspython
  File "/usr/lib/python3.12/site-packages/lexicon/client.py", line 12, in <module>
    import dns.resolver
ModuleNotFoundError: No module named 'dns'