community/xdg-desktop-portal-lxqt: fix build with qt6 6.10.0
Rebuild against qt6 6.10.0 and fix error due to private headers not
found.

```
In file included from /home/buildozer/aports/community/xdg-desktop-portal-lxqt/src/xdg-desktop-portal-lxqt-1.2.0/src/filedialoghelper.h:28,
                 from /home/buildozer/aports/community/xdg-desktop-portal-lxqt/src/xdg-desktop-portal-lxqt-1.2.0/src/filedialoghelper.cpp:28:
/usr/include/libfm-qt6/filedialoghelper.h:5:10: fatal error: qpa/qplatformdialoghelper.h: No such file or directory
    5 | #include <qpa/qplatformdialoghelper.h> // this private header is subject to changes
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```