community/calls: upgrade to 0.2.0
Calls is broken since its dependency libcallaudio-0 has been upgraded to
libcallaudio-0.1. Upgrade to latest version and add patches from
upstream MR on top to build against libcallaudio-0.1.

Fixes:
  / # apk add calls
  ERROR: unable to select packages:
    so:libcallaudio-0.so.0 (no such package):
      required by: calls-0.1.9-r0[so:libcallaudio-0.so.0]

Related: https://source.puri.sm/Librem5/calls/-/merge_requests/230