community/gossip: upgrade to 0.14.0_git20250820
Unlock 3.24 builder, error log:
```
    Updating git repository `https://github.com/mikedilger/rust-lightning`
error: failed to get `lightning-invoice` as a dependency of package `nostr-types v0.8.0-unstable (https://github.com/mikedilger/nostr-types?rev=a4d5c8f94b19c1306edcfeea51644541b02172bd#a4d5c8f9)`
    ... which satisfies git dependency `nostr-types` (locked to 0.8.0-unstable) of package `gossip-lib v0.14.0 (/home/alpine/aports/community/gossip/src/gossip-0.14.0/gossip-lib)`

Caused by:
  failed to load source for dependency `lightning-invoice`

Caused by:
  unable to update https://github.com/mikedilger/rust-lightning?rev=7a62cb4106d449bc4d1724920b73918d501bb3a9#7a62cb41
```