testing/linkquisition: add missing check dependencies
In addition to 3519512f32e358d068bcccac161a1a88b0f33c41.

```
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from ../go/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240306074159-ea2d69986ecb/c_glfw.go:4:
./glfw/src/x11_platform.h:45:10: fatal error: X11/extensions/Xinerama.h: No such file or directory
   45 | #include <X11/extensions/Xinerama.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
FAIL    github.com/strobotti/linkquisition/cmd [build failed]
```