main/tevent: fix public header
sys/types.h is needed due to:

/usr/include/tevent.h:1440:8: error: unknown type name 'pid_t'
        pid_t *pid,
        ^~~~~
/usr/include/tevent.h:1519:8: error: unknown type name 'pid_t'
        pid_t pid,
        ^~~~~