community/py3-lsp-server: replace py3-qt5 with py3-qt6 in checkdepends
Resolve error in `test_pyqt_completion` test on the 3.23 builders.

```
    @pytest.mark.skipif(
        PY2 or (sys.platform.startswith("linux") and os.environ.get("CI") is not None),
        reason="Test in Python 3 and not on CIs on Linux because wheels don't work on them.",
    )
    def test_pyqt_completion(config, workspace) -> None:
        # Over 'QA' in 'from PyQt6.QtWidgets import QApplication'
        doc_pyqt = "from PyQt6.QtWidgets import QA"
        com_position = {"line": 0, "character": len(doc_pyqt)}
        doc = Document(DOC_URI, workspace, doc_pyqt)
        completions = pylsp_jedi_completions(config, doc, com_position)

>       assert completions is not None
E       assert None is not None

test/plugins/test_completion.py:291: AssertionError
```