community/electrs: upgrade to 0.10.10
https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md

Temporarily set `CXXFLAGS` to include int types, resolving build errors
with gcc 15.

```
warning: electrs-librocksdb-sys@0.9.0-e3+7.8.3: In file included from rocksdb/db/blob/blob_file_meta.cc:6:
warning: electrs-librocksdb-sys@0.9.0-e3+7.8.3: rocksdb/db/blob/blob_file_meta.h:28:7: error: 'uint64_t' has not been declared
warning: electrs-librocksdb-sys@0.9.0-e3+7.8.3:    28 |       uint64_t blob_file_number, uint64_t total_blob_count,
warning: electrs-librocksdb-sys@0.9.0-e3+7.8.3:       |       ^~~~~~~~
warning: electrs-librocksdb-sys@0.9.0-e3+7.8.3: rocksdb/db/blob/blob_file_meta.h:15:1: note: 'uint64_t' is defined in header
'<cstdint>'; this is probably fixable by adding '#include <cstdint>'
warning: electrs-librocksdb-sys@0.9.0-e3+7.8.3:    14 | #include "rocksdb/rocksdb_namespace.h"
warning: electrs-librocksdb-sys@0.9.0-e3+7.8.3:   +++ |+#include <cstdint>
```