community/py3-patchworklib: upgrade to 0.6.5
https://github.com/ponnhide/patchworklib#news

Fixes a failed test `tests/test_patchworklib.py::test_example_plot`.

```
old_legend = <matplotlib.legend.Legend object at 0x3ff3b86a600>

    def move_legend(self, new_loc, **kws):

[...]

        self._comeback()
        old_legend = self.legend_
>       handles = old_legend.legendHandles
E       AttributeError: 'Legend' object has no attribute 'legendHandles'. Did you mean: 'legend_handles'?

patchworklib/patchworklib.py:3000: AttributeError
```