community/libsmbios: fix test runner with python 3.14
Replace `unittest.makeSuite` function call which was removed in python
>=3.13 to fix running tests.

Error from `test-suite.log`:

```
FAIL: src/pyunit/runtests.sh
============================

Running ALL PYTHON tests.
Traceback (most recent call last):
  File "[...]/src/pyunit/testAll.py", line 39, in <module>
    retval = TestLib.runTests( tests )
  File "[...]/pyunit/TestLib.py", line 29, in runTests
    temp = unittest.makeSuite( i, testToRun )
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/unittest/__init__.py", line 80, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'unittest' has no attribute 'makeSuite'
FAIL src/pyunit/runtests.sh (exit status: 1)
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18143