Revert "testing/coccinelle: new aport"
This reverts commit 4c478cde8edbde2e4c258d1c0fa8620de894684e.

Fails to build on the builders and blocks the queue:

    ocamlfind ocamlopt -c  -bin-annot -no-alias-deps -I . stdcompat__arg_s.mli -o stdcompat__arg_s.cmi
    File "stdcompat__arg_s.mli", lines 3-17, characters 0-38:
     3 | type spec = Arg.spec =
     4 |   | Unit of (unit -> unit)
     5 |   | Bool of (bool -> unit)
     6 |   | Set of bool ref
     7 |   | Clear of bool ref
    ...
    14 |   | Tuple of spec list
    15 |   | Symbol of string list * (string -> unit)
    16 |   | Rest of (string -> unit)
    17 |   | Expand of (string -> string array).
    Error: This variant or record definition does not match that of type Arg.spec
           Constructors number 14 have different names, Rest_all and Expand.

Also there's some binary file committed into the repository: SCORE_expected.sexp!