testing/pspp: fix build with gettext 1.0
Remove xgettext check in configure, no longer needed for gettext >0.20.
Resolves configure error with gettext 1.0.

```
configure: error: The following required packages are not installed.
You must install them before PSPP can be built:
  xgettext version 0.20 or greater
>>> ERROR: pspp: build failed
```