community/py3-asyncpg: skip failing test
The `test_connect_params` test is broken due to changes in URI parsing
of multiple hosts containing IPv6 addresses and is temporarily disabled
upstream. Skip the test until it is fixed upstream.

```
____________________ TestConnectParams.test_connect_params _____________________
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/home/buildozer/aports/community/py3-asyncpg/src/asyncpg-0.30.0/tests/test_connect.py", line 1237, in test_connect_params
    self.run_testcase(testcase)
  File "/home/buildozer/aports/community/py3-asyncpg/src/asyncpg-0.30.0/tests/test_connect.py", line 1154, in run_testcase
    addrs, params = connect_utils._parse_connect_dsn_and_args(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buildozer/aports/community/py3-asyncpg/src/asyncpg-0.30.0/testenv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 280, in _parse_connect_dsn_and_args
    parsed = urllib.parse.urlparse(dsn)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/parse.py", line 395, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/parse.py", line 516, in urlsplit
    _check_bracketed_netloc(netloc)
  File "/usr/lib/python3.12/urllib/parse.py", line 451, in _check_bracketed_netloc
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

Upstream issue: https://github.com/MagicStack/asyncpg/issues/1236
Related PR: https://github.com/MagicStack/asyncpg/pull/1244