community/py3-adapt-parser: add py3-six to depends
The dependency was previously included indirectly via py3-automat
(py3-pyee -> py3-twisted -> py3-automat -> py3-six), but no longer used
by the latter (per abae8421bd968b61a7bf0e0424e19eb19b0a5f54).

Add to depends as it is imported at runtime, for example:

```
 >>> from adapt.engine import IntentDeterminationEngine
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/lib/python3.12/site-packages/adapt/engine.py", line 18, in <module>
     from adapt.entity_tagger import EntityTagger
   File "/usr/lib/python3.12/site-packages/adapt/entity_tagger.py", line 17, in <module>
     from six.moves import xrange
 ModuleNotFoundError: No module named 'six'
```

Resolves failed tests due to missing module.

```
ImportError while importing test module '/home/buildozer/aports/community/py3-adapt-parser/src/adapt-release-v1.0.0/test/ContextManagerIntegrationTest.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test/ContextManagerIntegrationTest.py:16: in <module>
    from adapt.context import ContextManager
adapt/context.py:19: in <module>
    from six.moves import xrange
E   ModuleNotFoundError: No module named 'six'

[...]

ERROR test/ContextManagerIntegrationTest.py
ERROR test/ContextManagerTest.py
ERROR test/DomainIntentEngineTest.py
ERROR test/EntityExpanderTest.py
ERROR test/EntityTaggerTest.py
ERROR test/IntentEngineTest.py
ERROR test/IntentTest.py
```