main/libical: fix db.h: No such file or directory
Make libical-dev depend on db-dev, so db.h is available when building
against libical-dev.

Fix this error when building programs that depend on libical-dev:

In file included from /home/pmos/build/src/kcalcore-18.12.3/src/icalformat.cpp:45:
/usr/include/libical/icalss.h:492:10: fatal error: db.h: No such file or directory
 #include <db.h>
          ^~~~~~