community/folks: disable on s390x due to tracker
```
>>> folks: Analyzing dependencies...
ERROR: unable to select packages:
  tracker-dev (no such package):
    required by: .makedepends-folks-20201228.124439[tracker-dev]
>>> ERROR: folks: builddeps failed
```