community/kapp: upgrade to 0.65.0
Increase test timeouts even more:

```
    change_graph_cf_for_k8s_test.go:40:
        	Error Trace:	carvel.dev/kapp/pkg/kapp/diffgraph/change_graph_cf_for_k8s_test.go:40
        	Error:      	"4.570000995s" is not less than "2s"
        	Test:       	TestChangeGraphCFForK8sUpsert
        	Messages:   	Graph build took too long
```