community/easypki: disable on mips64 due to build failures
```
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/bolt_unix.go:62:15: undefined: maxMapSize
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/db.go:101:13: undefined: maxMapSize
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/db.go:317:12: undefined: maxMapSize
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/db.go:335:10: undefined: maxMapSize
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/db.go:336:8: undefined: maxMapSize
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/freelist.go:165:19: undefined: maxAllocSize
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/freelist.go:169:13: undefined: maxAllocSize
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/freelist.go:194:12: undefined: maxAllocSize
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/freelist.go:197:7: undefined: maxAllocSize
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/freelist.go:198:12: undefined: maxAllocSize
../../../../../go/pkg/mod/github.com/boltdb/bolt@v1.2.2-0.20160719165138-5cc10bbbc5c1/freelist.go:198:12: too many errors
```