testing/perl-file-mmagic-xs: build with -std=gnu17
The C source implements a method of function overloading which is no
longer supported in C23. Use -std=gnu17 until the macros are updated.

Example errors:

```
src/MMagicST.c:41:5: error: initialization of 'int (*)(void)' from incompatible pointer type 'int (*)(long int,  long int)' [-Wincompatible-pointer-types]
   41 |     numcmp,
      |     ^~~~~~
src/MMagicST.c:41:5: note: (near initialization for 'type_numhash.compare')
src/MMagicST.c:38:12: note: 'numcmp' declared here
   38 | static int numcmp(long, long);
      |            ^~~~~~
src/MMagicST.c:42:5: error: initialization of 'int (*)(void)' from incompatible pointer type 'int (*)(long int)' [-Wincompatible-pointer-types]
   42 |     numhash,
      |     ^~~~~~~
src/MMagicST.c:42:5: note: (near initialization for 'type_numhash.hash')
src/MMagicST.c:39:12: note: 'numhash' declared here
   39 | static int numhash(long);
      |            ^~~~~~~
src/MMagicST.c:48:5: error: initialization of 'int (*)(void)' from incompatible pointer type 'int (*)(const char *, const char *)' [-Wincompatible-pointer-types]
   48 |     strcmp,
      |     ^~~~~~
src/MMagicST.c:48:5: note: (near initialization for 'type_strhash.compare')
In file included from /usr/include/fortify/string.h:23,
                 from src/MMagicST.c:10:
/usr/include/string.h:39:5: note: 'strcmp' declared here
   39 | int strcmp (const char *, const char *);
      |     ^~~~~~
src/MMagicST.c:49:5: error: initialization of 'int (*)(void)' from incompatible pointer type 'int (*)(const char *)' [-Wincompatible-pointer-types]
   49 |     strhash,
      |     ^~~~~~~
src/MMagicST.c:49:5: note: (near initialization for 'type_strhash.hash')
src/MMagicST.c:46:12: note: 'strhash' declared here
   46 | static int strhash(const char *);
      |            ^~~~~~~
```