main/freeradius: fix build with python 3.14
Fix build error from calls to functions removed in python >=3.13. Error
found on the edge builders.

```
src/modules/rlm_python3/rlm_python3.c: In function 'python_interpreter_free':
src/modules/rlm_python3/rlm_python3.c:692:9: error: implicit declaration of function 'PyEval_AcquireLock'; did you mean 'PyEval_AcquireThread'? [-Wimplicit-function-declaration]
  692 |         PyEval_AcquireLock();
      |         ^~~~~~~~~~~~~~~~~~
      |         PyEval_AcquireThread
src/modules/rlm_python3/rlm_python3.c:695:9: error: implicit declaration of function 'PyEval_ReleaseLock'; did you mean 'PyEval_ReleaseThread'? [-Wimplicit-function-declaration]
  695 |         PyEval_ReleaseLock();
      |         ^~~~~~~~~~~~~~~~~~
```