main/perl-digest-md5: prevent conflict with perl-doc
Fixes the following upgrade error:

  ERROR: perl-digest-md5-doc-2.58-r0: trying to overwrite
    usr/share/man/man3/Digest::MD5.3pm.gz owned by perl-doc-5.32.1-r0.