testing/warzone2100: fix build with gcc 15
Add missing header includes to fix build error.

```
In file included from /home/buildozer/aports/testing/warzone2100/src/warzone2100/3rdparty/SQLiteCpp/include/SQLiteCpp/Column.h:14,
                 from /home/buildozer/aports/testing/warzone2100/src/warzone2100/3rdparty/SQLiteCpp/include/SQLiteCpp/Database.h:14,
                 from /home/buildozer/aports/testing/warzone2100/src/warzone2100/3rdparty/SQLiteCpp/src/Transaction.cpp:13:
/home/buildozer/aports/testing/warzone2100/src/warzone2100/3rdparty/SQLiteCpp/include/SQLiteCpp/Statement.h:128:39: error: 'int32_t' does not name a type
  128 |     void bind(const int aIndex, const int32_t       aValue);
      |                                       ^~~~~~~
/home/buildozer/aports/testing/warzone2100/src/warzone2100/3rdparty/SQLiteCpp/include/SQLiteCpp/Statement.h:20:1: note: 'int32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   19 | #include <memory>
  +++ |+#include <cstdint>
   20 |
```