testing/qt-creator: Disable build on ppc64le
qt-creator currently fails to build on ppc64le due to several errors
like:

 language/language.cpp:242:12: error: the compiler can assume that the address of 'a' will always evaluate to 'true' [-Werror=address]
     if (!!&a != !!&b)

Since this is more a desktop package, skipping it on ppc64le for now.