community/nodeinfo: set builddir
Set `builddir` and update source path in the install command accordingly
so the working directory path can be found.

```
/usr/bin/abuild: cd: line 20: can't cd to nodeinfo-go/cli: No such file or directory
>>> ERROR: nodeinfo: build failed
```