main/llvm10: disable on riscv64 due to FTBFS
/usr/lib/gcc/riscv64-alpine-linux-musl/10.3.1/../../../../riscv64-alpine-linux-musl/bin/ld: CMakeFiles/dsymutil.dir/dsymutil.cpp.o: in function `.L0 ':dsymutil.cpp:(.text._ZZ4mainENKUlSt10shared_ptrIN4llvm14raw_fd_ostreamEENS0_8dsymutil11LinkOptionsEE_clES2_S4_+0x58): undefined reference to `__atomic_fetch_and_1'
/usr/lib/gcc/riscv64-alpine-linux-musl/10.3.1/../../../../riscv64-alpine-linux-musl/bin/ld: dsymutil.cpp:(.text._ZZ4mainENKUlSt10shared_ptrIN4llvm14raw_fd_ostreamEENS0_8dsymutil11LinkOptionsEE_clES2_S4_+0x286): undefined reference to `__atomic_fetch_and_1'
collect2: error: ld returned 1 exit statusmake[2]: *** [tools/dsymutil/CMakeFiles/dsymutil.dir/build.make:226: bin/dsymutil] Error 1
make[1]: *** [CMakeFiles/Makefile2:22683: tools/dsymutil/CMakeFiles/dsymutil.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....