testing/weston: fix build
1. New makedepends needed, because mesa-libwayland-egl does not exist
   anymore (see 257a236 and 4f8b36b): wayland-libs-egl wayland-dev
   This fixes configure errors:

checking for EGL_TESTS... no
configure: error: Package requirements (egl glesv2 wayland-client wayland-egl) were not met:

Package 'wayland-client', required by 'virtual:world', not found
Package 'wayland-egl', required by 'virtual:world', not found

2. Disable RDP backend, because Weston source is incompatible with
   freerdp 2.0.0. This avoids compilation errors like this one:

libweston/compositor-rdp.c:193:5: error: 'SURFACE_BITS_COMMAND {aka struct _SURFACE_BITS_COMMAND}' has no member named 'bpp';