main/py3-future: add missing dependency
Before this change:

    $ dabuild sh
    $ sudo apk add py3-future >/dev/null && futurize --version
    Traceback (most recent call last):
      File "/usr/bin/futurize", line 6, in <module>
        from pkg_resources import load_entry_point
    ModuleNotFoundError: No module named 'pkg_resources'

This change adds py3-setuptools as a runtime dependency because pkg_resources is
imported by a file installed into /usr/bin/:

    $ grep pkg_resources /usr/bin/futurize
    from pkg_resources import load_entry_point

pkg_resources is part of py3-setuptools:

    $ apk info -L py3-setuptools | grep pkg_resources/__init__.py
    usr/lib/python3.8/site-packages/pkg_resources/__init__.py

After this change:

    $ dabuild sh
    $ sudo apk add py3-future >/dev/null && futurize --version
    0.18.2