main/py3-tappy: add missing dependency
Before this change:

    $ dabuild sh
    $ sudo apk add py3-tappy >/dev/null && tappy --help
    Traceback (most recent call last):
      File "/usr/bin/tappy", line 6, in <module>
        from pkg_resources import load_entry_point
    ModuleNotFoundError: No module named 'pkg_resources'

This change adds py3-setuptools as a runtime dependency because
pkg_resources is imported by a file installed into /usr/bin/:

    $ grep pkg_resources /usr/bin/tappy
    import pkg_resources

pkg_resources is part of py3-setuptools:

    $ apk info -L py3-setuptools | grep pkg_resources/__init__.py
    usr/lib/python3.8/site-packages/pkg_resources/__init__.py

After this change:

    $ dabuild sh
    $ sudo apk add py3-tappy >/dev/null && tappy --help
    usage: tappy [-h] [-v] [FILE [FILE ...]]

    A TAP consumer for Python

    positional arguments:
      FILE           A file containing TAP output. Any directories listed will be scanned for files to
                     include as TAP files.

    optional arguments:
      -h, --help     show this help message and exit
      -v, --verbose  use verbose messages

    When no files are given or a dash (-) is used for the file name, tappy will read a TAP stream from
    STDIN.