community/dpns: disable on ppc64le due to missing dependency dpns
>>> dpns: Building community/dpns 0.4-r0 (using abuild 3.7.0_rc1-r2) started Mon, 21 Dec 2020 16:20:19 +0000
>>> dpns: Checking sanity of /home/buildozer/aports/community/dpns/APKBUILD...
>>> dpns: Analyzing dependencies...
ERROR: unable to select packages:
  tini-static (no such package):
    required by: docker-engine-19.03.14-r1[tini-static]
>>> ERROR: dpns: builddeps failed
>>> dpns: Uninstalling dependencies...
ERROR: No such package: .makedepends-dpns