testing/py3-unearth: upgrade to 0.18.2
https://github.com/frostming/unearth/releases/tag/0.18.2
https://github.com/frostming/unearth/releases/tag/0.18.1

Fix test errors in `tests/test_evaluator.py` with packaging >=26.

```
_________________________________ test_evaluate_packages_matching_version[8.0.0dev0->=7-None-False] __________________________________

version = '8.0.0dev0', requires = '>=7', allow_prereleases = None, expected = False

    @pytest.mark.parametrize(
        "version,requires,allow_prereleases,expected",
        [
            ("8.1.3", ">=8.0", None, True),
            ("7.1", ">=8.0", None, False),
            ("8.0.0a0", ">=8.0.0dev0", None, True),
            ("8.0.0dev0", ">=7", None, False),
            ("8.0.0dev0", ">=7", True, True),
            ("8.0.0a0", "", None, False),
            ("8.0.0a0", ">=8.0.0dev0", False, False),
        ],
    )
    def test_evaluate_packages_matching_version(
        version, requires, allow_prereleases, expected
    ):
        requirement = Requirement(f"click{requires}")
        link = Link(f"https://test.pypi.org/packages/source/c/click/click-{version}.tar.gz")
        package = Package("click", version, link)
>       assert evaluate_package(package, requirement, allow_prereleases) is expected
E       AssertionError: assert True is False
E        +  where True = evaluate_package(Package(name='click', version='8.0.0dev0'), <Requirement('click>=7')>, None)

tests/test_evaluator.py:266: AssertionError

[...]

FAILED tests/test_evaluator.py::test_evaluate_packages_matching_version[8.0.0dev0->=7-None-False] - AssertionError: assert True is False
FAILED tests/test_evaluator.py::test_evaluate_packages_matching_version[8.0.0a0--None-False] - AssertionError: assert True is False
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025