main/ldb: downgrade to 1.1.31
samba 4.6.* does not build with 1.2:

  /usr/include/ldb_module.h:68:2: error: #error "Samba < 4.7 is not
  compatible with this version of ldb due to assumptions around read
  locks"