testing/dart: include lib/
When trying to build dart-sass-embedded, files from this directory are required:
> Error: SDK summary not found: /usr/lib/dart/lib/_internal/vm_platform_strong.dill.