community/py3-pytest-asyncio: upgrade to 0.21.2
Pytest 8.2.0 compatibility upgrade, fixes error
seen while building py3-fakeredis & py3-structlog:

E       AttributeError: 'FixtureDef' object has no attribute 'unittest'

Relevant issue: https://github.com/pytest-dev/pytest/issues/12269