testing/beancount: move py3-pytest to depends
The bean-file command which is a part of this package uses pytest at run
time. It is used indirectly through
<https://bitbucket.org/blais/beancount/src/default/beancount/ingest/__init__.py>
which is installed to
`usr/lib/python3.8/site-packages/beancount/ingest/__init__.py` and uses
pytest at line 13.

Before this change:

1. Install beancount: `sudo apk add beancount`
2. Check that `py3-pytest` is not installed: `apk list --installed
   '*pytest*'`
3. Running `/usr/bin/bean-file` gives the output below:

```
Traceback (most recent call last):
  File "/usr/bin/bean-file", line 4, in <module>
    from beancount.ingest.file import main; main()
  File "/usr/lib/python3.8/site-packages/beancount/ingest/__init__.py", line 13, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

After this change `/usr/bin/bean-file` behaves as expected.