testing/asteroid-settings: disable on riscv64
The `libqofono` -> `nemo-qml-plugin-systemsettings` dependencies are
currently unavailable on riscv64. Error found on the edge riscv64
builder.

```
ERROR: unable to select packages:
  .makedepends-asteroid-settings-20260518.220742:
    masked in: cache
    satisfies: world[.makedepends-asteroid-settings=20260518.220742]
  nemo-qml-plugin-systemsettings (no such package):
    required by: .makedepends-asteroid-settings-20260518.220742[nemo-qml-plugin-systemsettings]
```

Refs:
976bbc064aff73f135b9004199f9907eb40562d1
26098e4343b8aa8f701ec914d9dd33a24a82520d