community/py3-sphinx-autobuild: add missing dependnecies
sphinx-autobuild fails to run with:

    Traceback (most recent call last):
      File "/usr/bin/sphinx-autobuild", line 5, in <module>
        from sphinx_autobuild.__main__ import main
      File "/usr/lib/python3.12/site-packages/sphinx_autobuild/__main__.py", line 11, in <module>
        import uvicorn
    ModuleNotFoundError: No module named 'uvicorn'

After installing uvicorn, it fails with:

    Traceback (most recent call last):
      File "/usr/bin/sphinx-autobuild", line 5, in <module>
        from sphinx_autobuild.__main__ import main
      File "/usr/lib/python3.12/site-packages/sphinx_autobuild/__main__.py", line 15, in <module>
        from starlette.applications import Starlette
    ModuleNotFoundError: No module named 'starlette'

After installing py3-starlette, it fails with

    Traceback (most recent call last):
      File "/usr/bin/sphinx-autobuild", line 5, in <module>
        from sphinx_autobuild.__main__ import main
      File "/usr/lib/python3.12/site-packages/sphinx_autobuild/__main__.py", line 24, in <module>
        from sphinx_autobuild.server import RebuildServer
      File "/usr/lib/python3.12/site-packages/sphinx_autobuild/server.py", line 9, in <module>
        import watchfiles
    ModuleNotFoundError: No module named 'watchfiles'

It works after installing py3-watchfiles.