community/lnav: add missing dependency on tzdata
Whenever pressing `:` in lnav, the program exits. Running lnav with `-d
lnav.debug`, reveals the issue:

> E t8 lnav_log.cc:650 error: discover_tz_dir failed to find zoneinfo

It exits because it cannot find zoneinfo. Installing tzdata fixes the
issue.