community/lcov2cobertura: remove deprecated lints to fix build
Extend the existing list of deprecated lints being removed to fix build.
An upstream commit removed some but not all of the blocking ones, so add
to the existing list for now.

```
error: lint `unsupported_calling_conventions` has been removed: converted into hard error
  |
  = note: requested on the command line with `-F unsupported_calling_conventions`
  = note: `-D renamed-and-removed-lints` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(renamed_and_removed_lints)]`

error: lint `deprecated_cfg_attr_crate_type_name` has been removed: converted into hard error, see issue #91632 <https://github.com/rust-lang/rust/issues/91632> for more information
  |
  = note: requested on the command line with `-F deprecated_cfg_attr_crate_type_name`

error: lint `cenum_impl_drop_cast` has been removed: converted into hard error, see <https://github.com/rust-lang/rust/issues/73333> for more information
  |
  = note: requested on the command line with `-F cenum_impl_drop_cast`

error: could not compile `lcov2cobertura` (lib) due to 3 previous errors
```

See also: https://github.com/mike-kfed/lcov2cobertura/commit/48f7c9a12409b7ea2418e4932d4f182ed9bf061a