testing/kubectl-krew: fix tests due to lingering index cache
> --- FAIL: TestKrewUpdateListsUpgradesAvailable (1.82s)
> [..]
> update_test.go:129: output should not mention update available for "ns"; output=Updated the local copy of plugin index.
> [..]
> FAIL
> FAIL	sigs.k8s.io/krew/integration_test	70.448s