community/py3-google-api-python-client: upgrade to 1.8.2
Also fix missing dependency and enable check().

Before this change:

    $ python3 -c 'import googleapiclient.discovery'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.8/site-packages/googleapiclient/discovery.py", line 49, in <module>
        import google.api_core.client_options
    ModuleNotFoundError: No module named 'google.api_core'

After this change, `python3 -c 'import googleapiclient.discovery'`
succeeds.

Change log:
https://github.com/googleapis/google-api-python-client/blob/master/CHANGELOG.md#182-2020-04-21