community/py3-bayeso: increase test timeout
Increase pytest timeout to help tests complete.

```
   def test_optimize_str_acq():

[...]

        while True:
            # g may become float32 if a user provides a function that calculates
            # the Jacobian in float32 (see gh-18730). The underlying code expects
            # float64, so upcast it
            g = g.astype(np.float64)
            # x, f, g, wa, iwa, task, csave, lsave, isave, dsave = \
>           _lbfgsb.setulb(m, x, low_bnd, upper_bnd, nbd, f, g, factr, pgtol, wa,
                           iwa, task, lsave, isave, dsave, maxls, ln_task)
E           Failed: Timeout >30.0s

/usr/lib/python3.12/site-packages/scipy/optimize/_lbfgsb_py.py:461: Failed

[...]

FAILED tests/common/test_bo_bo_w_tp.py::test_optimize_str_acq - Failed: Timeo...
FAILED tests/common/test_bo_bo_w_gp.py::test_optimize_str_acq - Failed: Timeo...
FAILED tests/common/test_bo_bo_w_tp.py::test_optimize_use_ard - Failed: Timeo...
FAILED tests/common/test_bo_bo_w_gp.py::test_optimize_use_ard - Failed: Timeo...
FAILED tests/common/test_wrappers_bo_function.py::test_run_single_round - Fai...
```