main/weston: fix build
1. New makedepend wayland-dev, because mesa-libwayland-egl does not
   exist anymore (see 257a236 and 4f8b36b):

   This fixes configure errors:

checking for EGL_TESTS... no
configure: error: Package requirements (egl glesv2 wayland-client wayland-egl) were not met:

Package 'wayland-client', required by 'virtual:world', not found
Package 'wayland-egl', required by 'virtual:world', not found

2. Apply @z3ntu's patch to make the RDP backend work with freerdp-2.0.0_rc2.
   This avoids compilation errors like this one:

libweston/compositor-rdp.c:193:5: error: 'SURFACE_BITS_COMMAND {aka struct _SURFACE_BITS_COMMAND}' has no member named 'bpp';