main/strace: upgrade to 6.19
1. https://github.com/strace/strace/releases/tag/v6.19
2. Upgrading version can also fix the build error in strace 6.18 based on kernel 6.18:
```
In file included from evdev.c:22:

xlat/evdev_prop.h:39:3: error: 'INPUT_PROP_HAPTIC_TOUCHPAD' undeclared here (not in a function); did you mean 'INPUT_PROP_BUTTONPAD'?

   39 |  [INPUT_PROP_HAPTIC_TOUCHPAD] = XLAT(INPUT_PROP_HAPTIC_TOUCHPAD),

      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~

      |   INPUT_PROP_BUTTONPAD

xlat/evdev_prop.h:39:3: error: array index in initializer not of integer type

xlat/evdev_prop.h:39:3: note: (near initialization for 'evdev_prop_xdata')
```
ref: https://lkml.indiana.edu/hypermail/linux/kernel/2511.2/04733.html