testing/py3-eradicate: upgrade to 3.0.1
https://github.com/PyCQA/eradicate/releases/tag/3.0.1
https://github.com/PyCQA/eradicate/releases

3.0.1 includes python 3.14 support.

Resolves `AttributeError: 'Constant' object has no attribute 's'` error
when building against python 3.14.

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025