community/py3-ufolib2: upgrade to 0.17.1, fix installer .whl filename
https://github.com/fonttools/ufoLib2/releases/tag/v0.17.1
https://github.com/fonttools/ufoLib2/releases/tag/v0.17.0
https://github.com/fonttools/ufoLib2/releases/tag/v0.16.1

Also fix packaging error due to changed .whl filename with setuptools
>= 75.3.1.

```
FileNotFoundError: [Errno 2] No such file or directory: '.dist/ufoLib2-0.16.0-*.whl'
```