community/awww: revert references to rustix runtime
The `runtime` feature of rustix crate depends on the `linux_raw` backend
and not yet fully supported on some arches. Revert to `std` to retain arch
support.

```
error[E0433]: cannot find `runtime` in `rustix`
   --> daemon/src/wallpaper.rs:315:48
    |
315 |                         match unsafe { rustix::runtime::kernel_fork() } {
    |                                                ^^^^^^^ could not find `runtime` in `rustix`
    |
note: found an item that was configured out
   --> /builds/alpine/aports/community/awww/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.1.4/src/lib.rs:317:9
    |
314 | #[cfg(linux_raw)]
    |       --------- the item is gated here
...
317 | pub mod runtime;
    |         ^^^^^^^
```