testing/sedutil: fix build
Fix build error due to GCC 13 header dependency changes
(https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes):

In file included from ./Common/log.h:45,
                 from LinuxPBA/LinuxPBA.cpp:25:
./Common/DtaOptions.h:33:5: error: 'uint8_t' does not name a type
   33 |     uint8_t password;   /**< password supplied */
      |     ^~~~~~~
./Common/DtaOptions.h:1:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  +++ |+#include <cstdint>
    1 | /* C:B**************************************************************************
./Common/DtaOptions.h:34:9: error: 'uint8_t' does not name a type
   34 |         uint8_t userid;   /**< userid supplied */
      |         ^~~~~~~
./Common/DtaOptions.h:34:9: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
./Common/DtaOptions.h:35:9: error: 'uint8_t' does not name a type
   35 |         uint8_t newpassword;   /**< new password for password change */
      |         ^~~~~~~
./Common/DtaOptions.h:35:9: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
./Common/DtaOptions.h:36:9: error: 'uint8_t' does not name a type
   36 |         uint8_t pbafile;   /**< file name for loadPBAimage command */
      |         ^~~~~~~
./Common/DtaOptions.h:36:9: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
./Common/DtaOptions.h:37:5: error: 'uint8_t' does not name a type
   37 |     uint8_t device;   /**< device name  */
      |     ^~~~~~~
./Common/DtaOptions.h:37:5: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
./Common/DtaOptions.h:38:5: error: 'uint8_t' does not name a type
   38 |     uint8_t action;   /**< option requested */
      |     ^~~~~~~
./Common/DtaOptions.h:38:5: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
./Common/DtaOptions.h:39:9: error: 'uint8_t' does not name a type
   39 |         uint8_t mbrstate;   /**< mbrstate for set mbr commands */
      |         ^~~~~~~
./Common/DtaOptions.h:39:9: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
./Common/DtaOptions.h:40:9: error: 'uint8_t' does not name a type
   40 |         uint8_t lockingrange;  /**< locking range to be manipulated */
      |         ^~~~~~~
./Common/DtaOptions.h:40:9: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
./Common/DtaOptions.h:41:9: error: 'uint8_t' does not name a type
   41 |         uint8_t lockingstate;  /**< locking state to set a lockingrange to */
      |         ^~~~~~~
./Common/DtaOptions.h:41:9: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
./Common/DtaOptions.h:42:9: error: 'uint8_t' does not name a type
   42 |         uint8_t lrstart;                /** the starting block of a lockingrange */
      |         ^~~~~~~
./Common/DtaOptions.h:42:9: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
./Common/DtaOptions.h:43:9: error: 'uint8_t' does not name a type
   43 |         uint8_t lrlength;               /** the length in blocks of a lockingrange */
      |         ^~~~~~~
./Common/DtaOptions.h:43:9: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
./Common/DtaOptions.h:55:1: error: 'uint8_t' does not name a type
   55 | uint8_t DtaOptions(int argc, char * argv[], DTA_OPTIONS * opts);
      | ^~~~~~~
./Common/DtaOptions.h:55:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
make[1]: *** [Makefile:644: LinuxPBA/LinuxPBA.o] Error 1