community/arti: revert upgrade to 1.1.13
The upgrade passed in CI with rust 1.73.0 but is now failing on the
package builders with rust 1.74.1, however not certain it is due to the
rust version.

failures:

---- replay::test::test_partial_write stdout ----
in test runner process, forking..,
reaped actual test process ExitStatus(unix_wait_status(25856)) (expecting signal 12)
thread 'replay::test::test_partial_write' panicked at crates/tor-hsservice/src/replay.rs:514:17:
assertion `left == right` failed
  left: None
 right: Some(12)

This reverts commit 734f954cf46f69a7f271b825f06fc42458df8d0f.