main/qt5-qtbase: rebuild against icu-57.1
ERROR: unsatisfiable constraints:
  icu-libs-56.1-r0:
    conflicts: icu-libs-57.1-r3
    satisfies:
               harfbuzz-icu-1.0.6-r1[so:libicudata.so.56]
               harfbuzz-icu-1.0.6-r1[so:libicuuc.so.56]
               firefox-38.3.0-r1[so:libicui18n.so.56]
               firefox-38.3.0-r1[so:libicuuc.so.56]
               webkit2gtk-2.10.4-r0[so:libicui18n.so.56]
               webkit2gtk-2.10.4-r0[so:libicuuc.so.56]
  icu-libs-57.1-r3:
    conflicts: icu-libs-56.1-r0
    satisfies:
               qt5-qtbase-5.6.1_p1-r0[so:libicui18n.so.57]
               qt5-qtbase-5.6.1_p1-r0[so:libicuuc.so.57]