main/s6-linux-utils: upgrade to 2.6.4.0
Upgraded to fix the rebuild against skalibs 2.14.5.1:
    ```
src/multicall/s6-linux-utils.c:34:13: error: conflicting types for 'main_func'; have 'int(int,  const char * const*, const char * const*)'
   34 | typedef int main_func (int, char const *const *, char const *const *) ;
      |             ^~~~~~~~~
In file included from /usr/include/skalibs/posixplz.h:11,
                 from /usr/include/skalibs/skalibs.h:17,
                 from src/multicall/s6-linux-utils.c:29:
/usr/include/skalibs/functypes.h:67:13: note: previous declaration of 'main_func' with type 'main_func' {aka 'int(const char * const*)'}
   67 | typedef int main_func (char const *const *) ;
      |             ^~~~~~~~~
src/multicall/s6-linux-utils.c:35:20: error: conflicting types for 'main_func_ref'; have 'int (*)(int,  const char * const*, const char * const*)'
   35 | typedef main_func *main_func_ref ;
    ```