community/psmisc: Fix FTBFS on ppc64le
There is an issue with psmisc that fails to build due to names clash.
This is the type of the problem this patch is resolving:

  In file included from /usr/include/sys/user.h:11:0,
                   from peekfd.c:33:
  /usr/include/bits/user.h:1:8: error: redefinition of 'struct pt_regs'
   struct pt_regs {
          ^~~~~~~
  In file included from peekfd.c:30:0:
  /usr/include/asm/ptrace.h:31:8: note: originally defined here
   struct pt_regs {
          ^~~~~~~