community/ocamlbuild: rebuild with reverted ocaml
commit 6f58e167f186 reverted the ocaml version so we need to rebuild
ocamlbuild.

This fixes the error:
Error: /usr/lib/ocaml/ocamlbuild/ocamlbuild_plugin.cmi
       is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.