testing/sequoia-sqv: disable due to build error with nettle
bindgen-wrapper.h:19:10: fatal error: 'nettle/des-compat.h' file not
found
bindgen-wrapper.h:19:10: fatal error: 'nettle/des-compat.h' file not
found, err: true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
()', src/libcore/result.rs:999:5