main/gnokii: build fix for gcc8
This is yet another package that assumes GNU-style inline keyword handling
and fails with the "undefined reference to `foo'" linker error where foo is
some inline function (here local_atoi).

Instead of fixing the source, pass -std=gnu89 in CFLAGS because
1) this is shorter and easier;
2) the project is actually written in GNU C89 dialect;
3) upstream is not active (the last release was in 2011).

With this change in place gnokii-0.6.31-gcc5.patch can be removed,
suggesting the -std=gnu89 approach is also more future-proof for any
further changes in compiler's inliner implementation.