community/R: add musl-dev to -dev dependencies
I might be missing something here and I certainly don't want to add an
unnecessary dependency if there are use-cases for using R-dev without
musl-dev, but I can't figure out how you could actually use R-dev for
anything without musl-dev installed.

The header files installed by R-dev depend on the standard library, so
that any attempt to compile using the R-dev header files will fail with e.g.

    /usr/include/R/Rinternals.h:39:11: fatal error: stdio.h: No such file or directory
       39 | # include <stdio.h>
          |           ^~~~~~~~~