community/xpra: disable on armhf due to build failure
  gcc -DNDEBUG -Os -fomit-frame-pointer -pipe -fPIC -g -Os -fomit-frame-pointer -pipe \
      -fno-strict-aliasing -Os -fomit-frame-pointer -pipe -fPIC -I/usr/include/python2.7 \
      -c xpra/codecs/dec_avcodec2/decoder.c \
      -o build/temp.linux-armv8l-2.7/xpra/codecs/dec_avcodec2/decoder.o -Wl,--as-needed \
      -Wall -Werror -fPIC
  xpra/codecs/dec_avcodec2/decoder.c: In function '__pyx_pf_4xpra_6codecs_12dec_avcodec2_7decoder_7Decoder_init_context':
  xpra/codecs/dec_avcodec2/decoder.c:5551:3: error: 'refcounted_frames' is deprecated [-Werror=deprecated-declarations]
     __pyx_v_self->codec_ctx->refcounted_frames = 1;
     ^~~~~~~~~~~~
  In file included from xpra/codecs/dec_avcodec2/decoder.c:558:0:
  /usr/include/libavcodec/avcodec.h:2694:9: note: declared here
       int refcounted_frames;
           ^~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors
  error: command 'gcc' failed with exit status