community/eog: upgrade to 41.1
Build against libportal.so.1 and upgrade to latest version while at it.

Fix for:
  / # apk add eog
  ERROR: unable to select packages:
    so:libportal.so.0 (no such package):
      required by: eog-41.0-r0[so:libportal.so.0]