testing/ocaml*: change ocaml-cppo-dev to ocaml-cppo
in makedepends, to workaround a problem on ppc64le
only (other architectures do not encounter this)

>>> utop: Analyzing dependencies...
ERROR: unable to select packages:
  ocaml4-impl:Ocamlbuild_plugin:35e029bf41b01449484051712a0cf481 (no such package):
    required by: ocaml-cppo-ocamlbuild-1.6.9-r4[ocaml4-impl:Ocamlbuild_plugin:35e029bf41b01449484051712a0cf481]
  .makedepends-utop-20240324.012502:
    masked in: cache
    satisfies: world[.makedepends-utop=20240324.012502]
>>> ERROR: utop: builddeps failed

ocaml-merlin-extend, utop, and reason do not seem to depend on the
cppo ocamlbuild plugin, so using -dev was probably not intended