community/ncspot: disable on ppc64le due to build failure
    error: failed to run custom build command for `ring v0.16.20`

    Caused by:
      process didn't exit successfully: `/home/buildozer/aports/community/ncspot/src/ncspot-0.9.2/target/release/build/ring-d4a01ac164bad81b/build-script-build` (exit status: 101)
      --- stderr
      thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/buildozer/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace