testing/py3-ecos: add missing build dependency on python3-dev
src/ecosmodule.c:4:10: fatal error: Python.h: No such file or directory
    4 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.