community/nextcloud: fix logrotate config
    error: skipping "/var/log/nextcloud/nextcloud.log" because parent
    directory has insecure permissions (It's world writable or writable
    by group which is not "root") Set "su" directive in config file to
    tell logrotate which user/group should be used for rotation.