community/perl-net-cli-interact: Fix dependency list
This package FTBFS because not all the dependencies were listed
properly. Causing errors like:

 Can't locate object method "log_at" via package "Net::CLI::Interact

 Error:  Can't locate Eval/Closure.pm in @INC

Adding the missing dependencies fixed this problem.