community/py3-referencing: depend on py3-typing-extensions
	>>> import referencing
	[...]
	TypeError: 'default' is an invalid keyword argument for typevar()

Ref: https://github.com/python-jsonschema/referencing/issues/216
Closes: https://gitlab.alpinelinux.org/alpine/aports/-/issues/16877