community/muacme: fix depends on cmd:openssl
It doesn't work...

ERROR: unsatisfiable constraints:
  cmd:openssl (virtual):
    provided by: openssl
    required by: muacme-0.2.0-r0[cmd:openssl]