community/openjdk-mandrel: add missing build dependency on py3-setuptools
Python 3.12 has removed distutils from stdlib causing this error:

  File "/home/buildozer/aports/community/openjdk-mandrel/src/mandrel-23.0.0.0/substratevm/mx.substratevm/mx_substratevm.py", line 36, in <module>
    from distutils.dir_util import mkpath, remove_tree  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'distutils'