community/megasdk: fix tests
Fix error during compiling of tests due to missing header includes.

```
tests/unit/utils_test.cpp: In member function 'virtual void
Filesystem_EscapesReservedCharacters_Test::TestBody()':
tests/unit/utils_test.cpp:86:26: error: 'setfill' is not a member of 'std'
   86 |                  << std::setfill('0')
      |                          ^~~~~~~
tests/unit/utils_test.cpp:32:1: note: 'std::setfill' is defined in
header '<iomanip>'; this is probably fixable by adding '#include <iom
anip>'
   31 | #include <mega/json.h>
  +++ |+#include <iomanip>
   32 |
tests/unit/utils_test.cpp:87:26: error: 'setw' is not a member of 'std'
   87 |                  << std::setw(2)
      |                          ^~~~
tests/unit/utils_test.cpp:87:26: note: 'std::setw' is defined in header
'<iomanip>'; this is probably fixable by adding '#include <iomanip>'
```