community/modemmanager: temporarily disable gtkdoc
Temporarily disable gtkdoc for -doc subpackage due to a rebuild error
at the builder with the gtkdoc helper script. The error:

```
ERROR: Error in gtkdoc helper script:

ERROR: ['/usr/bin/gtkdoc-mkhtml', '--path=/home/buildozer/aports/community/modemmanager/src/ModemManager-1.22.0/docs/reference/api:/home/buildozer/aports/community/modemmanager/src/ModemManager-1.22.0/output/docs/reference/api', 'ModemManager', '../ModemManager-docs.xml'] failed with status 6
warning: failed to load external entity "../../libmm-glib/generated/mm-gdbus-doc-org.freedesktop.ModemManager1.xml"
../xml/ModemManager-dbus-reference.xml:93: element include: XInclude error : could not load ../../libmm-glib/generated/mm-gdbus-doc-org.freedesktop.ModemManager1.xml, and no fallback was found
```

Related upstream issue:
https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/issues/902