testing/kind: move from community
Some recent changes broke cluster creation.

> $ kind create cluster
> Creating cluster "kind" ...
>  ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
>  ✗ Preparing nodes 📦
> Deleted nodes: ["kind-control-plane"]
> ERROR: failed to create cluster: could not find a log line that
> matches "Reached target .*Multi-User System.*|detected cgroup v1"