community/bogofilter: fix fortify-headers.h not found
First detected on build-edge-riscv64 (other archs finished
building bogofilter before fortify-headers 2.3.1 was merged):

/usr/include/fortify/sys/select.h:26:10: fatal error: ../fortify-headers.h: No such file or directory
   26 | #include "../fortify-headers.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~