community/py3-fontmath: fix installer .whl filename
Fix packaging error due to changed .whl filename with setuptools >= 75.3.1.

```
FileNotFoundError: [Errno 2] No such file or directory: '.dist/fontMath-*.whl'
```