community/py3-werkzeug: depend on py3-markupsafe
From 2.2.0 changelog:
  Add MarkupSafe as a dependency and use it to escape values when rendering HTML.

Fix for:
  File "/usr/lib/python3.10/site-packages/werkzeug/exceptions.py", line 49, in <module>
    from markupsafe import escape
    ModuleNotFoundError: No module named 'markupsafe'

Related: https://werkzeug.palletsprojects.com/en/2.2.x/changes/?highlight=markupsafe#version-2-2-0