community/kamoso: disable on mips64
die to missing deps:
ERROR: unsatisfiable constraints:
  so:libHalf-2_4.so.24 (missing):
    required by: gst-plugins-bad-1.16.2-r11[so:libHalf-2_4.so.24]
  so:libIex-2_4.so.24 (missing):
    required by: gst-plugins-bad-1.16.2-r11[so:libIex-2_4.so.24]
  so:libIlmImf-2_4.so.24 (missing):
    required by: gst-plugins-bad-1.16.2-r11[so:libIlmImf-2_4.so.24]