community/bareos: fix bareos-webui - add jansson-dev to makedepends
bareos-webui did not work after login:

    Error: API 2 not available on director.
    Please upgrade to version 15.2.1 or greater and/or compile with
    jansson support.

See similar issue: https://bugs.bareos.org/view.php?id=543