testing/snapper: disable on armhf due to build failure
    /bin/bash ../libtool  --tag=CXX   --mode=link armv6-alpine-linux-musleabihf-g++  -Os -fomit-frame-pointer -pipe -std=c++11 -Wall -Wextra -Wformat=2 -Wnon-virtual-dtor -Wno-unused-parameter  -Wl,--as-needed -lintl -o mksubvolume mksubvolume.o ../snapper/libsnapper.la utils/libutils.la -lbtrfs
    libtool: link: armv6-alpine-linux-musleabihf-g++ -Os -fomit-frame-pointer -pipe -std=c++11 -Wall -Wextra -Wformat=2 -Wnon-virtual-dtor -Wno-unused-parameter -Wl,--as-needed -o .libs/snapper snapper.o types.o commands.o cleanup.o proxy.o proxy-dbus.o proxy-lib.o misc.o errors.o  ../snapper/.libs/libsnapper.so utils/.libs/libutils.a /home/buildozer/aports/testing/snapper/src/snapper-0.5.4/snapper/.libs/libsnapper.so -lboost_thread-mt -lboost_system-mt -lxml2 -lacl -lz -lmount ../dbus/.libs/libdbus.a -lintl -ldbus-1 -lbtrfs
    /usr/lib/gcc/armv6-alpine-linux-musleabihf/6.4.0/../../../../armv6-alpine-linux-musleabihf/bin/ld: ../snapper/.libs/libsnapper.so: undefined reference to symbol '_ZN5boost6system16generic_categoryEv'
    /usr/lib/gcc/armv6-alpine-linux-musleabihf/6.4.0/../../../libboost_system-mt.so: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status