community/ruff: temporarily skip tests on arm
Tests fail with `No file descriptors available` error despite `ulimit`
already increased.

Example error on aarch64:

```
---- unix::symlinked_module_search_path stdout ----
Error: Failed to create directory watcher

Caused by:
    No file descriptors available (os error 24)

failures:
    directory_moved_to_trash
    new_non_project_file
    remove_search_path
    search_path
    submodule_cache_invalidation_deleted
    unix::symlinked_module_search_path

test result: FAILED. 25 passed; 6 failed; 2 ignored; 0 measured; 0 filtered out; finished in 1.71s
```