testing/ostinato: upgrade to 1.1
* Use `make -j1`. Parallel build fails on armv7 with:
  fatal error: protocol.pb.h: No such file or directory
* Add qt5-qtsvg-dev make dependency.
* Remove bug-265.patch, changes have been applied upstream.