community/plasma-desktop: build without kaccounts-integration on armv7 and x86
Temporarily build without kaccounts-integration due to missing .so on
armv7 and x86.

```
>>> plasma-desktop: Analyzing dependencies...
ERROR: unable to select packages:
  so:libQt6WebEngineQuick.so.6 (no such package):
    required by: signon-ui-0.18_git20231016-r0[so:libQt6WebEngineQuick.so.6]
  .makedepends-plasma-desktop-20250813.021005:
    masked in: cache
    satisfies: world[.makedepends-plasma-desktop=20250813.021005]
```