community/py3-readability-lxml: add py3-lxml-html-clean to depends
Fix test failure due to missing import.

```
ImportError: Failed to import test module: test_article_only
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 137, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/build/tests/py3-readability-lxml/src/python-readability-0.8.1/tests/test_article_only.py", line 4, in <module>
    from readability import Document
  File "/home/build/tests/py3-readability-lxml/src/python-readability-0.8.1/readability/__init__.py", line 3, in <module>
    from .readability import Document
  File "/home/build/tests/py3-readability-lxml/src/python-readability-0.8.1/readability/readability.py", line 11, in <module>
    from .cleaners import clean_attributes
  File "/home/build/tests/py3-readability-lxml/src/python-readability-0.8.1/readability/cleaners.py", line 3, in <module>
    from lxml.html.clean import Cleaner
  File "/usr/lib/python3.12/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```