community/py3-pytest-aiohttp: skip test
The `test_warning_for_legacy_mode` test checks a deprecation warning is
emitted for `LEGACY_MODE`. To do so, it runs a subprocess with the
`--asyncio-mode=legacy` option which has since been removed from
pytest-asyncio. Skip test for a mode that is no longer available.

```
_________________________ test_warning_for_legacy_mode _________________________

testdir = <Testdir local('/tmp/pytest-of-buildozer/pytest-24/test_warning_for_legacy_mode0')>

    def test_warning_for_legacy_mode(testdir: pytest.Testdir) -> None:
        testdir.makepyfile(
            """\
    async def test_a():
        pass

    """
        )
        result = testdir.runpytest_subprocess("--asyncio-mode=legacy")
>       result.assert_outcomes(passed=1)

/home/buildozer/aports/community/py3-pytest-aiohttp/src/pytest-aiohttp-1.1.0/tests/test_switch_mode.py:17:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.14/site-packages/_pytest/pytester.py:566: in parseoutcomes
    return self.parse_summary_nouns(self.outlines)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[...]

----------------------------- Captured stdout call -----------------------------
running: /home/buildozer/aports/community/py3-pytest-aiohttp/src/pytest-aiohttp-1.1.0/.testenv/bin/python3 -mpytest --basetemp=/tmp/pytest-of-buildozer/pytest-24/test_warning_for_legacy_mode0/runpytest-0 --asyncio-mode=legacy
     in: /tmp/pytest-of-buildozer/pytest-24/test_warning_for_legacy_mode0
============================= test session starts ==============================
platform linux -- Python 3.14.3, pytest-9.0.3, pluggy-1.6.0
----------------------------- Captured stderr call -----------------------------
ERROR: 'legacy' is not a valid asyncio_mode. Valid modes: auto, strict.
```