community/cassandra-cpp-driver: fix build
The build was emitting an error due to -Werror.

```
/home/devel/aports/community/cassandra-cpp-driver/src/cpp-driver-2.15.2/src/cloud_secure_connection_config.cpp:123:62:
required from here
/home/devel/aports/community/cassandra-cpp-driver/src/cpp-driver-2.15.2/src/third_party/rapidjson/rapidjson/reader.h:1013:53:
error: comparison is always true due to limited range of data type
[-Werror=type-limits]
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/cassandra_static.dir/build.make:238:
src/CMakeFiles/cassandra_static.dir/cloud_secure_connection_config.cpp.o]
Error 1
make[1]: *** [CMakeFiles/Makefile2:258:
src/CMakeFiles/cassandra_static.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
>>> ERROR: cassandra-cpp-driver: build failed
```

Signed-off-by: Gustavo L F Walbon <gwalbon@linux.ibm.com>