community/terminator: fix tests
Fix a type mismatch in the checking of duplicate keys in
`tests/test_prefseditor_keybindings.py`.

```
    def test_duplicate_accels_not_possible_to_set(accel_params):
        """
        Tests that a duplicate key binding accelerator, that is a key binding accelerator
        which is already defined in the config cannot be used to refer to more than
        one action.
        """

        [...]

        all_default_accelerators = {
            Gtk.accelerator_parse(accel)
            for accel in config.DEFAULTS["keybindings"].values()
            if accel != ""  # ignore empty key bindings
        }
        # Check that a test accelerator is indeed a duplicate
>       assert (key, mods) in all_default_accelerators
E       assert (97, <ModifierType.CONTROL_MASK|MOD1_MASK: 12>) in {(accelerator_key=43, accelerator_mods=<ModifierType.          CONTROL_MASK: 4>), (accelerator_key=45, accelerator_mods=<ModifierType.CONTROL_MASK: 4>), (accelerator_key=48,accelerator_mods=<ModifierType.CONTROL_MASK: 4>), (accelerator_key=48, accelerator_mods=<ModifierType.SUPER_MASK: 67108864>),(accelerator_key=49, accelerator_mods=<ModifierType.SUPER_MASK: 67108864>), (accelerator_key=97, accelerator_mods=<ModifierType.SHIFT_MASK|CONTROL_MASK: 5>), ...}

tests/test_prefseditor_keybindings.py:164: AssertionError
```

```
FAILED tests/test_prefseditor_keybindings.py::test_duplicate_accels_not_possible_to_set[accel_params0]
FAILED tests/test_prefseditor_keybindings.py::test_duplicate_accels_not_possible_to_set[accel_params1]
FAILED tests/test_prefseditor_keybindings.py::test_duplicate_accels_not_possible_to_set[accel_params2]
FAILED tests/test_prefseditor_keybindings.py::test_duplicate_accels_not_possible_to_set[accel_params3]
```