testing/bionic_translation: disable on armv7 due to FTBFS
fails on armv7 with:
../linker/linker.c:1653:62: error: 'bionic_dl_iterate_phdr' undeclared (first use in this function); did you mean 'dl_iterate_phdr'?

Disable for now to unblock the builders.