testing/boinc: add xcb-util-dev to makedepends
The xcb-atom header in xcb-util-dev is required to build the screensaver.

```
checking for xcb-atom... no
WARNING: Xcb-atom not found, x11_screensaver will not be built
[...]
>>> ERROR: boinc-screensaver*: screensaver failed
>>> ERROR: boinc*: prepare_subpackages failed
```

Also remove the `-Wno-error=format-security` flag, no longer needed with
system libzip.