community/py3-kitchen: build with gpep517, disable check
Switch to gpep517 and disable check due to failed tests. Upstream repo
has been archived on 2024-08-09.

Resolves check error due to removed `setup.py test` command, which was
deprecated in setuptools 72.0.0.

```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'test'
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/17110