community/solaar: fix dependencies
The dependency on py3-hid-parser is removed because this aport
provides it's own. Added py3-typing-extensions dependency:
```
Traceback (most recent call last):
  File "/usr/bin/solaar", line 40, in <module>
    import solaar.gtk
  File "/usr/lib/python3.14/site-packages/solaar/gtk.py", line 34, in <module>
    from solaar import cli
  File "/usr/lib/python3.14/site-packages/solaar/cli/__init__.py", line 26, in <module>
    from logitech_receiver import device
  File "/usr/lib/python3.14/site-packages/logitech_receiver/device.py", line 34, in <module>
    from . import hidpp10
  File "/usr/lib/python3.14/site-packages/logitech_receiver/hidpp10.py", line 22, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

From !100059:

For some reason Solaar forks some libraries (including py3-hid-parser) then
installs those forks to site-packages by default, which causes conflicts with
the original libraries. However, it also supports being installed to /usr/share/solaar.
Move the Python libary files to /usr/share/solaar. Drop the dependency on py3-hid-parser
as it's included in Solaar itself.