community/prosody: skip failing test
Test passed in ci but failed on the builders. Test assertions in "works"
test case require stdout to be writable.

```
Failure -> spec/util_poll_spec.lua @ 21
util.poll new works
spec/util_poll_spec.lua:23: Operation not permitted
Expected to be truthy, but value was:
(nil)
>>> ERROR: prosody: check failed
```