community/py3-seaborn: fix tests
Fix tests with matplotlib 3.10.x.

```
self = <tests._core.test_plot.TestLabelVisibility object at 0xdbda19a8>

    def test_1d_column_wrapped(self):

[...]

        for s in subplots[1:]:
            ax = s["ax"]
            assert ax.xaxis.get_label().get_visible()
            # mpl3.7 added a getter for tick params, but both yaxis and xaxis return
            # the same entry of "labelleft" instead of  "labelbottom" for xaxis
            if not _version_predates(mpl, "3.7"):
>               assert ax.xaxis.get_tick_params()["labelleft"]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E               KeyError: 'labelleft'

tests/_core/test_plot.py:1858: KeyError

[...]

FAILED tests/_core/test_plot.py::TestLabelVisibility::test_1d_column_wrapped
FAILED tests/_core/test_plot.py::TestLabelVisibility::test_1d_row_wrapped - K...
```

Also fix a test with numpy 2.x.

```
self = <tests.test_distributions.TestKDEPlotBivariate object at 0x7f77e46751c0>
rng = RandomState(MT19937) at 0x7F77E5677D40

    def test_weights(self, rng):

        import warnings
>       warnings.simplefilter("error", np.VisibleDeprecationWarning)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

tests/test_distributions.py:1042:
```