testing/opa: fix test with go 1.25.6
Update patch to fix test error with runtime/metrics.

```
--- FAIL: TestJSONSerialization (0.00s)
    prometheus_test.go:196: unexpected extra metrics, expected 124, got 125
    prometheus_test.go:207: unexpected metric: go_godebug_non_default_behavior_urlmaxqueryparams_events_total (type: map[help:The number of non-default behaviors executed by the net/url package due to a non-default GODEBUG=urlmaxqueryparams=... setting. Sourced from /godebug/non-default-behavior/urlmaxqueryparams:events. metric:[map[counter:map[createdTimestamp:2026-01-17T06:15:49.520688040Z value:0]]] name:go_godebug_non_default_behavior_urlmaxqueryparams_events_total type:COUNTER])
FAIL
FAIL	github.com/open-policy-agent/opa/internal/prometheus	0.031s
```