community/drawpile: fix build with qt 6.10.2
Fix build error with Qt >=6.10.1.

```
$builddir/src/desktop/widgets/tablettest.cpp:69:54: error: no matching function for call to 'QString::arg(Qt::MouseButtons)'
   66 |         emit eventReport(QString("Mouse move X=%1 Y=%2 B=%3")
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   67 |                                                  .arg(mousePos.x())
      |                                                  ~~~~~~~~~~~~~~~~~~
   68 |                                                  .arg(mousePos.y())
      |                                                  ~~~~~~~~~~~~~~~~~~
   69 |                                                  .arg(e->buttons()));
      |                                                  ~~~~^~~~~~~~~~~~~~
```

(cherry picked from commit b85f7059f0700b4209427bb7b960f99712b1c4f9)