community/py3-udev: fix dependency on libudev
It looks like since commit c2fe9e580 the libudev.so.1 is now in
eudev-libs package instead of in the eudev package.

Add the correct dependency so py3-udev can load the library again

    File "/usr/lib/python3.12/site-packages/pyudev/core.py", line 59, in __init__
      self._libudev = load_ctypes_library("udev", SIGNATURES, ERROR_CHECKERS)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/pyudev/_ctypeslib/utils.py", line 51, in load_ctypes_library
      raise ImportError("No library named %s" % name)
  ImportError: No library named udev