community/aws-crt-cpp: fix missing private header
Fix missing private header include, which resolves a `No such file or
directory` error during a rebuild of dependent aws-sdk-cpp.

```
In file included from /usr/include/aws/crt/Api.h:9,
                 from /home/buildozer/aports/community/aws-sdk-cpp/src/aws-sdk-cpp-1.11.700/src/aws-cpp-sdk-core/source/Globals.cpp:6:
/usr/include/aws/crt/mqtt/Mqtt5Client.h:9:10: fatal error: aws/crt/mqtt/private/MqttShared.h: No such file or directory
    9 | #include <aws/crt/mqtt/private/MqttShared.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```