community/miller: skip some test cases in regression test on loongarch64
Failed test cases found on the edge loongarch64 builder.

```
FAILED CASE DIRECTORIES:
  ./test/cases/verb-summary/
  ./test/cases/dsl-stats/moments/
  ./test/cases/
NUMBER OF CASES            PASSED 4590
NUMBER OF CASES            FAILED 7
NUMBER OF CASE-DIRECTORIES PASSED 286
NUMBER OF CASE-DIRECTORIES FAILED 3
FAIL overall
--- FAIL: TestRegression (96.71s)
    regression_test.go:70:
FAIL
FAIL	command-line-arguments	96.717s
FAIL
```