community/tor: upgrade to 0.4.7.10
Disable on s390x for now. On the CI builder we currently get this:

  config/extended_fmt: Aug 14 10:04:00.723 [err] tor_assertion_failed_(): Bug: src/lib/encoding/confline.c:411: parse_config_line_from_str_verbose: Assertion cp >= val failed; aborting. (on Tor 0.4.7.10 )
  Aug 14 10:04:00.723 [err] Bug: Tor 0.4.7.10: Assertion cp >= val failed in parse_config_line_from_str_verbose at src/lib/encoding/confline.c:411: . (Stack trace not available) (on Tor 0.4.7.10 )
  make: *** [Makefile:25863: test] Aborted (core dumped)
  >>> ERROR: tor: check failed

Possibly due to GCC 12, we don't see this in 3.16-stable.