community/py3-jaraco.context: fix installer .whl filename
Fix packaging error due to changed .whl filename with setuptools >= 75.3.1.

```
FileNotFoundError: [Errno 2] No such file or directory: '.dist/jaraco.context-6.0.1-py3-none-any.whl'
```