community/apfs-fuse: fix build with gcc 15
Fix type errors with gcc 15 due to missing header.

```
/home/builder/aports/community/apfs-fuse/src/apfs-fuse-66b86bd525e8cb90f9012543be89b1f092b75cf3/ApfsLib/PList.h:58:9: error: 'int64_t' does not name a type
   58 |         int64_t value() const { return m_value; }
      |         ^~~~~~~
/home/builder/aports/community/apfs-fuse/src/apfs-fuse-66b86bd525e8cb90f9012543be89b1f092b75cf3/ApfsLib/PList.h:6:1: note:   'int64_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
    5 | #include <memory>
  +++ |+#include <cstdint>
    6 |
```