main/s6-portable-utils: upgrade to 2.3.1.1
upgraded to fix the rebuild against skalibs 2.14.5.1:
```
src/multicall/s6-portable-utils.c:24:13: error: conflicting types for 'main_func'; have 'int(int,  const char * const*, const char * const*)'
   24 | typedef int main_func (int, char const *const *, char const *const *) ;
      |             ^~~~~~~~~
In file included from /usr/include/skalibs/posixplz.h:11,
                 from /usr/include/skalibs/skalibs.h:17,
                 from src/multicall/s6-portable-utils.c:20:
/usr/include/skalibs/functypes.h:67:13: note: previous declaration of 'main_func' with type 'main_func' {aka 'int(const char * const*)'}
   67 | typedef int main_func (char const *const *) ;
      |             ^~~~~~~~~
```