testing/polybar: disable s390x
ERROR: unsatisfiable constraints:
  pulseaudio-dev (missing):
    required by: .makedepends-polybar-0[pulseaudio-dev]