community/ollama: upgrade to 0.11.7
- Ref https://github.com/ollama/ollama/releases/tag/v0.11.7
- Full Changelog: [v0.11.4...v0.11.7](https://github.com/ollama/ollama/compare/v0.11.4...v0.11.7)
- Disable armv7: undefined reference to `ggml_vec_dot_q4_0_q8_0'
- Disable armhf: undefined reference to `ggml_vec_dot_q4_0_q8_0'
- Disable ppc64le: Cannot find source file: ggml-cpu/arch/powerpc/quants.c