main/py-cffi: disable tests on x86 and ppc64le
>>>>>>>>>>>>>>>>>>> ppc64le

=================================== FAILURES ===================================
_______________________________ test_float_types _______________________________

    def test_float_types():
        INF = 1E200 * 1E200
        for name in ["float", "double"]:
            p = new_primitive_type(name)
            assert bool(cast(p, 0)) is False      # since 1.7
            assert bool(cast(p, -0.0)) is False   # since 1.7
            assert bool(cast(p, 1e-42)) is True
            assert bool(cast(p, -1e-42)) is True
            assert bool(cast(p, INF))
            assert bool(cast(p, -INF))
            assert bool(cast(p, float("nan")))
            assert int(cast(p, -150)) == -150
            assert int(cast(p, 61.91)) == 61
            assert long(cast(p, 61.91)) == 61
            assert type(int(cast(p, 61.91))) is int
            assert type(int(cast(p, 1E22))) is long
            assert type(long(cast(p, 61.91))) is long
            assert type(long(cast(p, 1E22))) is long
            py.test.raises(OverflowError, int, cast(p, INF))
            py.test.raises(OverflowError, int, cast(p, -INF))
            assert float(cast(p, 1.25)) == 1.25
            assert float(cast(p, INF)) == INF
            assert float(cast(p, -INF)) == -INF
            if name == "float":
                assert float(cast(p, 1.1)) != 1.1     # rounding error
>               assert float(cast(p, 1E200)) == INF   # limited range
E               AssertionError: assert 21918092.0 == inf
E                +  where 21918092.0 = float(<cdata 'float' 21918092.0>)
E                +    where <cdata 'float' 21918092.0> = cast(<ctype 'float'>, 1e+200)

c/test_c.py:181: AssertionError
______________________________ test_complex_types ______________________________

    def test_complex_types():
        INF = 1E200 * 1E200
        for name in ["float", "double"]:
            p = new_primitive_type(name + " _Complex")
            assert bool(cast(p, 0)) is False
            assert bool(cast(p, INF))
            assert bool(cast(p, -INF))
            assert bool(cast(p, 0j)) is False
            assert bool(cast(p, INF*1j))
            assert bool(cast(p, -INF*1j))
            # "can't convert complex to float", like CPython's "float(0j)"
            py.test.raises(TypeError, int, cast(p, -150))
            py.test.raises(TypeError, long, cast(p, -150))
            py.test.raises(TypeError, float, cast(p, -150))
            assert complex(cast(p, 1.25)) == 1.25
            assert complex(cast(p, 1.25j)) == 1.25j
            assert complex(cast(p, complex(0,INF))) == complex(0,INF)
            assert complex(cast(p, -INF)) == -INF
            if name == "float":
                assert complex(cast(p, 1.1j)) != 1.1j         # rounding error
>               assert complex(cast(p, 1E200+3j)) == INF+3j   # limited range
E               AssertionError: assert (21918092+3j) == (inf + 3j)
E                +  where (21918092+3j) = complex(<cdata 'float _Complex' (21918092+3j)>)
E                +    where <cdata 'float _Complex' (21918092+3j)> = cast(<ctype 'float _Complex'>, (1e+200 + 3j))

c/test_c.py:210: AssertionError
______________________________ TestFFI.test_float ______________________________

self = <testing.cffi0.test_ffi_backend.TestFFI object at 0x7fffaef9b048>

    def test_float(self):
        ffi = FFI(backend=self.Backend())
        p = ffi.new("float[]", [-2, -2.5])
        assert p[0] == -2.0
        assert p[1] == -2.5
        p[1] += 17.75
        assert p[1] == 15.25
        #
        p = ffi.new("float*", 15.75)
        assert p[0] == 15.75
        py.test.raises(TypeError, int, p)
        py.test.raises(TypeError, float, p)
        p[0] = 0.0
        assert bool(p) is True
        #
        p = ffi.new("float*", 1.1)
        f = p[0]
        assert f != 1.1      # because of rounding effect
        assert abs(f - 1.1) < 1E-7
        #
        INF = 1E200 * 1E200
        assert 1E200 != INF
        p[0] = 1E200
>       assert p[0] == INF     # infinite, not enough precision
E       AssertionError

testing/cffi0/backend_tests.py:416: AssertionError
____________________________ TestNewFFI1.test_float ____________________________

self = <testing.cffi1.test_new_ffi_1.TestNewFFI1 instance at 0x7fffaeaaed48>

    def test_float(self):
        p = ffi.new("float[]", [-2, -2.5])
        assert p[0] == -2.0
        assert p[1] == -2.5
        p[1] += 17.75
        assert p[1] == 15.25
        #
        p = ffi.new("float*", 15.75)
        assert p[0] == 15.75
        py.test.raises(TypeError, int, p)
        py.test.raises(TypeError, float, p)
        p[0] = 0.0
        assert bool(p) is True
        #
        p = ffi.new("float*", 1.1)
        f = p[0]
        assert f != 1.1      # because of rounding effect
        assert abs(f - 1.1) < 1E-7
        #
        INF = 1E200 * 1E200
        assert 1E200 != INF
        p[0] = 1E200
>       assert p[0] == INF     # infinite, not enough precision
E       assert 21918092.0 == inf

testing/cffi1/test_new_ffi_1.py:474: AssertionError
 4 failed, 1859 passed, 106 skipped, 4 xfailed, 508 warnings in 235.82 seconds =

>>>>>>>>>>>>>>>>>>>>>>>>> x86

=================================== FAILURES ===================================
________________________ TestFFI.test_function_typedef _________________________

self = <testing.cffi0.test_ffi_backend.TestFFI object at 0xf62c9aec>

    def test_function_typedef(self):
        ffi = FFI(backend=self.Backend())
        ffi.cdef("""
            typedef double func_t(double);
            func_t sin;
        """)
        m = ffi.dlopen(lib_m)
        x = m.sin(1.23)
>       assert x == math.sin(1.23)
E       assert nan == 0.9424888019316975
E        +  where 0.9424888019316975 = <built-in function sin>(1.23)
E        +    where <built-in function sin> = math.sin

testing/cffi0/test_function.py:301: AssertionError
______________________ TestFunction.test_function_typedef ______________________

self = <testing.cffi0.test_function.TestFunction object at 0xf59fd24c>

    def test_function_typedef(self):
        ffi = FFI(backend=self.Backend())
        ffi.cdef("""
            typedef double func_t(double);
            func_t sin;
        """)
        m = ffi.dlopen(lib_m)
        x = m.sin(1.23)
>       assert x == math.sin(1.23)
E       assert nan == 0.9424888019316975
E        +  where 0.9424888019316975 = <built-in function sin>(1.23)
E        +    where <built-in function sin> = math.sin

testing/cffi0/test_function.py:301: AssertionError
 2 failed, 1866 passed, 101 skipped, 4 xfailed, 504 warnings in 303.41 seconds =