community/umurmur: fix config and manpage source urls
Update the urls for `umurmur.conf.5` and `umurmurd.8` to the new
locations to fix a checksum error on the 3.24 builders. The contents of
the files have not changed.

```
>>> umurmur: Fetching https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/ports/audio/umurmur/files/umurmurd.8?rev=1.1
Connecting to cvsweb.openbsd.org (128.100.17.243:443)
saving to '/var/cache/distfiles/v3.24/umurmurd.8?rev=1.1.part'
'/var/cache/distfiles/v3.24/umurmurd.8?rev=1.1.part' saved
/var/cache/distfiles/v3.24/umurmurd.8?rev=1.1: FAILED
sha512sum: WARNING: 1 of 1 computed checksums did NOT match
Because the remote file above failed the sha512sum check it will be renamed.
Rebuilding will cause it to re-download which in some cases may fix the problem.
Renaming: umurmurd.8?rev=1.1 to umurmurd.8?rev=1.1.b825c94d
>>> ERROR: umurmur: Use 'abuild checksum' to generate/update the checksum(s)
```