community/musescore: upgrade to 4.6.3, fix build
https://github.com/musescore/MuseScore/releases/tag/v4.6.3

Fix build errors with qt6 6.10.0.

```
CMake Error at src/framework/dockwindow/thirdparty/KDDockWidgets/src/CMakeLists.txt:298 (target_link_libraries):
  Target "kddockwidgets" links to:

    Qt6::GuiPrivate

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

```
In file included from /home/builder/builds/musescore/src/MuseScore-4.6.3/build/src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx:37:
/home/builder/builds/musescore/src/MuseScore-4.6.3/src/importexport/midi/internal/midiimport/importmidi_tuplet.cpp:900:59: error: use of undeclared identifier 'message'
  900 |                            "MidiTuplet::addTupletEvents", message.toLatin1().data());
      |                                                           ^~~~~~~
```