community/obs-studio: add simde-dev to depends_dev
The development files require `simde-dev`.

Example error found in dependent `looking-glass`:

```
In file included from /usr/include/obs/graphics/vec4.h:23,
                 from /usr/include/obs/graphics/vec3.h:21,
                 from /usr/include/obs/obs.h:26,
                 from /usr/include/obs/obs-module.h:20,
                 from /home/buildozer/aports/community/looking-glass/src/looking-glass-B7/obs/main.c:21:
/usr/include/obs/util/sse-intrin.h:39:10: fatal error: simde/x86/sse2.h: No such file or directory
   39 | #include <simde/x86/sse2.h>
      |          ^~~~~~~~~~~~~~~~~~
```