community/gcovr: depend on py3-setuptools
The main python3 script in /usr/bin imports the pkg_resources module, so
we need py3-setuptools. Otherwise this error is raised:

    ModuleNotFoundError: No module named 'pkg_resources'