testing/keyd: disable on 32-bit arches due to build failure
    src/main.c:223:4: error: 'struct input_event' has no member named 'time'
      223 |   .time.tv_sec = 0,
          |    ^~~~