testing/wldash: disable on aarch64, armhf, armv7, ppc64le due to failure
       Compiling fontconfig v0.2.0
    error[E0308]: mismatched types
       --> /home/buildozer/.cargo/registry/src/github.com-1ecc6299db9ec823/fontconfig-0.2.0/src/lib.rs:185:43
        |
    185 |                 let cstr = CStr::from_ptr(ret as *const i8);
        |                                           ^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
        |
        = note: expected raw pointer `*const u8`
                   found raw pointer `*const i8`

    error[E0308]: mismatched types
       --> /home/buildozer/.cargo/registry/src/github.com-1ecc6299db9ec823/fontconfig-0.2.0/src/lib.rs:281:45
        |
    281 |         let fcstr = unsafe { CStr::from_ptr(fcstr as *const i8) };
        |                                             ^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
        |
        = note: expected raw pointer `*const u8`
                   found raw pointer `*const i8`

    error: aborting due to 2 previous errors

    For more information about this error, try `rustc --explain E0308`.
    error: could not compile `fontconfig`

    To learn more, run the command again with --verbose.
    warning: build failed, waiting for other jobs to finish...
    error: build failed