Revert "main/git: ugprade to 2.15.1"
Build fails on ppc64le so revert for now.

>>> git*: Stripping binaries
[31;01mscanelf[00;00m: ./usr/bin/git: Invalid section header info (2)
[31;01mscanelf[00;00m: ./usr/bin/git-upload-archive: Invalid section header info (2)
[31;01mscanelf[00;00m: ./usr/bin/git-receive-pack: Invalid section header info (2)
getfattr: ./usr/libexec/git-core/stkilJKK: No such file or directory
strip: './usr/libexec/git-core/stkilJKK': No such file
>>> ERROR: git*: prepare_package failed
>>> ERROR: git: all failed

This reverts commit fa965be44008ffe8dc7240735f88450b9563d150.