main/libc0.9.32: backport posix_spawn fix
This should fix the following error when compiling posix-spawn ruby gem:

In file included from posix-spawn.c:9:0:
/usr/include/spawn.h:80:34: error: expected ';', ',' or ')' before 'pid'
 int posix_spawn(pid_t * restrict pid, const char * restrict path,
                                  ^
/usr/include/spawn.h:248:10: error: expected ';', ',' or ')' before 'file_actions'
          file_actions, int fd,
          ^

(cherry picked from commit 5a835d7baaf03751c32d2dad045fdc161dce8dfe)