testing/tailscale: disable on mips/mips64
test failures

--- FAIL: TestIgnoreLocallyBoundPorts (0.02s)
    portlist_test.go:45: didn't expect to find test's localhost ephemeral port
FAIL
FAIL	tailscale.com/portlist	0.064s