community/librsvg: fix comments in rsvg.h
Patch from https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/688

Causes build failures:

> error: "/*" within comment [-Werror=comment]