testing/libsigrokdecode: rebuild against python3-3.14
This fixes:

    ERROR: unable to select packages:
      so:libpython3.12.so.1.0 (no such package):
        required by: libsigrokdecode-0.5.3-r4[so:libpython3.12.so.1.0]

Also use official (read-only) Github mirror (upstream git seems to be
struggling under scraper load)