testing/py3-grpcio: upgrade to 1.28.1
Disable on ppc64le to avoid an error:

    third_party/abseil-cpp/absl/base/internal/unscaledcycleclock.cc:100:2: error: #error Must implement UnscaledCycleClock::Frequency()

linux-headers is now a dependency:
https://github.com/grpc/grpc/issues/21918#issuecomment-582589140

abseil is a git submodule and therefore must be downloaded separately:
https://github.com/grpc/grpc/issues/21956#issuecomment-584776736

See also community/grpc