main/py3-wheel: add missing dependency
Before this change:

    $ dabuild sh
    $ sudo apk add py3-wheel >/dev/null && wheel --help
    Traceback (most recent call last):
      File "/usr/bin/wheel", line 6, in <module>
        from pkg_resources import load_entry_point
    ModuleNotFoundError: No module named 'pkg_resources'

This change adds py3-setuptools as a runtime dependency because pkg_resources is
imported by a file installed into /usr/bin/:

    $ grep pkg_resources /usr/bin/wheel
    from pkg_resources import load_entry_point

pkg_resources is part of py3-setuptools:

    $ apk info -L py3-setuptools | grep pkg_resources/__init__.py
    usr/lib/python3.8/site-packages/pkg_resources/__init__.py

After this change:

    $ dabuild sh
    $ sudo apk add py3-wheel >/dev/null && wheel -h
    usage: wheel [-h] {unpack,pack,convert,version,help} ...

    positional arguments:
      {unpack,pack,convert,version,help}
                            commands
        unpack              Unpack wheel
        pack                Repack wheel
        convert             Convert egg or wininst to wheel
        version             Print version and exit
        help                Show this help

    optional arguments:
      -h, --help            show this help message and exit