community/man-db: conflict with mandoc and mandoc-apropos
Otherwise causes the following error:

	ERROR: man-db-2.9.3-r0: trying to overwrite usr/bin/apropos owned by mandoc-apropos-1.14.5-r5.
	ERROR: man-db-2.9.3-r0: trying to overwrite usr/bin/man owned by mandoc-1.14.5-r5.
	ERROR: man-db-2.9.3-r0: trying to overwrite usr/bin/whatis owned by mandoc-apropos-1.14.5-r5.