Revert "main/nodejs: upgrade to 8.10.0"
This reverts commit 0fec1f8393961c474ddc240c8f94f13c9002103f.

It fails to build on v3.7 (but works on edge):

    ../src/node.cc: In function 'void node::SetupProcessObject(node::Environment*, int, const char* const*, int, const char* const*)':
    ../src/node.cc:3495:63: error: 'uv_os_getpid' was not declared in this scope
                         Integer::New(env->isolate(), uv_os_getpid()));