main/gcalcli: upgrade to 4.0.0_alpha4 and modernize
current version (3.4.0) does not support python3, it fails with error:
SyntaxError: Missing parentheses in call to 'print'