testing/veracrypt: disable on s390x
Due to broken linking:
Linking veracrypt
Error: TestFailed at VeraCrypt::TestCipher:181
make[1]: *** [Main.make:159: veracrypt] Error 1
make: *** [Makefile:372: all] Error 2