community/py3-wasabi: skip test
Temporarily skip `wasabi/tests/test_jupyter.py` test due to
jupyter-nbconvert having a runtime dependency on py3-jupyterlab_pygments,
which was removed from depends to address a circular dependency.

```
    def test_jupyter():

[...]

>       subprocess.run(
            [
                sys.executable,
                "-m",
                "nbconvert",
                str(TEST_DATA / "wasabi-test-notebook.ipynb"),
                "--execute",
                "--stdout",
                "--to",
                "notebook",
            ],
            env=env,
            check=True,
        )

wasabi/tests/test_jupyter.py:23:

[...]

  File "/usr/lib/python3.12/site-packages/nbconvert/preprocessors/csshtmlheader.py", line 9, in <module>
    from jupyterlab_pygments import JupyterStyle  # type:ignore[import-untyped]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jupyterlab_pygments'
=========================== short test summary info ============================
FAILED wasabi/tests/test_jupyter.py::test_jupyter - subprocess.CalledProcessE...
```

See also: 18fb94a0d19dbe89612d8c3d72137e734eace375