testing/gnome-authenticator: depend on libhandy
Traceback (most recent call last):
  File "/usr/bin/authenticator", line 31, in <module>
    require_version("Handy", "0.0")
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available