community/avro: fix build with gcc 15, use cmake3.5 wrapper
Fix `too many arguments` errors with gcc 15.

```
/home/builder/aports/community/avro/src/avro-src-1.11.3/lang/c/src/st.c:69:43: error: too many arguments to function 'table->type->hash'; expected 0, have 1
   69 | #define do_hash(key,table) (unsigned int)(*(table)->type->hash)((key))
      |                                          ~^~~~~~~~~~~~~~~~~~~~~ ~~~~~
/home/builder/aports/community/avro/src/avro-src-1.11.3/lang/c/src/st.c:240:20: note: in expansion of macro 'do_hash'
  240 |         hash_val = do_hash(key, table);
      |                    ^~~~~~~
In file included from /home/builder/aports/community/avro/src/avro-src-1.11.3/lang/c/src/st.c:16:
/home/builder/aports/community/avro/src/avro-src-1.11.3/lang/c/src/st.h:42:9: note: declared here
   42 |   int (*hash) (ANYARGS);
      |         ^~~~
```

Also use cmake3.5 wrapper to rebuild with cmake >=4.

```
CMake Error at CMakeLists.txt:19 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```