testing/tootle: disable on mips(64)
```
ERROR: unable to select packages:
  libhandy1-dev (no such package):
    required by: .makedepends-tootle-20201228.104535[libhandy1-dev]
```