community/py3-praw: fix `test_auth` test
Fix build error due to failed test.

```
_____________________________ TestAuth.test_limits _____________________________
[gw13] linux -- Python 3.12.10 /home/buildozer/aports/community/py3-praw/src/praw-7.8.1/.testenv/bin/python3

self = <tests.unit.models.test_auth.TestAuth object at 0x7fffef87a690>

    def test_limits(self):
        expected = {"remaining": None, "reset_timestamp": None, "used": None}
        for app in [
            installed_app(),
            script_app(),
            script_app_with_password(),
            web_app(),
        ]:
>           assert expected == app.auth.limits

tests/unit/models/test_auth.py:71:

[...]

        data = self._reddit._core._rate_limiter
        return {
            "remaining": data.remaining,
>           "reset_timestamp": data.reset_timestamp,
            "used": data.used,
        }
E       AttributeError: 'RateLimiter' object has no attribute 'reset_timestamp'

praw/models/auth.py:39: AttributeError
```