community/networkmanager: disabled
ERROR: unsatisfiable constraints:
  libmm-glib-dev-1.4.14-r0:
    conflicts:
               modemmanager-dev-1.4.14-r0[pc:mm-glib=0]
    satisfies: world[libmm-glib-dev]
  modemmanager-dev-1.4.14-r0:
    conflicts:
               libmm-glib-dev-1.4.14-r0[pc:mm-glib=1.4.14]
    satisfies: world[modemmanager-dev]