Revert "main/nodejs: upgrade to 12.19.0"
This reverts commit 96a5e5e0aefea75aef5a588935dfdfcf863f6b6a.

It fails to build due to incompatibility with libuv 1.38.0:

    ../src/node.cc: In function 'int node::Start(int, char**)':
    ../src/node.cc:1022:42: error: 'UV_METRICS_IDLE_TIME' was not declared in this scope
     1022 |     uv_loop_configure(uv_default_loop(), UV_METRICS_IDLE_TIME);
          |

I'm sorry for this, I didn't test it on v3.12 before pushing. :(

Resolves #12028