community/wasm-pack: add samurai to makedepends
Add samurai to makedepends due to abuild setting ninja as default cmake
generator.

```
 error: failed to run custom build command for `libz-ng-sys v1.1.15`

 Caused by:
   process didn't exit successfully: `/home/buildozer/aports/community/wasm-pack/src/wasm-pack-0.13.0/target/release/build/libz-ng-sys-ad02b2085dd361b9/build-script-build_zng` (exit status: 101)

[...]

 CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```