main/alsa-lib: Fix FTBFS on ppc64le
Currently alsa-libs is FTBFS on ppc64le due to an old code
workaround on the linking mechanism.

This causes the following error:

 libasound.so: undefined reference to `.__snd_pcm_hw_params_set_format_first'

Removing this legacy workaround to enable alsa lib to build
on ppc64le.