community/garage: disable on 32-bit arches due to build failure
       Compiling garage v0.8.2 (/builds/alpine/aports/community/garage/src/garage-0.8.2/src/garage)
    terminate called after throwing an instance of 'std::bad_alloc'
      what():  std::bad_alloc
    error: could not compile `garage`
    Caused by:
      process didn't exit successfully: `rustc ...` (signal: 6, SIGABRT: process abort signal)