community/frotz: fix checksum
Update checksum to fix a checksum mismatch error on the 3.24 builders.
The git commit short hash in the `Makefile` was shortened, which led to
a checksum change.

```
sha512sum: WARNING: 1 of 1 computed checksums did NOT match
Because the remote file above failed the sha512sum check it will be renamed.
Rebuilding will cause it to re-download which in some cases may fix the problem.
Renaming: frotz-2.55.tar.gz to frotz-2.55.tar.gz.08ba5d31
>>> ERROR: frotz: Use 'abuild checksum' to generate/update the checksum(s)
```

```
diff -rupN a/Makefile b/Makefile
--- a/Makefile  2025-02-01 22:36:37.000000000 +0000
+++ b/Makefile  2025-02-01 22:36:37.000000000 +0000
@@ -338,7 +338,7 @@ GIT_HASH_SHORT = $(shell git rev-parse -
 GIT_DATE = $(shell git show -s --format=%ci)
 else
 GIT_HASH = acf205585a9472d27c07c0fe62da4b8bc89d1ec7
-GIT_HASH_SHORT = acf20558
+GIT_HASH_SHORT = acf2055
 GIT_DATE = 2025-02-01 14:36:37 -0800
 endif
 export CFLAGS
```