testing/ocaml-cppo: disable on ppc64le due to failing tests
          cppo alias test/runtest (exit 1)
  (cd _build/default/test && ../../install/default/bin/cppo test.cppo) > /dev/null
  Error: File "test.cppo", line 98, characters 0-20
  Error: math error