testing/zoneminder: minor fixes, disable x86
Does not build for x86 due to:

zm_utils.cpp: In function 'void ssedetect()':
zm_utils.cpp:167:3: error: PIC register clobbered by '%ebx' in 'asm'

zm_image.cpp: In function 'void ssse3_deinterlace_4field_gray8(uint8_t*, uint8_t*, unsigned int, unsigned int, unsigned int)':
zm_image.cpp:4780:3: error: 'asm' operand has impossible constraints

The assembly parts need proper PIC support.