testing/py3-fastapi: disable parallel testing
Some tests create and delete files and modify the same sqlite databases
which causes errors and failures like the following:

ERROR tests/test_tutorial/test_sql_databases_peewee/test_sql_databases_peewee.py::test_openapi_schema - FileNotFoundError: [Errno 2] No such file or directory: 'test.db'
FAILED tests/test_tutorial/test_sql_databases_peewee/test_sql_databases_peewee.py::test_read_items - assert []
FAILED tests/test_tutorial/test_sql_databases_peewee/test_sql_databases_peewee.py::test_get_user - AssertionError: {"detail":"User not found"}
FAILED tests/test_tutorial/test_sql_databases_peewee/test_sql_databases_peewee.py::test_inexistent_user - peewee.OperationalError: no such table: user
FAILED tests/test_tutorial/test_sql_databases_peewee/test_sql_databases_peewee.py::test_get_users - peewee.OperationalError: no such table: user
FAILED tests/test_tutorial/test_sql_databases_peewee/test_sql_databases_peewee.py::test_get_slowusers - peewee.OperationalError: no such table: user
FAILED tests/test_tutorial/test_sql_databases_peewee/test_sql_databases_peewee.py::test_create_item - peewee.OperationalError: no such table: item