main/harfbuzz: downgrade to 3.0.0
Build failures on 32bit arm

../src/hb-mutex.hh:100:42:error: cast from 'char*' to 'hb_mutex_impl_t*' {aka 'pthread_mutex_t*'} increases required alignment of target type [-Werror=cast-align
  100 |   void init   () { hb_mutex_impl_init   ((hb_mutex_impl_t *)); }
      |                                          ^~~~~~~~~~~~~~~~~~~~~

This reverts commit 72a08f417c84d7931a0c1656123fd9e44abf7cab.