testing/opa: fix test with go 1.25
Update patch to fix test error with runtime/metrics.

```
--- FAIL: TestJSONSerialization (0.01s)
    prometheus_test.go:190: unexpected extra metrics, expected 118, got 123
    prometheus_test.go:201: unexpected metric: go_godebug_non_default_behavior_updatemaxprocs_events_total (type: map[help:The number of non-default behaviors executed by the runtime package due to a non-default GODEBUG=updatemaxprocs=... setting. Sourced from /godebug/non-default-behavior/updatemaxprocs:events. metric:[map[counter:map[createdTimestamp:2025-09-05T03:08:28.815491570Z value:0]]] name:go_godebug_non_default_behavior_updatemaxprocs_events_total type:COUNTER])
    prometheus_test.go:201: unexpected metric: go_godebug_non_default_behavior_tlssha1_events_total (type: map[help:The number of non-default behaviors executed by the crypto/tls package due to a non-default GODEBUG=tlssha1=... setting. Sourced from /godebug/non-default-behavior/tlssha1:events. metric:[map[counter:map[createdTimestamp:2025-09-05T03:08:28.815484804Z value:0]]] name:go_godebug_non_default_behavior_tlssha1_events_total type:COUNTER])
    prometheus_test.go:201: unexpected metric: go_godebug_non_default_behavior_embedfollowsymlinks_events_total (type: map[help:The number of non-default behaviors executed by the cmd/go package due to a non-default GODEBUG=embedfollowsymlinks=... setting. Sourced from /godebug/non-default-behavior/embedfollowsymlinks:events. metric:[map[counter:map[createdTimestamp:2025-09-05T03:08:28.815395872Z value:0]]] name:go_godebug_non_default_behavior_embedfollowsymlinks_events_total type:COUNTER])
    prometheus_test.go:201: unexpected metric: go_godebug_non_default_behavior_containermaxprocs_events_total (type: map[help:The number of non-default behaviors executed by the runtime package due to a non-default GODEBUG=containermaxprocs=... setting. Sourced from /godebug/non-default-behavior/containermaxprocs:events. metric:[map[counter:map[createdTimestamp:2025-09-05T03:08:28.815392234Z value:0]]] name:go_godebug_non_default_behavior_containermaxprocs_events_total type:COUNTER])
    prometheus_test.go:201: unexpected metric: go_godebug_non_default_behavior_x509sha256skid_events_total (type: map[help:The number of non-default behaviors executed by the crypto/x509 package due to a non-default GODEBUG=x509sha256skid=... setting. Sourced from /godebug/non-default-behavior/x509sha256skid:events. metric:[map[counter:map[createdTimestamp:2025-09-05T03:08:28.815512195Z value:0]]] name:go_godebug_non_default_behavior_x509sha256skid_events_total type:COUNTER])
FAIL
FAIL	github.com/open-policy-agent/opa/internal/prometheus	0.015s
```