community/py3-urwid: add missing dependency
typing_extensions is imported unconditionally:

    > python -c 'from urwid.widget import PopUpTarget'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
        from urwid.widget import PopUpTarget
      File "/usr/lib/python3.14/site-packages/urwid/__init__.py", line 97, in <module>
        from . import display, event_loop, widget
      File "/usr/lib/python3.14/site-packages/urwid/event_loop/__init__.py", line 9, in <module>
        from .main_loop import MainLoop
      File "/usr/lib/python3.14/site-packages/urwid/event_loop/main_loop.py", line 37, in <module>
        from urwid.widget import PopUpTarget
      File "/usr/lib/python3.14/site-packages/urwid/widget/__init__.py", line 8, in <module>
        from .columns import Columns, ColumnsError, ColumnsWarning
      File "/usr/lib/python3.14/site-packages/urwid/widget/columns.py", line 7, in <module>
        from typing_extensions import Literal
    ModuleNotFoundError: No module named 'typing_extensions'