community/sbc: upgrade to 2.1, fix build with gcc 15 on 32-bit arm
Fix function argument types mismatch error in `sbc_primitives_armv6.c`.

```
sbc/sbc_primitives_armv6.c: In function 'sbc_analyze_1b_8s_armv6_odd':
sbc/sbc_primitives_armv6.c:300:9: error: too many arguments to function 'sbc_analyze_eight_armv6'; expected 0, have 3
  300 |         sbc_analyze_eight_armv6(x, out, analysis_consts_fixed8_simd_odd);
      |         ^~~~~~~~~~~~~~~~~~~~~~~ ~
sbc/sbc_primitives_armv6.c:112:36: note: declared here
  112 | static void __attribute__((naked)) sbc_analyze_eight_armv6()
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~
sbc/sbc_primitives_armv6.c: In function 'sbc_analyze_1b_8s_armv6_even':
sbc/sbc_primitives_armv6.c:307:9: error: too many arguments to function 'sbc_analyze_eight_armv6'; expected 0, have 3
  307 |         sbc_analyze_eight_armv6(x, out, analysis_consts_fixed8_simd_even);
      |         ^~~~~~~~~~~~~~~~~~~~~~~ ~
sbc/sbc_primitives_armv6.c:112:36: note: declared here
  112 | static void __attribute__((naked)) sbc_analyze_eight_armv6()
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~
```