main/libmemcached: fix ppc64le build break due to null pointer comparison
fixes compile error:

clients/memflush.cc:42:22: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
   if (opt_servers == false)