scripts/mkimg.standard.sh: add linux-firmware-none to the extended iso
Fixes installation without network, if this pkg is not on the iso:

Installing system on /dev/xvda1:
extlinux: Not a directory: /mnt/boot
ERROR: unable to select packages:
  linux-firmware-none (no such package):
    required by: world[linux-firmware-none]

(cherry picked from commit 41065fd278ddbb5309c1b5031babdfd388ad145e)

Closes #13973