main/icu: remove -full dependency on dev
similarly to the previous commit, starting on 3.16, adding
postgresql-dev, then trying to upgrade to edge, yields:

ERROR: unable to select packages:
  icu-data-en-71.1-r3:
    conflicts: icu-data-full-71.1-r3[icu-data=71.1-r3]
    satisfies: icu-libs-71.1-r3[icu-data=71.1-r3]
  icu-data-full-71.1-r3:
    conflicts: icu-data-en-71.1-r3[icu-data=71.1-r3]
    satisfies: icu-dev-71.1-r3[icu-data-full=71.1-r3] icu-libs-71.1-r3[icu-data=71.1-r3]

adding the full data first seems to work fine, though:

/ # apk add icu-data-full
(1/5) Installing icu-data-full (71.1-r3)
(2/5) Upgrading icu-libs (71.1-r2 -> 71.1-r3)
(3/5) Upgrading icu (71.1-r2 -> 71.1-r3)
(4/5) Upgrading icu-dev (71.1-r2 -> 71.1-r3)
(5/5) Purging icu-data-en (71.1-r2)
Executing busybox-1.35.0-r15.trigger
OK: 343 MiB in 36 packages
/ # apk upgrade -alU
(1/32) Upgrading alpine-baselayout-data (3.2.0-r22 -> 3.3.0-r0)

but having -full only be pulled in on upgrade from a previous -en
between repositories seems to not work as intended- apk cannot resolve
that -full will replace -en while also swapping repositories. (or maybe
there is another reason..?)

since this was added mostly for tests in aports (out of lazyness), just
get rid of it and fix it elsewhere later.