testing/opa: fix test with go 1.25.2
Update patch to fix test error with runtime/metrics.

```
--- FAIL: TestJSONSerialization (0.00s)
    prometheus_test.go:195: unexpected extra metrics, expected 123, got 124
    prometheus_test.go:206: unexpected metric: go_godebug_non_default_behavior_httpcookiemaxnum_events_total (type: map[help:The number of non-default behaviors executed by the net/http package due to a non-default GODEBUG=httpcookiemaxnum=... setting. Sourced from /godebug/non-default-behavior/httpcookiemaxnum:events. metric:[map[counter:map[createdTimestamp:2025-10-09T03:14:57.747889370Z value:0]]] name:go_godebug_non_default_behavior_httpcookiemaxnum_events_total type:COUNTER])
FAIL
FAIL    github.com/open-policy-agent/opa/internal/prometheus    0.007s
```