testing/csync2: disable on ppc64le due to build failure
    rsync.c:52:15: error: static declaration of 'strlcpy' follows non-static declaration
     static size_t strlcpy(char *d, const char *s, size_t bufsize)
                   ^~~~~~~
    In file included from csync2.h:33:0,
                     from rsync.c:21:
    /usr/include/string.h:84:8: note: previous declaration of 'strlcpy' was here
     size_t strlcpy (char *, const char *, size_t);
            ^~~~~~~