community/taskwarrior-tui: upgrade to 0.27.0
Move task3 from checkdepends to runtime depends, and fixed test
errors caused by parallel execution.

   failures:

   ---- app::tests::test_task_info_location_fixed_toggle_returns_to_configured_value stdout ----

   thread 'app::tests::test_task_info_location_fixed_toggle_returns_to_configured_value' (15676) panicked at src/app.rs:4613:60:
   called `Result::unwrap()` on an `Err` value: Unable to run `task show`.

   TASKRC override: ../taskwarrior-testdata-cdcdb20de1e9aefb2e2b50de7bbd27388b41f80e/.taskrc
   TASKDATA override: ../taskwarrior-testdata-cdcdb20de1e9aefb2e2b50de7bbd27388b41f80e/.task
   no such table: tasks: Error code 1: SQL error or missing database

   Please check your configuration or open a issue on github.
   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   failures:
       app::tests::test_task_info_location_fixed_toggle_returns_to_configured_value

   test result: FAILED. 36 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 29.65s