community/fractal: depend on gst-plugins-rs-gtk4
required to show video previews:

	thread 'main' panicked at src/components/media/video_player_renderer.rs:41:22:
	gst-plugin-gtk4 should be available: BoolError { message: "Failed to find element factory with name 'gtk4paintablesink' for creating element", filename: "./vendor/gstreamer/src/element_factory.rs", function: "gstreamer::element_factory::ElementBuilder::build::{{closure}}", line: 286 }