community/oath-toolkit: rebuild for xmlsec 1.3.11
Fixes:

    ERROR: unable to select packages:
      so:libxmlsec1.so.1 (no such package):
        required by: oath-toolkit-libpskc-2.6.14-r0[so:libxmlsec1.so.1]