community/gtk4.0: add missing depends_dev on vulkan-headers
In file included from /usr/include/gtk-4.0/gdk/gdk.h:75,
                 from /usr/include/gtk-4.0/gtk/gtk.h:31,
                 from testproj@exe/source/main.c:7:
/usr/include/gtk-4.0/gdk/gdkvulkancontext.h:32:10: fatal error: vulkan/vulkan.h: No such file or directory
   32 | #include <vulkan/vulkan.h>
      |          ^~~~~~~~~~~~~~~~