community/py3-plac: switch source to github repo
The PyPI tarball is missing a `doc/3.13/` subdirectory of example files
needed for running tests with python >= 3.13. Switch to a source which
includes the files.

See: https://github.com/ialbert/plac/commit/b57d3615712f6df98325cf3f8ee5c623abee70bf

```
Traceback (most recent call last):
  File "/home/builder/aports/community/py3-plac/src/plac-1.4.5/doc/test_plac.py", line 376, in <module>
    maybegen = test()
  File "/home/builder/aports/community/py3-plac/src/plac-1.4.5/doc/test_plac.py", line 108, in test_expected_help
    check_help(fname[:-5])
    ~~~~~~~~~~^^^^^^^^^^^^
  File "/home/builder/aports/community/py3-plac/src/plac-1.4.5/doc/test_plac.py", line 87, in check_help
    expected = fix_today(open(hname + '.help').read()).strip()
                         ~~~~^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '3.13/example8_.help'
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025