community/xwayland: replace xorg-server-xwayland
Without this, xwayland does not install properly since it tries to
overwrite packages owned by xorg-server-xwayland:

(1/1) Reinstalling xwayland (21.1.0-r0)
ERROR: xwayland-21.1.0-r0: trying to overwrite usr/bin/Xwayland owned by xorg-server-xwayland-1.20.10-r3.