community/py3-jaraco.collections: fix installer .whl filename, enable check
Fix packaging error due to changed .whl filename with setuptools >= 75.3.1.

```
FileNotFoundError: [Errno 2] No such file or directory: '.dist/jaraco.collections-5.1.0-py3-none-any.whl'
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/17110

Also enable check again as tests appear to pass.