[main][grub] Fix file /boot/grub/locale/C.gmo not found
Due to alpine using LANG=C.UTF-8 /etc/grub.d/00_header gets confused and
tries to load C.gmo during boot:

error: file /boot/grub/locale/C.gmo not found

which fails because it does not exist. This commit fixes this (harmless)
warning by correctly setting LANG variable.

Fixes https://gitlab.alpinelinux.org/alpine/aports/issues/10816