community/gnucash: upgrade to 5.13
https://code.gnucash.org/website/news.phtml

Temporarily use `-Wno-error=sign-compare` to rebuild guile bindings due
to signedness mismatch on 32-bit arches.

```
/home/buildozer/aports/community/gnucash/src/gnucash-5.11/build/bindings/guile/swig-app-utils-guile.cpp: In function 'void SWIG_TypeClientData(swig_type_info*, void*)':
/home/buildozer/aports/community/gnucash/src/gnucash-5.11/build/bindings/guile/swig-app-utils-guile.cpp:656:37: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]
  656 |     for (cast = head; (cast - head) <= head->value; cast++) {
      |                       ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/home/buildozer/aports/community/gnucash/src/gnucash-5.11/build/bindings/guile/swig-app-utils-guile.cpp: In function 'void SWIG_PropagateClientData()':
/home/buildozer/aports/community/gnucash/src/gnucash-5.11/build/bindings/guile/swig-app-utils-guile.cpp:2479:41: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]
 2479 |         for (cast = head; (cast - head) <= head->value; cast++) {
      |                           ~~~~~~~~~~~~~~^~~~~~~~~~~~~~

[...]

In file included from /home/buildozer/aports/community/gnucash/src/gnucash-5.11/bindings/guile/gnc-engine-guile.cpp:27:
/home/buildozer/aports/community/gnucash/src/gnucash-5.11/build/common/swig-runtime.h: In function 'void SWIG_TypeClientData(swig_type_info*, void*)':
/home/buildozer/aports/community/gnucash/src/gnucash-5.11/build/common/swig-runtime.h:658:37: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]
  658 |     for (cast = head; (cast - head) <= head->value; cast++) {
      |                       ~~~~~~~~~~~~~~^~~~~~~~~~~~~~

[...]

/home/buildozer/aports/community/gnucash/src/gnucash-5.11/build/bindings/guile/swig-engine.cpp: In function 'void SWIG_TypeClientData(swig_type_info*, void*)':
/home/buildozer/aports/community/gnucash/src/gnucash-5.11/build/bindings/guile/swig-engine.cpp:666:37: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]
  666 |     for (cast = head; (cast - head) <= head->value; cast++) {
      |                       ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/home/buildozer/aports/community/gnucash/src/gnucash-5.11/build/bindings/guile/swig-engine.cpp: In function 'void SWIG_PropagateClientData()':
/home/buildozer/aports/community/gnucash/src/gnucash-5.11/build/bindings/guile/swig-engine.cpp:64195:41: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]
64195 |         for (cast = head; (cast - head) <= head->value; cast++) {
      |                           ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
```