community/i2c-tools: update source url
Switch to an alternate official source to resolve a `403 Forbidden` error when
fetching the archive via busybox wget.

The checksum differs but `diff` identified no changes between the
extracted directories.

```
>>> i2c-tools: Fetching https://fossies.org/linux/misc/i2c-tools-4.4.tar.gz
Connecting to fossies.org (148.251.50.230:443)
wget: server returned error: HTTP/1.1 403 Forbidden
>>> ERROR: i2c-tools: fetch failed
```