community/kalgebra: disable on s390x
ERROR: unable to select packages:
  kconfigwidgets-dev (no such package):
    required by:
.makedepends-kalgebra-20201120.151734[kconfigwidgets-dev]
  kio-dev (no such package):
    required by: .makedepends-kalgebra-20201120.151734[kio-dev]