community/sxmo-utils: fix issues
- Does not amove the desktop files now. It breaks upgrading until pmaports
merge. Let's do it in a second time.

- fix -common dependency to -audio

Cause -audio is a virtual package, it seems like we canno't ask for a
specific version.

ERROR: unable to select packages:
  sxmo-utils-audio-pipewire-1.14.2-r1:
    breaks: sxmo-utils-common-1.14.2-r1[sxmo-utils-audio=1.14.2-r1]
    satisfies: stacy-meta-base-1_git20230709-r0[sxmo-utils-audio]