community/sddm: Fix dbus config filename conflict with lightdm
This fixes the following error while installing sddm and lightdm together.
ERROR: sddm-0.21.0-r4: trying to overwrite usr/share/dbus-1/system.d/org.freedesktop.DisplayManager.conf owned by lightdm-1.32.0-r6.