community/below: upgrade to 0.7.0, disable on 32-bit
    error[E0308]: mismatched types
      --> /home/buildozer/.cargo/registry/src/index.crates.io-1cd66030c949c28d/libbpf-rs-0.20.1/src/program.rs:56:17
       |
    56 |             sz: mem::size_of::<Self>() as u64,
       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    error[E0308]: mismatched types
      --> /home/buildozer/.cargo/registry/src/index.crates.io-1cd66030c949c28d/libbpf-rs-0.20.1/src/program.rs:79:17
       |
    79 |             sz: mem::size_of::<Self>() as u64,
       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    error[E0308]: mismatched types
       --> /home/buildozer/.cargo/registry/src/index.crates.io-1cd66030c949c28d/libbpf-rs-0.20.1/src/program.rs:538:17
        |
    538 |             sz: mem::size_of::<Self>() as u64,
        |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`