community/alembic: rebuild with latest community/hdf5
Currently an old version is linked:

    > doas apk add blender
    ERROR: unable to select packages:
      so:libhdf5.so.310 (no such package):
        required by: alembic-libs-1.8.6-r1[so:libhdf5.so.310]

Fixes: https://gitlab.alpinelinux.org/alpine/aports/-/issues/16092