community/py3-pykwalify: fix tests with ruamel.yaml 0.18
Fix tests using deprecated ruamel.yaml methods.

Example error:

```
    def error_deprecation(fun: Any, method: Any, arg: str = '', comment: str = 'instead of') -> None:  # NOQA
        import inspect

[...]
        if sys.version_info < (3, 10):
            raise AttributeError(s)
        else:
>           raise AttributeError(s, name=None)
E           AttributeError:
E           "safe_load_all()" has been removed, use
E
E             yaml = YAML(typ='safe', pure=True)
E             yaml.load_all(...)
E
E           instead of file "/home/buildozer/aports/community/py3-pykwalify/src/pykwalify-1.8.0/tests/test_core.py", line 570
E
E                           yaml_data = yaml.safe_load_all(stream)

/usr/lib/python3.12/site-packages/ruamel/yaml/main.py:1042: AttributeError

[...]

FAILED tests/test_core.py::TestCore::test_core_files - AttributeError:
FAILED tests/test_unicode.py::TestUnicode::test_files_with_unicode_content_success
FAILED tests/test_unicode.py::TestUnicode::test_files_with_unicode_content_failing
```