community/py3-fiona: remove version constraint on py3-click depends
py3-click has been upgraded to 8.3.1. Lift the version constraint to
enable the aport to rebuild.

```
 >>> py3-fiona: Analyzing dependencies...
 ERROR: unable to select packages:
   py3-click-8.3.1-r1:
     breaks: .makedepends-py3-fiona-20260321.215216[py3-click<8.2]
     satisfies: celery-5.6.2-r1[py3-click]
                py3-click-didyoumean-0.3.1-r2[py3-click]
                py3-click-plugins-2.0_git20240226-r1[py3-click]
                py3-click-repl-0.3.0-r6[py3-click]
                py3-cligj-0.7.2-r6[py3-click]
   .makedepends-py3-fiona-20260321.215216:
     masked in: cache
     satisfies: world[.makedepends-py3-fiona=20260321.215216]
 >>> ERROR: py3-fiona: builddeps failed
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025