community/plasma-wayland-protocols: bump pkgrel to avoid conflicts
this package already existed in 83df2b14e63c8a7b821b389b9a2ab43a8208110d

therefore now half the architectures fail with:
> ERROR: plasma-wayland-protocols-1.12.0-r0: BAD signature