community/py3-pytest-black: upgrade to 0.6.0, switch upstream
https://github.com/coherent-oss/pytest-black/compare/0.3.12...v0.6.0

Previous upstream repo has been archived, maintenance has moved to a new
repo. See: https://github.com/shopkeep/pytest-black/issues/70

Upgrade to 0.6.0 and fix tests with pytest 9.

```
______________________________ test_help_message _______________________________

testdir = <Testdir local('/tmp/pytest-of-builder/pytest-85/test_help_message0')>

    def test_help_message(testdir):
        result = testdir.runpytest("--help")
>       result.stdout.fnmatch_lines(["*--black*enable format checking with black"])
E       Failed: remains unmatched: '*--black*enable format checking with black'

[...]

pytest.PytestRemovedIn9Warning: The (path: py.path.local) argument is deprecated, please use (file_path: pathlib.Path)
```

```
 FAILED tests/test_black.py::test_help_message - Failed: remains unmatched: '*...
 FAILED tests/test_black.py::test_fail - ValueError: Pytest terminal summary r...
 FAILED tests/test_black.py::test_pass - ValueError: Pytest terminal summary r...
 FAILED tests/test_black.py::test_mtime_cache - ValueError: Pytest terminal su...
 FAILED tests/test_black.py::test_exclude - ValueError: Pytest terminal summar...
 FAILED tests/test_black.py::test_exclude_folder - ValueError: Pytest terminal...
 FAILED tests/test_black.py::test_include - ValueError: Pytest terminal summar...
 FAILED tests/test_black.py::test_pytest_deprecation_warning - ValueError: Pyt...
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025