community/py3-openpyxl: fix tests with py3-lxml 6.0.0
Fix xml tests with py3-lxml 6.0.0.

`lxml.etree.fromstring` function raises a `TypeError` with 6.0.0 instead
of a `ValueError` as with 5.x.

```
_ test_iterparse[<?xml version="1.0" encoding="ISO-8859-1"?>\n            <!DOCTYPE foo [\n            <!ELEMENT foo ANY >\n            <!ENTITY xxe SYSTEM "file:///dev/random" >]>\n            <foo>&xxe;</foo>] _
[gw0] linux -- Python 3.12.12 /home/buildozer/aports/community/py3-openpyxl/src/openpyxl-3.1.5/.testenv/bin/python3

[...]

    @pytest.mark.lxml_required
    @pytest.mark.parametrize("xml_input", vulnerable_xml_strings)
    def test_iterparse(xml_input):
        f = BytesIO(xml_input)
        with pytest.raises(ValueError):
>           fromstring(f)

f          = <_io.BytesIO object at 0x7fffaa385e40>
xml_input  = b'<?xml version="1.0" encoding="ISO-8859-1"?>\n            <!DOCTYPE foo [\n            <!ELEMENT foo ANY >\n            <!ENTITY xxe SYSTEM "file:///dev/random" >]>\n            <foo>&xxe;</foo>'

/home/buildozer/aports/community/py3-openpyxl/src/openpyxl-3.1.5/openpyxl/xml/tests/test_functions.py:72:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/lxml/etree.pyx:3428: in lxml.etree.fromstring
    ???
src/lxml/parser.pxi:2059: in lxml.etree._parseMemoryDocument
    ???
src/lxml/parser.pxi:1916: in lxml.etree._parseDoc
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TypeError: memoryview: a bytes-like object is required, not '_io.BytesIO'
```

```
=========================== short test summary info ============================
FAILED openpyxl/xml/tests/test_functions.py::test_iterparse[<?xml version="1.0" encoding="ISO-8859-1"?>\n            <!DOCTYPE foo [\n            <!ELEMENT foo ANY >\n            <!ENTITY xxe SYSTEM "file:///dev/random" >]>\n            <foo>&xxe;</foo>]
FAILED openpyxl/xml/tests/test_functions.py::test_iterparse[<?xml version="1.0" encoding="UTF-8"?>\n          <!DOCTYPE xmlbomb [\n          <!ENTITY a "1234567890" >\n          <!ENTITY b "&a;&a;&a;&a;&a;&a;&a;&a;">\n          <!ENTITY c "&b;&b;&b;&b;&b;&b;&b;&b;">\n          <!ENTITY d "&c;&c;&c;&c;&c;&c;&c;&c;">\n          ]>\n          <foo>&d;</foo>]
FAILED openpyxl/xml/tests/test_functions.py::test_iterparse[<?xml version="1.0" encoding="UTF-8"?>\n          <!DOCTYPE test [\n          <!ENTITY % one SYSTEM "http://127.0.0.1:8100/x.xml" >\n          %one;\n          ]>]
FAILED openpyxl/xml/tests/test_functions.py::test_iterparse[<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n        <!DOCTYPE bomb [\n        <!ENTITY a "{loads_of_bs}">\n        ]>\n        <foo>&a;&a;&a;</foo>]
```