community/gitui: use system zlib-ng, fix build with rust 1.90
Upstream has switched to zlib-ng in the dependencies. Add zlib-ng-dev
to makedepends and adjust `.cargo/config.toml` to use system-provided
zlib-ng.

Fix build error with rust 1.90.

Upstream issue: https://github.com/gitui-org/gitui/issues/2742

```
error: failed to run custom build command for `libz-ng-sys v1.1.21`

Caused by:
  process didn't exit successfully: `/home/buildozer/aports/community/gitui/src/gitui-0.27.0/target/release/build/libz-ng-sys-c9b8b6eaaef06469/build-script-cmake` (exit status: 101)

[...]

 --- stderr
  CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```

```
   Compiling git2-hooks v0.4.0 (/home/builder/builds/gitui/src/gitui-0.27.0/git2-hooks)
error: associated constant `CREATE_NO_WINDOW` is never used
   --> git2-hooks/src/hookspath.rs:214:8
    |
205 | trait CommandExt {
    |       ---------- associated constant in this trait
...
214 |     const CREATE_NO_WINDOW: u32 = 0x0800_0000;
    |           ^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> git2-hooks/src/lib.rs:16:2
    |
 16 |     dead_code,
    |     ^^^^^^^^^

error: could not compile `git2-hooks` (lib) due to 1 previous error
```