testing/sccache: disable on armhf
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully:
`/home/buildozer/aports/testing/sccache/src/sccache-0.2.15/target/release/deps/sccache-b4e7f8a8743fa243`
(signal
: 7, SIGBUS: access to undefined memory)