community/pueue: disable on ppc64le due to build failures
Log below:

error: failed to run custom build command for `ring v0.16.19`

Caused by:
  process didn't exit successfully: `/home/buildozer/aports/community/pueue/src/pueue-0.10.2/target/release/build/ring-c5c457031cdaa898/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/buildozer/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.19/build.rs:375:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed