testing/ttl: upgrade to 0.21.0
Disabled on 32-bit arches due to pnet_sys bug

```
error[E0308]: mismatched types
   --> /builds/alpine/aports/testing/ttl/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pnet_sys-0.35.0/src/unix.rs:109:22
    |
109 |             tv_usec: dur.subsec_micros() as TvUsecType,
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i64`, found `i32`
error: cannot construct `timespec` with struct literal syntax due to private fields
   --> /builds/alpine/aports/testing/ttl/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pnet_sys-0.35.0/src/unix.rs:120:9
    |
120 |         libc::timespec {
    |         ^^^^^^^^^^^^^^
    |
    = note: ...and other private field `__pad0` that was not provided
help: consider using the `Default` trait
    |
120 -         libc::timespec {
121 -             tv_sec: dur.as_secs() as libc::time_t,
122 -             tv_nsec: (dur.subsec_nanos() as TvUsecType).into(),
123 -         }
120 +         <libc::timespec as std::default::Default>::default()
    |
```