main/haproxy: don't override CFLAGS in make
with 'CFLAGS="$CFLAGS"' in make haproxy doesn't start with message
----
FATAL ERROR: invalid code detected -- cannot go further, please
recompile!
----
removal of CFLAGS fixed it