community/py3-spsdk: fix tests with py3-pyscard 2.3.1
Fix test errors due to failed `CardConnection` imports. The
`CardConnection` class was moved to `smartcard.CardConnection` in
pyscard 2.3.1.

```
spsdk/tp/adapters/tpdev_scard.py:29: in <module>
    from smartcard.CardConnectionDecorator import CardConnection
E   ImportError: cannot import name 'CardConnection' from 'smartcard.CardConnectionDecorator' (/usr/lib/python3.12/site-packages/smartcard/CardConnectionDecorator.py). Did you mean: 'CardConnectionEvent'?

The above exception was the direct cause of the following exception:
tests/tp/audit_log/test_audit_log.py:15: in <module>
    from spsdk.tp.tphost import TrustProvisioningHost
spsdk/tp/tphost.py:24: in <module>
    from spsdk.tp.adapters.tptarget_blhost import TpTargetBlHost
spsdk/tp/adapters/__init__.py:11: in <module>
    from spsdk.tp.adapters.tpdev_scard import TpDevSmartCard
spsdk/tp/adapters/tpdev_scard.py:31: in <module>
    raise SPSDKError(
E   spsdk.exceptions.SPSDKError: SPSDK: pyscard package is missing, please install it with pip install 'spsdk[tp]' in order to use TP
__________ ERROR collecting tests/tp/audit_log/test_audit_log_cli.py ___________
spsdk/tp/adapters/tpdev_scard.py:29: in <module>
    from smartcard.CardConnectionDecorator import CardConnection
E   ImportError: cannot import name 'CardConnection' from 'smartcard.CardConnectionDecorator' (/usr/lib/python3.12/site-packages/smartcard/CardConnectionDecorator.py). Did you mean: 'CardConnectionEvent'?
```

```
ERROR tests/tp/audit_log/test_audit_log.py - spsdk.exceptions.SPSDKError: SPS...
ERROR tests/tp/audit_log/test_audit_log_cli.py - spsdk.exceptions.SPSDKError:...
ERROR tests/tp/device/test_tp_dev_models.py - spsdk.exceptions.SPSDKError: SP...
ERROR tests/tp/test_tp_host.py - spsdk.exceptions.SPSDKError: SPSDK: pyscard ...
ERROR tests/tp/test_tp_utils.py - spsdk.exceptions.SPSDKError: SPSDK: pyscard...
ERROR tests/tp/tphost/test_tphost.py - spsdk.exceptions.SPSDKError: SPSDK: py...
ERROR tests/tp/tphost/test_tphost_cli.py - spsdk.exceptions.SPSDKError: SPSDK...
ERROR tests/tp/trgt - spsdk.exceptions.SPSDKError: SPSDK: pyscard package is ...
```