community/py3-rdflib: add py3-html5lib to depends
Fix `ModuleNotFoundError` when importing rdflib.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/rdflib/__init__.py", line 168, in <module>
    from rdflib.graph import ConjunctiveGraph, Dataset, Graph
  File "/usr/lib/python3.12/site-packages/rdflib/graph.py", line 283, in <module>
    import rdflib.namespace as namespace  # noqa: F401 # This is here because it is used in a docstring.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/rdflib/namespace/__init__.py", line 83, in <module>
    from rdflib.term import URIRef, Variable, _is_valid_uri
  File "/usr/lib/python3.12/site-packages/rdflib/term.py", line 68, in <module>
    import html5lib
ModuleNotFoundError: No module named 'html5lib'
```