community/py3-img2pdf: add missing dependency
`py3-setuptools` is required at runtime because /usr/bin/img2pdf
includes the line:

    from pkg_resources import load_entry_point

`pkg_resources` is a part of py3-setuptools:

    $ apk info -W /usr/lib/python3.8/site-packages/pkg_resources/__init__.py
    /usr/lib/python3.8/site-packages/pkg_resources/__init__.py is owned by py3-setuptools-46.1.3-r0

Before this change, img2pdf exits with the error below:

    $ img2pdf --version
    Traceback (most recent call last):
      File "/usr/bin/img2pdf", line 6, in <module>
        from pkg_resources import load_entry_point
    ModuleNotFoundError: No module named 'pkg_resources'

After this change img2pdf succeeds:

    $ img2pdf --version
    img2pdf 0.3.4