community/py3-bioframe: add missing dep on py3-setuptools
top-level pkg_resources import:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/bioframe/io/assembly.py", line 4, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'