community/paper-gtk-theme: switch source to dev.a.o
Upstream repo no longer exists.

```
>>> paper-gtk-theme: Fetching paper-gtk-theme-2.1.0.tar.gz::https://github.com/snwh/paper-gtk-theme/archive/v2.1.0.tar.gz
Connecting to github.com (140.82.121.3:443)
wget: server returned error: HTTP/1.1 404 Not Found
>>> ERROR: paper-gtk-theme: fetch failed
```