testing/elf_diff: fix missing dep
py3-setuptools is actually a runtime dep, not just a makedep. This
fixes:

    $ elf_diff --help
    Traceback (most recent call last):
      File "/usr/bin/elf_diff", line 3, in <module>
        from elf_diff.__main__ import main
      File "/usr/lib/python3.12/site-packages/elf_diff/__main__.py", line 23, in <module>
        from elf_diff.pair_report_document import generateDocument, ValueTreeNode
      File "/usr/lib/python3.12/site-packages/elf_diff/pair_report_document.py", line 36, in <module>
        from elf_diff.binary_pair import BinaryPair, BinaryPairSettings
      File "/usr/lib/python3.12/site-packages/elf_diff/binary_pair.py", line 24, in <module>
        from elf_diff.auxiliary import setIntersection
      File "/usr/lib/python3.12/site-packages/elf_diff/auxiliary.py", line 24, in <module>
        from distutils import dir_util
    ModuleNotFoundError: No module named 'distutils'