community/fractal: add missing xdg-utils dep
without cmd:xdg-open, fractal crashes with the following error
when opening a file:

	thread '<unnamed>' panicked at 'failed to execute process:
	  Os { code: 2, kind: NotFound, message: "No such file or directory" }',
	  fractal-gtk/src/app/backend_loop.rs:175:21