testing/perl-www-curl: Fix issue on build
Perl-www-curl version 4.17 has an upstream issue that causes the
following error:

  curlopt-constants.c:128:49: error: 'CURL_STRICTER' undeclared (first use in this function)
               if (strEQ(name, "STRICTER")) return CURL_STRICTER;

This was fixed upstream on the following commit:

https://anonscm.debian.org/cgit/pkg-perl/packages/libwww-curl-perl.git/commit/?id=d83b9f7

Cherry-picking this patch to Alpine.