community/coretime: fix checksum
Update checksum to fix checksum mismatch error on the 3.24 builders.
Several source files had changed.

```
sha512sum: WARNING: 1 of 1 computed checksums did NOT match
Because the remote file above failed the sha512sum check it will be renamed.
Rebuilding will cause it to re-download which in some cases may fix the problem.
Renaming: coretime-5.0.1.tar.gz to coretime-5.0.1.tar.gz.056b987a
>>> ERROR: coretime: Use 'abuild checksum' to generate/update the checksum(s)
```