Revert "community/ocaml: upgraded to 4.09.0"
This reverts commit d95a53813d93148146b793532b55873416d9af63.

ocaml-camlp4 latest/final version is 4.08 which does not work with ocaml 4.09.
It is better if we keep ocaml 4.08 for 3.11 release and deal with ocaml-camlp4
after release.

$ apk add ocaml-camlp4
ERROR: unsatisfiable constraints:
  ocaml-runtime-4.09.0-r0:
    breaks: ocaml-camlp4-4.08.1-r0[ocaml-runtime~4.08]