community/jetty-runner: fix server_out_log and server_access_log
Jetty requires write permissions to the log directory. :(

> java.io.IOException: Cannot write log directory /var/log