community/anbox: upgrade to 31d584e13d (2021-09-02)
This fixes a build issue:

> external/xdg/xdg.h:94:17: error: 'shared_ptr' in namespace 'std' does
> not name a template type