community/py3-anytree: upgrade to 2.13.0
https://github.com/c0fec0de/anytree/releases/tag/2.13.0

Includes fix for build error:

```
Traceback (most recent call last):
  File "/usr/bin/gpep517", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 238, in main
    return func(args)
           ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 45, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/build.py", line 180, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/poetry/core/masonry/api.py", line 55, in build_wheel
    poetry = Factory().create_poetry(Path().resolve(), with_groups=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/poetry/core/factory.py", line 59, in create_poetry
    raise RuntimeError("The Poetry configuration is invalid:\n" + message)
RuntimeError: The Poetry configuration is invalid:
  - project must contain ['name'] properties
```

Upstream PR: https://github.com/c0fec0de/anytree/pull/271