community/gitu: upgrade to 0.40.0 and fix error
https://github.com/altsem/gitu/releases/tag/v0.40.0
backport patch fix error:
error[E0716]: temporary value dropped while borrowed