community/py3-jwt: upgrade to 2.10.1, fix installer .whl filename
https://github.com/jpadilla/pyjwt/blob/2.10.1/CHANGELOG.rst

Also fix packaging error due to changed .whl filename with setuptools
>= 75.3.1.

```
FileNotFoundError: [Errno 2] No such file or directory: '.dist/PyJWT-2.9.0-py3-none-any.whl'
```