community/py3-paste: disable pkg_resources warning
Fix `test_cgiapp.py` test in part by removing the usage of the deprecated
setuptools `pkg_resources` in the test file. Unfortunately the package
currently uses it in other sections, e.g. in `paste/__init__.py` where
the warning leaks into the test data result, causing the test to fail.
Temporarily filter the `pkg_resources` deprecation warnings until
`pkg_resources` is no longer used.

Upstream issue: https://github.com/pasteorg/paste/issues/107

```
     def test_form():
         app = TestApp(CGIApplication({}, script='form.cgi', path=[data_dir]))
 >       res = app.post('', params={'name': b'joe'},
                        upload_files=[('up', 'file.txt', b'x'*10000)])

 tests/test_cgiapp.py:47:

[...]

    def write(self, value):
        if not value:
            return
>       raise AssertionError(
            "No errors should be written (got: %r)" % value)
E       AssertionError: No errors should be written (got: '/home/buildozer/aports/community/py3-paste/src/paste-3.10.1/tests/cgiapp_data/form.cgi:16: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.\n  import pkg_resources\n')

paste/wsgilib.py:381: AssertionError

[...]

FAILED tests/test_cgiapp.py::test_form - AssertionError: No errors should be ...
```