community/libzmf: fix doc installation failure caused by Doxygen 1.16.1
error log:
```
install: can't stat 'html/*.png': No such file or directory
make[3]: *** [Makefile:480: install-data-am] Error 1
make[3]: Leaving directory '/home/buildozer/aports/community/libzmf/src/libzmf-0.0.2/docs/doxygen'
make[2]: *** [Makefile:369: install-am] Error 2
make[2]: Leaving directory '/home/buildozer/aports/community/libzmf/src/libzmf-0.0.2/docs/doxygen'
make[1]: *** [Makefile:387: install-recursive] Error 1
make[1]: Leaving directory '/home/buildozer/aports/community/libzmf/src/libzmf-0.0.2/docs'
make: *** [Makefile:496: install-recursive] Error 1
>>> ERROR: libzmf*: package failed
>>> ERROR: libzmf: rootpkg failed
```