community/picolibc: fix compilation
This fixes the following compilation error:

    cc1: error: /usr/picolibc/arm-none-eabi/include/../arm-none-eabi/include/c++/16.1.0/arm-none-eabi/thumb/v6-m/nofp: No such file or directory [-Werror=missing-include-dirs]

The issue is that the specs file points to a separate installation of
libstdc++ build against picolibc, which we do not package. But with the
include path injected even into C compilations, we can no longer build
code that does not use libstdc++ at all.

C++ code that actually uses libstdc++ code may not work with picolibc,
though.