main/knot: drop unused variables
Fixes the following linter errors:
```
======================================================
                apkbuild-shellcheck:
======================================================
In ./APKBUILD line 127:
gpg_signature_extensions="asc"
^----------------------^ SC2034 (warning): gpg_signature_extensions appears unused. Verify use (or export if used externally).
In ./APKBUILD line 128:
gpgfingerprints="good:742F A4E9 5829 B6C5 EAC6  B857 10BB 7AF6 FEBB D6AB"
^-------------^ SC2034 (warning): gpgfingerprints appears unused. Verify use (or export if used externally).
For more information:
  https://www.shellcheck.net/wiki/SC2034 -- gpg_signature_extensions appears ...
======================================================
                  apkbuild-lint:
======================================================
IC[AL6]:APKBUILD:127:1:prefix custom variable with _: gpg_signature_extensions
IC[AL6]:APKBUILD:128:1:prefix custom variable with _: gpgfingerprints
Cleaning up project directory and file based variables 00:02
ERROR: Job failed: command terminated with exit code 1
```