testing/k3s: disable on s390x due to build failure
 # golang.org/x/crypto/internal/chacha20
 ../../../../pkg/mod/golang.org/x/crypto@v0.0.0-20190506204251-e1dfcc566284/internal/chacha20/chacha_s390x.go:13:15:
 undefined: "golang.org/x/sys/cpu".S390X
 # golang.org/x/crypto/poly1305
 ../../../../pkg/mod/golang.org/x/crypto@v0.0.0-20190506204251-e1dfcc566284/poly1305/sum_s390x.go:29:5:
 undefined: cpu.S390X
 ../../../../pkg/mod/golang.org/x/crypto@v0.0.0-20190506204251-e1dfcc566284/poly1305/sum_s390x.go:34:6:
 undefined: cpu.S390X