community/certbot-nginx: remove py3-josepy version constraint
Resolve build error due to the specified version of py3-josepy being
unavailable.

```
ERROR: unable to select packages:
  py3-josepy-2.0.0-r1:
    breaks: .makedepends-certbot-nginx-20250504.190125[py3-josepy<2]
    satisfies: certbot-4.0.0-r0[py3-josepy]
               py3-acme-4.0.0-r0[py3-josepy]
```