community/rust: fix build error with rustdoc
Building rust fails with the error:

error[E0523]: found two different crates with name `bitflags` that are not
distinguished by differing `-C metadata`. This will result in symbol conflicts
between the two.
  --> src/librustdoc/html/markdown.rs:36:5
     |
     36 | use pulldown_cmark::{html, CowStr, Event, Options, Parser, Tag};
        |     ^^^^^^^^^^^^^^

Upstream fixed it with the included patch.