community/dqlite: fix build with libuv 1.51.0
Fix build error due to conflicting types.

```
In file included from ␛[01m␛[Ksrc/response.h:4␛[m␛[K,
                 from ␛[01m␛[Ksrc/response.c:1␛[m␛[K:
␛[01m␛[Ksrc/lib/serialize.h:40:16:␛[m␛[K ␛[01;31m␛[Kerror: ␛[m␛[Kconflicting types for '␛[01m␛[Kfloat_t␛[m␛[K'; have '␛[01m␛[Kdouble␛[m␛[K'
   40 | typedef double ␛[01;31m␛[Kfloat_t␛[m␛[K;
      |                ␛[01;31m␛[K^~~~~~~␛[m␛[K
In file included from ␛[01m␛[K/usr/include/math.h:12␛[m␛[K,
                 from ␛[01m␛[K/usr/include/uv.h:61␛[m␛[K,
                 from ␛[01m␛[Ksrc/lib/serialize.h:7␛[m␛[K:
␛[01m␛[K/usr/include/bits/alltypes.h:22:15:␛[m␛[K ␛[01;36m␛[Knote: ␛[m␛[Kprevious declaration of '␛[01m␛[Kfloat_t␛[m␛[K' with type '␛[01m␛[Kfloat_t␛[m␛[K' {aka '␛[01m␛[Kfloat␛[m␛[K'}
   22 | typedef float ␛[01;36m␛[Kfloat_t␛[m␛[K;
      |               ␛[01;36m␛[K^~~~~~~␛[m␛[K
```