testing/sane: rebuild for libnetsnmp.so.35
And remove inelegant "an" wording.

Fixes:
$ apk add -i sane-backends
ERROR: unsatisfiable constraints:
  so:libnetsnmp.so.30 (missing):
    required by: sane-backend-magicolor-1.0.27-r1[so:libnetsnmp.so.30]