community/openexr: fix build with gcc 14
Upstream has since changed the underlying code in the main branch to
work around the error with incompatible pointer types. Use `uLong` type
cast for now to resolve the issue for 32-bit arches.

See: https://github.com/AcademySoftwareFoundation/openexr/issues/1444

The error:

```
/home/buildozer/aports/community/openexr/src/openexr-3.1.13/src/lib/OpenEXRCore/internal_dwa_compressor.h: In function 'exr_compress_buffer':
/home/buildozer/aports/community/openexr/src/openexr-3.1.13/src/lib/OpenEXRCore/internal_dwa_compressor.h:57:21: error: passing argument 2 of 'compress2' from incompatible pointer type [-Wincompatible-pointer-types]
   57 |                     &compbufsz,
      |                     ^~~~~~~~~~
      |                     |
      |                     size_t * {aka unsigned int *}
In file included from /home/buildozer/aports/community/openexr/src/openexr-3.1.13/src/lib/OpenEXRCore/internal_dwa.c:117:
/usr/include/zlib.h:1247:54: note: expected 'uLongf *' {aka 'long unsigned int *'} but argument is of type 'size_t *' {aka 'unsigned int *'}
 1247 | ZEXTERN int ZEXPORT compress2(Bytef *dest,   uLongf *destLen,
      |                                              ~~~~~~~~^~~~~~~
```