community/openpgm: fix build with 32-bit mmx
Fix -Wimplicit-function-declaration error due to undefined
`_mm_cvtm64_si64` function.

```
checksum.c: In function 'do_csumcpy_mmx':
checksum.c:952:34: error: implicit declaration of function
'_mm_cvtm64_si64'; did you mean '_mm_cvtsi64_si32'?
[-Wimplicit-function-declaration]
  952 |                 *(int64_t*)dst = _mm_cvtm64_si64 (tmp);
      |                                  ^~~~~~~~~~~~~~~
      |                                  _mm_cvtsi64_si32
```