community/s2geometry: fix build with swig 4.4.0
The `SWIG_Python_TypeError` method was removed in swig 4.4.0. Replace
with `SWIG_Error`.

Resolves build error:

```
python/CMakeFiles/s2geometry.dir/CMakeFiles/s2geometry.dir/s2PYTHON_wrap.cxx.o -c /home/buildozer/aports/community/s2geometry/src/s2geometry-0.11.1/build/python/CMakeFiles/s2geometry.dir/s2PYTHON_wrap.cxx
/home/buildozer/aports/community/s2geometry/src/s2geometry-0.11.1/build/python/CMakeFiles/s2geometry.dir/s2PYTHON_wrap.cxx: In function 'PyObject* _wrap_S2Polygon_InitNested(PyObject*, PyObject*)':
/home/buildozer/aports/community/s2geometry/src/s2geometry-0.11.1/build/python/CMakeFiles/s2geometry.dir/s2PYTHON_wrap.cxx:20173:9: error: 'SWIG_Python_TypeError' was not declared in this scope; did you mean 'SWIG_Python_TypeQuery'?
20173 |         SWIG_Python_TypeError(SWIG_TypePrettyName(SWIGTYPE_p_S2Loop), element);
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         SWIG_Python_TypeQuery
```