main/xtables-addons-vanilla: add replaces hardened
this should fix when you have xtables-hardened installed, but not the
xtables-vanilla and do apk upgrade -U -a, which gives:

ERROR: unsatisfiable constraints:
  xtables-addons-vanilla-4.14.13-r2:
    conflicts:
xtables-addons-hardened-4.9.73-r1[xtables-addons-grsec=4.14.13-r2]
  xtables-addons-hardened-4.9.73-r1:
    conflicts:
xtables-addons-vanilla-4.14.13-r2[xtables-addons-grsec=4.9.73-r1]