community/vkmark: patch missing cstdint include
Fixes build errors like:

```
In file included from ../tests/test_scene.h:23,
                 from ../tests/test_scene.cpp:23:
../src/scene.h:79:5: error: 'uint64_t' does not name a type
   79 |     uint64_t start_time;
      |     ^~~~~~~~
../src/scene.h:28:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
```