community/py-opencl: disable ppc64le
Fails to compile. Error out with:

/usr/include/c++/8.3.0/chrono:826:38:   required from here
/usr/include/c++/8.3.0/type_traits:1925:64: error: 'value' is not a member of 'std::is_array<long int>'
       typedef typename __decay_selector<__remove_type>::__type type;
                                                                ^~~~
In file included from /usr/include/c++/8.3.0/thread:38,
                 from src/wrap_cl.hpp:76,
                 from src/wrap_constants.cpp:27:
/usr/include/c++/8.3.0/chrono: In instantiation of 'constexpr unsigned int std::chrono::operator<(const std::chrono::duration<_Rep1, _Period1>&, const std::chrono::duration<_Rep2, _Period2>&) [with _Rep1 = long int; _Period1 = std::ratio<1, 1000000000>; _Rep2 = long int; _Period2 = std::ratio<1, 1000000000>]':
/usr/include/c++/8.3.0/chrono:826:38:   required from here
/usr/include/c++/8.3.0/chrono:564:52: error: no type named 'type' in 'struct std::common_type<std::chrono::duration<long int, std::ratio<1, 1000000000> >, std::chrono::duration<long int, std::ratio<1, 1000000000> > >'
  typedef typename common_type<__dur1,__dur2>::type __ct;
                                                    ^~~~
error: command 'gcc' failed with exit status 1
>>> ERROR: py-opencl: build failed
>>> py-opencl: Uninstalling dependencies...