community/py3-readability-lxml: fix test with python 3.14
Replace the use of timeout-decorator to avoid test error from the
default `multiprocessing.Process` behaviour. The default multiprocessing
start method in python 3.14 is `forkserver`, which appears to cause
tests to fail in some instances.

```
ERROR: test_many_repeated_spaces (tests.test_article_only.TestArticleOnly.test_many_repeated_spaces)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.14/site-packages/timeout_decorator/timeout_decorator.py", line 92, in new_function
    return timeout_wrapper(*args, **kwargs)
  File "/usr/lib/python3.14/site-packages/timeout_decorator/timeout_decorator.py", line 147, in __call__
    self.__process.start()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.14/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.14/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.14/multiprocessing/context.py", line 300, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.14/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^

[...]

_pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7f5cde0d0250>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spaces
when serializing tuple item 1
when serializing dict item '_args'
when serializing multiprocessing.context.Process state
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025