testing/py-pygfm: disable on armv7 due to failing tests
======================================================================
ERROR: test_autolink (test_gfm.TestGfm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File
"/home/buildozer/aports/testing/py-pygfm/src/py-gfm-0.1.4/tests/test_gfm.py",
line 109, in test_autolink
    """, ['gfm'])
  File
"/home/buildozer/aports/testing/py-pygfm/src/py-gfm-0.1.4/tests/test_case.py",
line 32, in assert_renders
    expected, markdown.markdown(source, extensions=extensions))
  File "/usr/lib/python2.7/site-packages/markdown/core.py", line 390, in
markdown
    md = Markdown(**kwargs)
  File "/usr/lib/python2.7/site-packages/markdown/core.py", line 100, in
__init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/lib/python2.7/site-packages/markdown/core.py", line 126, in
registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/lib/python2.7/site-packages/markdown/core.py", line 166, in
build_extension
    module = importlib.import_module(ext_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in
import_module
    __import__(name)
  File
"/home/buildozer/aports/testing/py-pygfm/src/py-gfm-0.1.4/gfm/__init__.py",
line 11, in <module>
    from gfm import autolink
ImportError: Failed loading extension "gfm".