testing/mapnik: Added missing dependency icu-libs.
A user reported the following error:

  ERROR: unsatisfiable constraints:
  so:libicuuc.so.59 (missing):
  required by:
  mapnik-3.0.15-r0[so:libicuuc.so.59]
  mapnik-3.0.15-r0[so:libicuuc.so.59]

libicuuc.so.59 is part of the icu-libs package.