main/py3-tox: add missing dependency
Before this change:

    $ dabuild sh
    $ sudo apk add py3-tox >/dev/null && tox --version
    Traceback (most recent call last):
      File "/usr/bin/wheel", line 6, in <module>
        from pkg_resources import load_entry_point
    ModuleNotFoundError: No module named 'pkg_resources'

This change adds py3-setuptools as a runtime dependency because
pkg_resources is imported by a file installed into /usr/bin/:

    $ grep pkg_resources /usr/bin/tox
    from pkg_resources import load_entry_point

pkg_resources is part of py3-setuptools:

    $ apk info -L py3-setuptools | grep pkg_resources/__init__.py
    usr/lib/python3.8/site-packages/pkg_resources/__init__.py

After this change:

    $ dabuild sh
    $ sudo apk add py3-tox >/dev/null && tox --version
    3.14.6 imported from /usr/lib/python3.8/site-packages/tox/__init__.py