community/apache-orc: rebuild to fix ceph17/18
This seems to be the missing rebuild that fixes ceph17/18,
for future reference, the errors seen were:

/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libarrow.so: undefined reference to `google::protobuf::io::ZeroCopyOutputStream::WriteCord(absl::lts_20230802::Cord const&)'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libarrow.so: undefined reference to `google::protobuf::io::ZeroCopyInputStream::ReadCord(absl::lts_20230802::Cord*, int)'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libarrow.so: undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const* (*)(), absl::lts_20230802::once_flag*, google::protobuf::Metadata const&)'