Revert "main/argon2: upgrade to 20190702"
build fails with:

>>> argon2-libs*: Preparing subpackage argon2-libs...
/usr/bin/abuild: cd: line 2293: can't cd to
/home/ncopa/aports/main/argon2/pkg/argon2-libs: No such file or
directory
>>> ERROR: argon2-libs*: prepare_package failed

This reverts commit eb606b4367c2028e1deb01f456063d80f13663e4.