community/libinput: mark udev subpkg as arch-specific
Currently -udev subpackages are set to `noarch` by default. Mark the
subpackage as having arch-specific binaries by setting the arch to
`all`.

```
>>> libinput-udev*: Running split function udev...
'usr/lib/udev' -> '/home/buildozer/aports/community/libinput/pkg/libinput-udev/usr/lib/udev'
>>> libinput-udev*: Preparing subpackage libinput-udev...
>>> ERROR: libinput-udev*: Arch specific binaries found so arch must not be set to "noarch"
```

Ref: https://gitlab.alpinelinux.org/alpine/abuild/-/commit/758b135ca9cff12726cf15fa7349ce40d42b18dc