community/vint: fix tests, build with gpep517
Backport patches to fix tests which failed due to the import of
`pkg_resources` emitting a deprecation warning. The import was used in
version handling and has been replaced upstream with `setuptools_scm`.

```
def test_exec_vint_with_no_args(self):
        cmd = ['bin/vint']

        with self.assertRaises(subprocess.CalledProcessError) as context_manager:
            subprocess.check_output(cmd,
                                    stderr=subprocess.STDOUT,
                                    universal_newlines=True)

        got_output = context_manager.exception.output

        expected_output_pattern = r'^vint ERROR:'
>       self.assertRegex(got_output, expected_output_pattern)

test/acceptance/test_cli.py:72:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/acceptance/test_cli.py:14: in assertRegex
    super(TestCLI, self).assertRegex(string, pattern)
E   AssertionError: Regex didn't match: '^vint ERROR:' not found in "/home/buildozer/aports/community/vint/src/vint-0.3.21/vint/linting/cli.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.\n  import pkg_resources\nvint

[...]

FAILED test/acceptance/test_cli.py::TestCLI::test_exec_vint_with_no_args - As...
FAILED test/acceptance/test_cli.py::TestCLI::test_exec_vint_with_unexistent_file
FAILED test/acceptance/test_cli.py::TestCLI::test_exec_vint_with_verbose_flag
```

Build with gpep517 in preparation for the deprecation of setuptools
`setup.py` commands.

Remove `01-python3-shebang.patch` as it is no longer needed for the
script to run.