community/ansible-lint: add missing dependency on py3-filelock
Doesn't work without it:

> Traceback (most recent call last):
>   File "/usr/bin/ansible-lint", line 5, in <module>
>     from ansiblelint.__main__ import _run_cli_entrypoint
>   File "/usr/lib/python3.10/site-packages/ansiblelint/__main__.py", line 38, in <module>
>     from filelock import FileLock, Timeout
> ModuleNotFoundError: No module named 'filelock'