community/opensubdiv: fix build with ptex-2.5.2
From build log:
--
ninja: job failed: /usr/bin/c++ -DGLFW_VERSION_3 -DOPENSUBDIV_HAS_GLSL_COMPUTE -DOPENSUBDIV_HAS_GLSL_TRANSFORM_FEEDBACK -DOPENSUBDIV_HAS_OPENCL -DOPENSUBDIV_HAS_OPENGL -DOPENSUBDIV_HAS_OPENMP -DOPENSUBDIV_HAS_PATCH_SHADER_SOURCE_GLSL -DOPENSUBDIV_HAS_PTEX -DOPENSUBDIV_HAS_TBB -DOPENSUBDIV_VERSION_STRING=\"3.6.1\" -DOSD_USES_INTERNAL_GLAPILOADER -DPTEX_STATIC -I/home/buildozer/aports/community/opensubdiv/src/OpenSubdiv-3_6_1 -I/home/buildozer/aports/community/opensubdiv/src/OpenSubdiv-3_6_1/glLoader -I/home/buildozer/aports/community/opensubdiv/src/OpenSubdiv-3_6_1/build/examples/glPtexViewer -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST  -O3 -DNDEBUG -std=c++14   -Wall -Wextra -Wno-invalid-offsetof -Wno-strict-aliasing -fopenmp -MD -MT examples/glPtexViewer/CMakeFiles/glPtexViewer.dir/glPtexViewer.cpp.o -MF examples/glPtexViewer/CMakeFiles/glPtexViewer.dir/glPtexViewer.cpp.o.d -o examples/glPtexViewer/CMakeFiles/glPtexViewer.dir/glPtexViewer.cpp.o -c /home/buildozer/aports/community/opensubdiv/src/OpenSubdiv-3_6_1/examples/glPtexViewer/glPtexViewer.cpp
In file included from /usr/include/CL/cl.h:20,
                 from /usr/include/CL/opencl.h:24,
                 from /home/buildozer/aports/community/opensubdiv/src/OpenSubdiv-3_6_1/opensubdiv/osd/../osd/opencl.h:34,
                 from /home/buildozer/aports/community/opensubdiv/src/OpenSubdiv-3_6_1/opensubdiv/osd/clEvaluator.h:30,
                 from /home/buildozer/aports/community/opensubdiv/src/OpenSubdiv-3_6_1/examples/glPtexViewer/glPtexViewer.cpp:52:
/usr/include/CL/cl_version.h:22:104: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |                                                                                                        ^
In file included from /home/buildozer/aports/community/opensubdiv/src/OpenSubdiv-3_6_1/examples/glPtexViewer/glPtexViewer.cpp:79:
/usr/include/PtexUtils.h:59:12: error: 'clamp' has not been declared in 'std'
   59 | using std::clamp;
      |            ^~~~~
--

The fallback c++ standard that the CMakeLists.txt uses is 14, but c++17
is needed for std::clamp. Add -DCMAKE_CXX_STANDARD=17. The change in
ptex was introduced with ptex-2.5.2.