community/yubikey-manager-qt: add missing dependency on yubikey-manager
otherwise, this happens:
    qml: Function not found: 'yubikey.init' (Traceback (most recent call last):
      File "<string>", line 1, in <module>
    NameError: name 'yubikey' is not defined