testing/hypnotix: remove gettext-tiny-dev makedepends
It conflicts with musl-libintl:

> ERROR: gettext-tiny-dev-0.3.2-r0: trying to overwrite
> usr/include/libintl.h owned by musl-libintl-1.2.2-r2.