testing/sslscan: disable on x86 due to build failure
Fails with:
>>> ERROR: sslscan*: Found textrels:
TEXTREL /home/buildozer/aports/testing/sslscan/pkg/sslscan/usr/bin/sslscan