community/hugo: upgrade to 0.147.2
https://github.com/gohugoio/hugo/releases/tag/v0.147.2
https://github.com/gohugoio/hugo/releases

Fix `TestVimeoShortcode` test, skip `TestSilenceDependencyDeprecations` test.

```
--- FAIL: TestVimeoShortcode (0.35s)
    shortcodes_integration_test.go:486:
        error:
          no substring match found

[...]

        stack:
          github.com/gohugoio/hugo/hugolib/integrationtest_builder.go:323
            <cannot parse source file: open github.com/gohugoio/hugo/hugolib/integrationtest_builder.go: no such file or directory>
          github.com/gohugoio/hugo/tpl/tplimpl/shortcodes_integration_test.go:486
            <cannot parse source file: open github.com/gohugoio/hugo/tpl/tplimpl/shortcodes_integration_test.go: no such file or directory>

FAIL
FAIL	github.com/gohugoio/hugo/tpl/tplimpl	2.804s
```