community/java-jffi: set JAVA_HOME path
Resolve build error on loongarch64 and s390x due to header file mismatch.

```
    [exec] make[1]: Leaving directory '/home/buildozer/aports/community/java-jffi/src/jffi-jffi-1.3.13/build/jni/libffi-loongarch64-linux'
     [exec] /home/buildozer/aports/community/java-jffi/src/jffi-jffi-1.3.13/jni/jffi/Array.c:37:10: fatal error: jni.h: No such file or directory
     [exec]    37 | #include <jni.h>
     [exec]       |          ^~~~~~~
     [exec] compilation terminated.
     [exec] make: *** [/home/buildozer/aports/community/java-jffi/src/jffi-jffi-1.3.13/jni/GNUmakefile:273: /home/buildozer/aports/community/java-jffi/src/jffi-jffi-1.3.13/build/jni/jffi/Array.o] Error 1
```