testing/hw-probe: add missing dependency on xz
When xz is missing the following error occurs:

```
/ # hw-probe -probe -upload
WARNING: 'edid-decode' package is not installed
Probe for hardware ... Ok
BusyBox v1.31.1 () multi-call binary.

Usage: xz -d [-cfk] [FILE]...

Decompress FILE (or stdin)

        -d      Decompress
        -c      Write to stdout
        -f      Force
        -k      Keep input files
tar: write error: Broken pipe
ERROR: unsupported probe format '/tmp/phpfDOZvo'
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
ERROR: not enough info collected
ERROR: failed to upload probe
```

Also fixes the following lint issues:
- MC:[AL1]:APKBUILD:16:builddir can be removed as it is the default value
- TP:[AL3]:APKBUILD:3:pkgname must not be quoted