main/py3-virtualenv: add missing depends & new URL
Dependencies are listed at
https://github.com/pypa/virtualenv/blob/20.2.2/setup.cfg#L42

Before this change

    $ sudo apk add py3-virtualenv
    ✂
    (13/13) Installing py3-virtualenv (20.2.2-r1)
    Executing busybox-1.33.0-r2.trigger
    OK: 271 MiB in 71 packages
    $ virtualenv --version
    Traceback (most recent call last):
      File "/usr/bin/virtualenv", line 33, in <module>
        sys.exit(load_entry_point('virtualenv==20.2.2', 'console_scripts', 'virtualenv')())
      File "/usr/bin/virtualenv", line 25, in importlib_load_entry_point
        return next(matches).load()
      File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
        module = import_module(match.group('module'))
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/lib/python3.8/site-packages/virtualenv/__init__.py", line 3, in <module>
        from .run import cli_run, session_via_cli
      File "/usr/lib/python3.8/site-packages/virtualenv/run/__init__.py", line 6, in <module>
        from ..app_data import make_app_data
      File "/usr/lib/python3.8/site-packages/virtualenv/app_data/__init__.py", line 9, in <module>
        from appdirs import user_data_dir
    ModuleNotFoundError: No module named 'appdirs'

After this change:

    ~/aports/main/py3-virtualenv $ sudo apk add py3-virtualenv
    ✂
    (15/15) Installing py3-virtualenv (20.2.2-r2)
    Executing busybox-1.33.0-r2.trigger
    OK: 272 MiB in 73 packages
    $ virtualenv --version
    virtualenv 20.2.2 from /usr/lib/python3.8/site-packages/virtualenv/__init__.py