community/py3-pyzbar: build with gpep517, fix running tests
Switch to gpep517 and fix check failure due to removed `setup.py test` command,
which was deprecated in setuptools 72.0.0.

```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'test'
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/17110