community/py-opencl: disable check, tests are broken
`setup.py test` downloads some Python modules needed for running tests.
They now fail even on the previous version, so it's probably caused by
some change in one of the module downloaded on-demand.
It must be fixed to not download some arbitrary modules, so the build is
reproducible.

    pyopencl.compyte.ndarray.test_gpu_ndarray (unittest.loader.ModuleImportFailure) ... ERROR
    pyopencl.compyte.ndarray.test_gpu_elemwise (unittest.loader.ModuleImportFailure) ... ERROR

    ======================================================================
    ERROR: pyopencl.compyte.ndarray.test_gpu_ndarray (unittest.loader.ModuleImportFailure)
    ----------------------------------------------------------------------
    ImportError: Failed to import test module: pyopencl.compyte.ndarray.test_gpu_ndarray
    Traceback (most recent call last):
      File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
        module = self._get_module_from_name(name)
      File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
        __import__(name)
      File "/home/buildozer/aports/community/py-opencl/src/pyopencl-2017.2.2/pyopencl/compyte/ndarray/test_gpu_ndarray.py", line 7, in <module>
        import pygpu_ndarray as gpu_ndarray
    ImportError: No module named pygpu_ndarray

    ======================================================================
    ERROR: pyopencl.compyte.ndarray.test_gpu_elemwise (unittest.loader.ModuleImportFailure)
    ----------------------------------------------------------------------
    ImportError: Failed to import test module: pyopencl.compyte.ndarray.test_gpu_elemwise
    Traceback (most recent call last):
      File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
        module = self._get_module_from_name(name)
      File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
        __import__(name)
      File "/home/buildozer/aports/community/py-opencl/src/pyopencl-2017.2.2/pyopencl/compyte/ndarray/test_gpu_elemwise.py", line 4, in <module>
        import theano
    ImportError: No module named theano

  ----------------------------------------------------------------------
  Ran 2 tests in 0.000s