community/py3-xarray: upgrade to 2025.4.0, skip failed tests on 32-bit arches
https://github.com/pydata/xarray/releases/tag/v2025.04.0
https://github.com/pydata/xarray/releases/tag/v2025.03.1
https://github.com/pydata/xarray/releases/tag/v2025.03.0
https://github.com/pydata/xarray/releases/tag/v2025.01.2
https://github.com/pydata/xarray/releases/tag/v2025.01.1
https://github.com/pydata/xarray/releases/tag/v2025.01.0

Also add patch to remove unrecognised pytest options, and skip failed
tests on 32-bit arches.

```
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --mypy-only-local-stub --mypy-pyproject-toml-file=pyproject.toml
  inifile: [...]/py3-xarray/src/xarray-2025.4.0/pyproject.toml
  rootdir: [...]/py3-xarray/src/xarray-2025.4.0
```