community/zigbee2mqtt: disable on riscv64 due to build failure
    > zigbee2mqtt@1.36.1 build
    > tsc
    /builds/alpine/aports/community/zigbee2mqtt/src/zigbee2mqtt-1.36.1/node_modules/typescript/lib/tsc.js:118617
          throw e;
          ^
    RangeError: Maximum call stack size exceeded