community/xscreensaver: upgrade to 6.15
https://www.jwz.org/xscreensaver/changelog.html

Resolves `404 Not Found` error when fetching `xscreensaver-6.13.tar.gz`.

Remove the `--with-xf86vmode-ext` option as it is no longer recognised.

```
configure: WARNING: unrecognized options: --with-xf86vmode-ext
current directory: [...]/xscreensaver-6.15
command line was: ./configure --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --prefix=/usr --sysconfdir=/etc --mandir=/usr/share/man --infodir=/usr/share/info --with-gtk --with-xinerama-ext --with-xf86vmode-ext --with-randr-ext --with-elogind

>>> ERROR: xscreensaver: build failed
```