testing/openconnect-sso: disable on x86
```
ERROR: unable to select packages:
  .makedepends-openconnect-sso-20260331.005338:
    masked in: cache
    satisfies: world[.makedepends-openconnect-sso=20260331.005338]
  py3-pyqt6-webengine (no such package):
    required by: .makedepends-openconnect-sso-20260331.005338[py3-pyqt6-webengine]
```