community/gvmd: replace libpq-dev with postgresql-dev
This reverts part of commit 2cf3fe063b1b9e308372af7e2c2348e9e494a135.

gvmd needs postgresql.h:

    /builds/alpine/aports/community/gvmd/src/gvmd-21.4.3/src/manage_pg_server.c:29:10: fatal error: postgres.h: No such file or directory
       29 | #include "postgres.h"
	  |          ^~~~~~~~~~~~