testing/pdal-python-plugins: upgrade to 1.6.2
https://github.com/PDAL/python-plugins/compare/1.2.1...1.6.2

- 1.6.2 includes numpy 2.1 support
- 1.6.1 includes pdal 2.8.0 support

Resolves build errors in 1.2.1 with pdal 2.8.0+:

```
/home/builder/builds/pdal-python-plugins/src/pdal-plugins-1.2.1/pdal/plang/Invocation.cpp: In member function 'void* pdal::plang::Invocation::extractArray(PyObject*, const std::string&, pdal::Dimension::Type, size_t&)':
/home/builder/builds/pdal-python-plugins/src/pdal-plugins-1.2.1/pdal/plang/Invocation.cpp:260:38: error: 'PyArray_Descr' has no member named 'elsize'
  260 |     if (static_cast<uint32_t>(dtype->elsize) != Dimension::size(t))
      |                                      ^~~~~~
/home/builder/builds/pdal-python-plugins/src/pdal-plugins-1.2.1/pdal/plang/Invocation.cpp:263:53: error: 'PyArray_Descr' has no member named 'elsize'
  263 |         oss << "dtype of array has size " << dtype->elsize
      |                                                     ^~~~~~
```