community/libreoffice: upgrade to 7.2.2.2
Co-Authored-By: Rasmus Thomsen <oss@cogitri.dev>

Squashed commits:

community/libreoffice: force ant using OpenJDK 11

community/libreoffice: upgrade to 7.1.5.2

community/libreoffice: disable java

community/libreoffice: upgrade to 7.2.0.4

community/libreoffice: upgrade to 7.2.1.2

community/libreoffice: downgrade external skia source to expected version

community/libreoffice: fix issues with newer freetype

community/libreoffice: remove backtrace references and use vendored libcmis

Also removed sdk subpackage, doesn't seem to exist anymore

community/libreoffice: disable on armhf

/builds/alpine/aports/community/libreoffice/src/libreoffice-7.2.1.2/workdir/UnpackedTarball/pdfium/third_party/base/allocator/partition_allocator/spin_lock.cpp:83:9: error: instruction requires: armv6k
        YIELD_PROCESSOR;
        ^

community/libreoffice: build with clang rather than gcc

community/libreoffice: upgrade to 7.2.2.2