testing/py3-xdoctest: upgrade to 1.3.2
https://github.com/Erotemic/xdoctest/releases/tag/v1.3.2
https://github.com/Erotemic/xdoctest/releases/tag/v1.3.1
https://github.com/Erotemic/xdoctest/releases/tag/v1.3.0

1.3.0 includes python 3.14 support.

Resolves `AttributeError: 'Constant' object has no attribute 's'` error when
rebuilding against python 3.14.

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025