testing/ocaml-lambda-term: disable on ppc64le due to build failure
       ocamlopt tools/lambda_term_actions.exe (exit 2)
    (cd _build/default && /usr/bin/ocamlopt.opt -w -40 -safe-string -g -o tools/lambda_term_actions.exe -I /usr/lib/ocaml/bytes -I /usr/lib/ocaml/camomile -I /usr/lib/ocaml/lwt -I /usr/lib/ocaml/lwt_react -I /usr/lib/ocaml/react -I /usr/lib/ocaml/result -I /usr/lib/ocaml/threads -I /usr/lib/ocaml/zed -I src /usr/lib/ocaml/result/result.cmxa /usr/lib/ocaml/lwt/lwt.cmxa /usr/lib/ocaml/unix.cmxa /usr/lib/ocaml/bigarray.cmxa /usr/lib/ocaml/lwt/lwt_log.cmxa /usr/lib/ocaml/threads/threads.cmxa /usr/lib/ocaml/lwt/lwt_unix.cmxa /usr/lib/ocaml/react/react.cmxa /usr/lib/ocaml/lwt_react/lwt_react.cmxa /usr/lib/ocaml/camomile/camomile.cmxa /usr/lib/ocaml/zed/zed.cmxa src/lambda_term.cmxa tools/.lambda_term_actions.eobjs/lambda_term_actions.cmx)
    /usr/lib/gcc/powerpc64le-alpine-linux-musl/6.4.0/../../../../powerpc64le-alpine-linux-musl/bin/ld: /usr/lib/ocaml/lwt/liblwt_unix_stubs.a(unix_lseek_job.o): In function `result_lseek':
    /home/buildozer/aports/testing/ocaml-lwt/src/lwt-3.2.1/_build/default/src/unix/unix_lseek_job.c:113:(.text+0xb8): call to `result_lseek.part.0' lacks nop, can't restore toc; (-mcmodel=small toc adjust stub)
    /usr/lib/gcc/powerpc64le-alpine-linux-musl/6.4.0/../../../../powerpc64le-alpine-linux-musl/bin/ld: /usr/lib/ocaml/lwt/liblwt_unix_stubs.a(unix_lseek_job.o): In function `result_lseek_64':
    /home/buildozer/aports/testing/ocaml-lwt/src/lwt-3.2.1/_build/default/src/unix/unix_lseek_job.c:134:(.text+0x134): call to `result_lseek_64.part.1' lacks nop, can't restore toc; (-mcmodel=small toc adjust stub)
    /usr/lib/gcc/powerpc64le-alpine-linux-musl/6.4.0/../../../../powerpc64le-alpine-linux-musl/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    File "caml_startup", line 1:
    Error: Error during linking