main/d-feet: add missing gtk+3.0 dependency
Traceback (most recent call last):
  File "/usr/bin/d-feet", line 44, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 3.0