testing/cmocka: disable on aarch64 due to build error
[  1%] Building C object src/CMakeFiles/cmocka_shared.dir/cmocka.c.o
[  3%] Building C object src/CMakeFiles/cmocka_static.dir/cmocka.c.o
In file included from /home/buildozer/aports/testing/cmocka/src/cmocka-1.1.0/src/cmocka.c:61:0:
/home/buildozer/aports/testing/cmocka/src/cmocka-1.1.0/include/cmocka.h:126:28: error: conflicting types for 'uintptr_t'
       typedef unsigned int uintptr_t;
                            ^~~~~~~~~
In file included from /home/buildozer/aports/testing/cmocka/src/cmocka-1.1.0/src/cmocka.c:61:0:
/home/buildozer/aports/testing/cmocka/src/cmocka-1.1.0/include/cmocka.h:126:28: error: conflicting types for 'uintptr_t'
       typedef unsigned int uintptr_t;
                            ^~~~~~~~~
In file included from /usr/include/stdint.h:20:0,
                 from /usr/include/inttypes.h:9,
                 from /home/buildozer/aports/testing/cmocka/src/cmocka-1.1.0/src/cmocka.c:27:
/usr/include/bits/alltypes.h:109:24: note: previous declaration of 'uintptr_t' was here
 typedef unsigned _Addr uintptr_t;
                        ^~~~~~~~~
In file included from /usr/include/stdint.h:20:0,
                 from /usr/include/inttypes.h:9,
                 from /home/buildozer/aports/testing/cmocka/src/cmocka-1.1.0/src/cmocka.c:27:
/usr/include/bits/alltypes.h:109:24: note: previous declaration of 'uintptr_t' was here
 typedef unsigned _Addr uintptr_t;