community/modemmanager: update initd to depend on polkit
Without polkit, modemmanager logs a warning at start-up:

  <wrn> [auth-provider] failed to create PolicyKit authority: 'Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: Failed to execute program org.freedesktop.PolicyKit1: No such file or directory'

Attempting to control modemmanager fails with an error:

  error: couldn't disable the modem: 'GDBus.Error:org.freedesktop.ModemManager1.Error.Core.Failed: PolicyKit authorization error: 'authority not found''

Add polkit as a dependency for the modemmanager service. The latter is
unusable if the former does not start first.