community/rng-tools: downgrade to 6.3.1 since does not build on ppc64le
rngd_darn.c: In function 'refill_rand':
rngd_darn.c:129:15: error: 'struct rng' has no member named 'options'; did you mean 'rng_options'?
  if (ent_src->options[DARN_USE_AES].int_val) {
               ^~~~~~~