community/dockviz: disable on armv7
>>> dockviz: Analyzing dependencies...
ERROR: unable to select packages:
  containerd (no such package):
    required by: docker-engine-19.03.14-r1[containerd]
  tini-static (no such package):
    required by: docker-engine-19.03.14-r1[tini-static]
>>> ERROR: dockviz: builddeps failed