main/arpwatch: fix build problem, add doc subpackage
Without the chmod the following occur in the prepare phase:

```
>>> arpwatch: 21_all_arpwatch-2.1a15-pid-filename.patch
File arpwatch.8 is read-only; trying to patch anyway
patching file arpwatch.8
File arpwatch.h is read-only; trying to patch anyway
patching file arpwatch.h
File arpwatch.c is read-only; trying to patch anyway
patching file arpwatch.c
>>> arpwatch: 22_alpine_bihourly_script.patch
File bihourly.sh is read-only; trying to patch anyway
patching file bihourly.sh
>>> arpwatch: Updating ./config.sub
cp: cannot create regular file './config.sub': Permission denied
>>> ERROR: arpwatch: prepare failed
```

Some lint problems were addressed, but more remain as the patches do
not have descriptions.  I don't fully understand what each patch does,
so I did not attempt to address those lint problems.

The manpages and project docs are now installed in a doc
package.

Finally, the a sed command was added to install files as root:root
instead of bin:bin.