comunity/gnome-passwordsafe: add missing dependency on py3-cairo
Opening some entries crashes gnome-passwordsafe if py3-cairo is not installed,
with:

    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/gsecrets/widgets/progress_icon.py", line 20, in do_snapshot_symbolic
        ctx = snapshot.append_cairo(rect)
    TypeError: Couldn't find foreign struct converter for 'cairo.Context'