community/warp: upgrade to 0.8.0
https://gitlab.gnome.org/World/warp/-/tags/v0.8.0

Also resolves `error[E0282]: type annotations needed for 'Box<_>'` error
in time crate with Rust >=1.8.0.