testing/keepassxc-proxy-static: disable on aarch64 due to build failure
    error[E0425]: cannot find value `MAP_32BIT` in crate `libc`
      --> /home/buildozer/aports/testing/keepassxc-proxy-static/src/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.11.0/src/sys/mman.rs:53:9
       |
    53 |         MAP_32BIT;
       |         ^^^^^^^^^ not found in `libc`

    error: aborting due to previous error