community/grommunio-admin-web: limit jobs on 32-bit arm
Limit jobs on 32-bit arm to potentially avoid OOM error on the 3.24
armhf and armv7 builders.

```
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

<--- Last few GCs --->

[2431:0xb1df6000]     2136 ms: Scavenge 13.4 (18.7) -> 10.7 (26.9) MB, pooled: 0 MB, 6.57 / 0.00 ms  (average mu = 1.000, current mu = 1.000) task;
[2431:0xb1df6000]     2183 ms: Mark-Compact 10.8 (26.9) -> 8.8 (26.8) MB, pooled: 0 MB, 5.78 / 0.00 ms  (+ 31.7 ms in 99 steps since start of marking, biggest step 1.3 ms, walltime since start of marking 47 ms) (average mu = 0.983, current mu = 0.983) fin

<--- Last few GCs --->

[2431:0xc510b000]     2279 ms: Scavenge 13.7 (18.4) -> 10.4 (26.6) MB, pooled: 0 MB, 6.63 / 0.00 ms  (average mu = 1.000, current mu = 1.000) allocation failure;
[2431:0xc510b000]     2361 ms: Mark-Compact 12.9 (26.6) -> 8.7 (26.6) MB, pooled: 0 MB, 10.11 / 0.00 ms  (+ 31.6 ms in 100 steps since start of marking, biggest step 1.3 ms, walltime since start of marking 50 ms) (average mu = 0.983, current mu = 0.983) f
FATAL ERROR: Zone Allocation failed - process out of memory
----- Native stack trace -----
```