testing/cpplint: rebuild against python 3.14
Replace usage of deprecated `codecs.open` function to fix deprecation
warnings emitted in tests, leading to test failure.

```
AssertionError: Failed check in /tmp/tmp_kcwi3hr/./samples/chromium-sample comparing to ./samples/chromium-sample/simple.def for command: /builds/alpine/aports/testing/cpplint/src/cpplint-2.0.2/.testenv/bin/python3 /builds/alpine/aports/testing/cpplint/src/cpplint-2.0.2/cpplint.py  --repository /tmp/tmp_kcwi3hr :
--- first
+++ second
@@ -1,3 +1,5 @@
+'/builds/alpine/aports/testing/cpplint/src/cpplint-2.0.2/cpplint.py:7553: DeprecationWarning: codecs.open()is deprecated. Use open() instead.\n'
+'  with codecs.open(filename, "r", "utf8", "replace") as target_file:\n'

[...]

cpplint_clitest.py:167: AssertionError
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025