testing/heplify-server: disable on ppc64le due to build failure
build fails with:

/usr/lib/go/pkg/tool/linux_ppc64le/link: running gcc failed: exit status 1
/usr/lib/gcc/powerpc64le-alpine-linux-musl/13.2.1/../../../../powerpc64le-alpine-linux-musl/bin/ld: /tmp/go-link-358901543/000022.o: in function `__sanitizer::WriteOneLineToSyslog(char const*)':
gotsan.cpp:(.text+0x81a8): undefined reference to `__syslog_chk'
collect2: error: ld returned 1 exit status