community/glycin-loaders: fix build with libheif-rs
Backport upstream patch to resolve a build error with libheif-rs crate.

```
error[E0063]: missing fields `preload_range_hint`, `release_error_msg`, `release_file_range` and 1 other field in initializer of
↪`heif_reader`
   --> /home/buildozer/aports/community/glycin-loaders/src/glycin-loaders-1.0.1/vendor/libheif-rs/src/reader.rs:101:50
    |
101 | pub(crate) static HEIF_READER: lh::heif_reader = lh::heif_reader {
    |                                                  ^^^^^^^^^^^^^^^ missing `preload_range_hint`, `release_error_msg`,
↪`release_file_range` and 1 other field

For more information about this error, try `rustc --explain E0063`.
error: could not compile `libheif-rs` (lib) due to 1 previous error
```