main/postgresql-bdr: add missing libpq dependency
Fixes:
    >>> postgresql-bdr-client*: Tracing dependencies...
    >>> ERROR: postgresql-bdr-client*: libpq.so.5: path not found

This problem was introduced in
39b29a4e796f2b183ff659d8062e887e79b51fba.