community/task: use cmake3.5 wrapper, fix build with gcc 15
Use cmake3.5 wrapper to rebuild with cmake >= 4 and set a cmake generator.
(The build files do not use ninja and may require adaptation to do so,
e.g. for `ninja: build.ninja:155:98: invalid $ escape` error).

Include `cstdint` header for `{u}int64_t` type definitions.

```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```

```
In file included from /home/builder/builds/task/src/task-2.6.2/src/libshared/src/JSON.cpp:28:
/home/builder/builds/task/src/task-2.6.2/src/libshared/src/JSON.h:148:35: error: 'int64_t' has not been declared
  148 |       virtual void eventValueInt (int64_t) {}
      |                                   ^~~~~~~
/home/builder/builds/task/src/task-2.6.2/src/libshared/src/JSON.h:34:1: note: 'int64_t' is defined in header '<cstdint>'; this is
↪probably fixable by adding '#include <cstdint>'
   33 | #include <Pig.h>
  +++ |+#include <cstdint>
   34 |
/home/builder/builds/task/src/task-2.6.2/src/libshared/src/JSON.h:149:36: error: 'uint64_t' has not been declared
  149 |       virtual void eventValueUint (uint64_t) {}
      |                                    ^~~~~~~~
/home/builder/builds/task/src/task-2.6.2/src/libshared/src/JSON.h:149:36: note: 'uint64_t' is defined in header '<cstdint>'; this
↪is probably fixable by adding '#include <cstdint>'
```