community/quick-lint-js: fix build
Use cmake3.5 wrapper to set a minimum required version of 3.5 for rebuilding
with cmake >= 4. It has been fixed upstream in `adc7db6`.

```
CMake Error at vendor/googletest/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```

Fix build error due to undefined reference to `environ`.

```
/usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: src/libquick-lint-js-lib.a(child-     -process.cpp.o): in function `quick_lint_js::run_program(quick_lint_js::Span<char const* const>, quick_lint_js::Run_Program_Options)':
child-process.cpp:(.text._ZN13quick_lint_js11run_programENS_4SpanIKPKcEENS_19Run_Program_OptionsE+0x299): undefined reference to `quick_lint_js::(anonymous namespace)::environ'
/usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
```