community/rng-tools: disable on ppc64le due to build failure
    rngd_darn.c: In function 'init_darn_entropy_source':
    rngd_darn.c:208:31: error: 'PPC_FEATURE2_DARN' undeclared (first use in this function)
      if (!(getauxval(AT_HWCAP2) & PPC_FEATURE2_DARN)) {
                                   ^~~~~~~~~~~~~~~~~
    rngd_darn.c:208:31: note: each undeclared identifier is reported only once for each function it appears in
    make[2]: *** [Makefile:729: rngd-rngd_darn.o] Error 1