main/zfs: mark udev subpkg as arch-specific
https://gitlab.alpinelinux.org/alpine/abuild/-/commit/758b135ca9cff12726cf15fa7349ce40d42b18dc
sets -udev subpackages as `noarch`, while zfs-udev contains the
zvol-id binary. This causes abuild to fail with:

> ERROR: zfs-udev*: Arch specific binaries found so arch must not be set to "noarch"

Mark the subpackage as having binaries by setting the arch to `all`.