main/vulkan-tools: upgrade to 1.4.321.0
Upgrade to match vulkan-headers version and fix build error.

```
ninja: job failed: /usr/bin/c++ -DVK_ENABLE_BETA_EXTENSIONS -DVK_NO_PROTOTYPES -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR -I/home/buildozer/aports/main/vulkan-tools/src/Vulkan-Tools-vulkan-sdk-1.4.313.0/vulkaninfo/generated -I/home/buildozer/aports/main/vulkan-tools/src/Vulkan-Tools-vulkan-sdk-1.4.313.0/vulkaninfo/. -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -g -flto=auto -Os -DNDEBUG -std=c++17 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-stringop-truncation -MD -MT vulkaninfo/CMakeFiles/vulkaninfo.dir/vulkaninfo.cpp.o -MF vulkaninfo/CMakeFiles/vulkaninfo.dir/vulkaninfo.cpp.o.d -o vulkaninfo/CMakeFiles/vulkaninfo.dir/vulkaninfo.cpp.o -c /home/buildozer/aports/main/vulkan-tools/src/Vulkan-Tools-vulkan-sdk-1.4.313.0/vulkaninfo/vulkaninfo.cpp
In file included from /home/buildozer/aports/main/vulkan-tools/src/Vulkan-Tools-vulkan-sdk-1.4.313.0/vulkaninfo/vulkaninfo.cpp:34:
/home/buildozer/aports/main/vulkan-tools/src/Vulkan-Tools-vulkan-sdk-1.4.313.0/vulkaninfo/generated/vulkaninfo.hpp: In function 'std::vector<const char*> VkImageUsageFlagBitsGetStrings(VkImageUsageFlagBits)':
/home/buildozer/aports/main/vulkan-tools/src/Vulkan-Tools-vulkan-sdk-1.4.313.0/vulkaninfo/generated/vulkaninfo.hpp:1454:9: error: 'VK_IMAGE_USAGE_TILE_MEMORY_QCOM' was not declared in this scope; did you mean 'VK_IMAGE_USAGE_TILE_MEMORY_BIT_QCOM'?
 1454 |     if (VK_IMAGE_USAGE_TILE_MEMORY_QCOM & value) strings.push_back("IMAGE_USAGE_TILE_MEMORY_QCOM");
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         VK_IMAGE_USAGE_TILE_MEMORY_BIT_QCOM
```

Also include a patch for cube CmakeLists.txt to resolve broken build
parameters: `/bin/sh: syntax error: unterminated quoted string`