community/minizip: install missing ints.h header
The `ints.h` file is included but not installed, which resulted in
an error when including `minizip/unzip.h` and `ioapi.h` failing to find
`ints.h`.

Example error with freexl:

```
In file included from /usr/include/minizip/unzip.h:54,
                 from freexl_xlsx.c:87:
/usr/include/minizip/ioapi.h:74:10: fatal error: ints.h: No such file or directory
   74 | #include "ints.h"
      |          ^~~~~~~~
```