testing/libguestfs: disable due to build failures
https://build.alpinelinux.org/buildlogs/build-edge-x86_64/testing/libguestfs/libguestfs-1.40.2-r7.log

```
File "std_utils.ml", line 310, characters 36-37:
310 |       | (y, y') :: _ when cmp x y = 0 -> y'
                                          ^
Error: This expression has type int but an expression was expected of type
         'weak1 list -> int
make[2]: *** [Makefile:2551: std_utils.cmo] Error 2
make[2]: *** Waiting for unfinished jobs....
File "std_utils.ml", line 310, characters 36-37:
310 |       | (y, y') :: _ when cmp x y = 0 -> y'
                                          ^
Error: This expression has type int but an expression was expected of type
         'weak1 list -> int
```