community/karlender: upgrade to 0.10.11
https://gitlab.com/floers/calendar-stuff/karlender/-/blob/main/CHANGELOG.md

Also includes a time crate update, which resolves `error[E0282]: type
annotations needed for 'Box<_>'` error with Rust >=1.80.