testing/*: add temporary boost version constraint
A new boost1.89 aport was introduced, and some builders prefer the latest
available version for testing/ aports. Add a temporary constraint to
enable rebuild with the older one.

```
>>> noggin: Analyzing dependencies...
ERROR: unable to select packages:
  boost1.84-python3-1.84.0-r5:
    conflicts: boost1.89-python3-1.89.0-r0[boost-python3=1.84.0-r5]
    satisfies: py3-imath-3.2.2-r0[so:libboost_python312.so.1.84.0]
  boost1.89-filesystem-1.89.0-r0:
    conflicts: boost1.84-filesystem-1.84.0-r5[boost-filesystem=1.89.0-r0]
    satisfies: boost1.89-dev-1.89.0-r0[boost1.89-filesystem=1.89.0-r0]
               boost1.89-libs-1.89.0-r0[boost1.89-filesystem]
               boost1.89-log-1.89.0-r0[so:libboost_filesystem.so.1.89.0]
               boost1.89-log_setup-1.89.0-r0[so:libboost_filesystem.so.1.89.0]
               boost1.89-process-1.89.0-r0[so:libboost_filesystem.so.1.89.0]
  boost1.89-python3-1.89.0-r0:
    conflicts: boost1.84-python3-1.84.0-r5[boost-python3=1.89.0-r0]
    satisfies: boost1.89-dev-1.89.0-r0[boost1.89-python3=1.89.0-r0]
               boost1.89-libs-1.89.0-r0[boost1.89-python3]
  boost1.89-serialization-1.89.0-r0:
    conflicts: boost1.84-serialization-1.84.0-r5[boost-serialization=1.89.0-r0]
    satisfies: boost1.89-dev-1.89.0-r0[boost1.89-serialization=1.89.0-r0]
               boost1.89-libs-1.89.0-r0[boost1.89-serialization]
               boost1.89-wserialization-1.89.0-r0[so:libboost_serialization.so.1.89.0]
  boost1.84-serialization-1.84.0-r5:
    conflicts: boost1.89-serialization-1.89.0-r0[boost-serialization=1.84.0-r5]
    satisfies: sfcgal-2.2.0-r0[so:libboost_serialization.so.1.84.0]
  boost1.84-filesystem-1.84.0-r5:
    conflicts: boost1.89-filesystem-1.89.0-r0[boost-filesystem=1.84.0-r5]
    satisfies: apache-arrow-22.0.0-r1[so:libboost_filesystem.so.1.84.0]
  .makedepends-noggin-20260118.005509:
    masked in: cache
    satisfies: world[.makedepends-noggin=20260118.005509]
```