community/openjdk-mandrel: fix preparation of builddir
As of abuild 3.16.0 rc, the working directory is in `$startdir` at
`prepare()` if the `$builddir` does not yet exist. Explicitly change
into `$srcdir` before the `mv` operations to ensure the source
directories can be found.

```
>>> openjdk-mandrel: Unpacking /var/cache/distfiles/v3.23/mandrel-packaging-23.0.0.0-Final.tar.gz...
>>> openjdk-mandrel: Unpacking /var/cache/distfiles/v3.23/mandrel-23.0.0.0-Final.tar.gz...
>>> openjdk-mandrel: Unpacking /var/cache/distfiles/v3.23/graalvm-mx-6.27.3.tar.gz...
mv: can't rename 'mandrel-mandrel-23.0.0.0-Final': No such file or directory
>>> ERROR: openjdk-mandrel: unpack failed
```