community/cargo-modules: security upgrade to 0.21.1
- https://github.com/regexident/cargo-modules/blob/v0.21.1/CHANGELOG.md
- https://rustsec.org/advisories/RUSTSEC-2024-0421.html

- community/cargo-modules: enable on s390x
- increase stack size in check(), as done in other rust aports,
  seen on on aarch64, loongarch64, s390x&x86_64` in CI:

    thread 'opt cgu.1' has overflowed its stack
    fatal runtime error: stack overflow
    ...
    error: could not compile `ra_ap_intern` (lib)
    Caused by:
      process didn't exit successfully: `rustc --crate-name ra_ap_intern --edition=2021 /home/buildozer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_intern-0.0.248/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 '--warn=clippy::suspicious' '--warn=clippy::style' '--allow=clippy::restriction' '--deny=clippy::perf' '--deny=clippy::correctness' '--warn=clippy::complexity' '--allow=clippy::wrong_self_convention' '--allow=clippy::useless_asref' --warn=unused_lifetimes --warn=unused_extern_crates --warn=unsafe_op_in_unsafe_fn --warn=unreachable_pub '--allow=clippy::type_complexity' '--allow=clippy::too_many_arguments' '--allow=clippy::too_long_first_doc_paragraph' '--warn=clippy::todo' '--warn=clippy::str_to_string' '--allow=clippy::single_match' '--allow=clippy::result_unit_err' '--warn=clippy::rc_buffer' '--warn=clippy::print_stdout' '--warn=clippy::print_stderr' '--allow=clippy::new_ret_no_self' '--allow=clippy::len_without_is_empty' --warn=explicit_outlives_requirements '--allow=clippy::enum_variant_names' --warn=elided_lifetimes_in_paths '--warn=clippy::dbg_macro' '--allow=clippy::assigning_clones' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=fbf83bd1c198ec03 -C extra-filename=-fbf83bd1c198ec03 --out-dir /builds/alpine/aports/community/cargo-modules/src/cargo-modules-0.21.1/target/debug/deps -L dependency=/builds/alpine/aports/community/cargo-modules/src/cargo-modules-0.21.1/target/debug/deps --extern dashmap=/builds/alpine/aports/community/cargo-modules/src/cargo-modules-0.21.1/target/debug/deps/libdashmap-349b43a21e8eb2de.rmeta --extern hashbrown=/builds/alpine/aports/community/cargo-modules/src/cargo-modules-0.21.1/target/debug/deps/libhashbrown-c7d5b684e11526a4.rmeta --extern rustc_hash=/builds/alpine/aports/community/cargo-modules/src/cargo-modules-0.21.1/target/debug/deps/librustc_hash-bce15cfc309e1373.rmeta --extern sptr=/builds/alpine/aports/community/cargo-modules/src/cargo-modules-0.21.1/target/debug/deps/libsptr-bdadd2f2d306ee25.rmeta --extern triomphe=/builds/alpine/aports/community/cargo-modules/src/cargo-modules-0.21.1/target/debug/deps/libtriomphe-45d3b92066166941.rmeta --cap-lints allow -Clink-arg=-Wl,-z,pack-relative-relocs` (signal: 6, SIGABRT: process abort signal)
    warning: build failed, waiting for other jobs to finish...
    >>> ERROR: cargo-modules: check failed