testing/rhash: disable build on aarch64 due to build failure
gcc -c  -pipe -DIN_RHASH  -O2 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations whirlpool_sbox.c -o whirlpool_sbox.o
In file included from tiger_sbox.c:16:0:
byte_order.h:59:3: error: #error "Can't detect CPU architechture"
 # error "Can't detect CPU architechture"
    ^~~~~