community/bcachefs-tools: upgrade to 1.25.2, disable on x86, enable on loongarch64
https://evilpiepirate.org/git/bcachefs-tools.git/tag/?h=v1.25.2
https://evilpiepirate.org/git/bcachefs-tools.git/tag/?h=v1.25.1
https://evilpiepirate.org/git/bcachefs-tools.git/tag/?h=v1.25.0
https://evilpiepirate.org/git/bcachefs-tools.git/tag/?h=v1.13.0

- loongarch64: no longer blocked by libc crate
- x86: bch_bindgen 0.1.0 still fails on the arch with `error[E0588]:
  packed type cannot transitively contain a `#[repr(align)]` type` error
  after an upstreamed patch

Related upstream links on the bch_bindgen issue:
https://github.com/koverstreet/bcachefs-tools/issues/202
https://github.com/koverstreet/bcachefs-tools/commit/7717a439cffdd32808131ee9837e6c8a8a1972fc