community/idris2-stage0: rebuild against updated chez-scheme 10.3.0
fixes build of idris2:
Exception: incompatible fasl-object version 10.2.0 found in /usr/bin/idris2_app/idris2.so

fixes commit commit 2053fdbb73ef (community/chez-scheme: upgrade to 10.3.0)