community/es-shell: upgrade to 0.9.2_git20250503, enable check
https://github.com/wryun/es-shell/compare/0993c96...f913651

Resolves the following build error:

```
y.tab.c: In function 'yyparse':
y.tab.c:1853: error: expected declaration or statement at end of input
 1853 | break;
y.tab.c:1853: error: expected declaration or statement at end of input
./parse.y:41:2: error: label 'yyaccept' used but not defined
   41 | es      : line end              { parsetree = $1; YYACCEPT; }
      |  ^
./parse.y:61:9: error: label 'yyabort' used but not defined
   61 |         | redir cmd     %prec '!'               { $$ = redirect(mk(nRedir, $1, $2)); if ($$ == &errornode) YYABORT; }
      |         ^
y.tab.c:1507:17: error: label 'yyoverflow' used but not defined
 1507 |                 if (yystack.s_mark >= yystack.s_last && yygrowstack(&yystack) == YYENOMEM) goto yyoverflow;
      |                 ^~
```