community/py3-nashpy: upgrade to 0.0.43
https://github.com/drvinceknight/Nashpy/releases/tag/v0.0.43
https://github.com/drvinceknight/Nashpy/releases/tag/v0.0.42

0.0.42 resolves an assertion error in the `test_properties_of_scores`
test from `tests/unit/test_moran_process.py`.

```
    @given(M=arrays(np.int8, (3, 3), unique=True))
    def test_properties_of_scores(M):
        """
        Checks that if non negative valued matrices are passed then non negative
        valued scores are calculated.

        Parameters
        ----------
        M : array
            a payoff matrix
        """
        if np.min(M) >= 0:
            population = np.array((0, 0, 1, 1, 2, 2))
            scores = score_all_individuals(A=M, population=population)
>           assert np.min(scores) >= 0
E           assert np.int8(-128) >= 0
E            +  where np.int8(-128) = <function min at 0x7fb892fbf370>(array([   6,    6,   20,   20, -128, -128], dtype=int8))
E            +    where <function min at 0x7fb892fbf370> = np.min
E           Falsifying example: test_properties_of_scores(
E               M=array([[ 0,  1,  2],
E                      [ 3,  4,  5],
E                      [ 6, 54,  8]], dtype=int8),
E           )
E           Explanation:
E               These lines were always and only run by failing examples:
E                   /usr/lib/python3.12/site-packages/numpy/_core/arrayprint.py:1304
E                   /usr/lib/python3.12/site-packages/numpy/_core/arrayprint.py:1305

tests/unit/test_moran_process.py:126: AssertionError
```