testing/git-lfs: disable on armhf, aarch64 due to test error
  Git LFS: /home/buildozer/aports/testing/git-lfs/src/git-lfs-2.3.4/bin/git-lfs
  git-lfs/2.3.4 (GitHub; linux arm; go 1.9.2)
  git version 2.15.0
  >>> ERROR: git-lfs*: check failed

I have no idea what's going on, will investigate it later.