community/pg_probackup: add missing makedepend on perl
    checking for perl... no
    configure: error: Perl not found
    >>> ERROR: pg_probackup: prepare failed