testing/py3-certauth: disable check options
py3-certauth test fail with log:

FAILED test/test_certauth.py::test_custom_not_before_not_after - AttributeError: module 'OpenSSL.crypto' has no attribute 'PKCS12'

FAILED test/test_certauth.py::test_ca_cert_in_mem - AttributeError: module 'OpenSSL.crypto' has no attribute 'PKCS12'

I noted that pyOpenSSL have removed OpenSSL.crypto.PKCS12

https://pypi.org/project/pyOpenSSL/23.3.0/
23.3.0 (2023-10-25)
Removed the deprecated OpenSSL.crypto.PKCS12 and OpenSSL.crypto.NetscapeSPKI. OpenSSL.crypto.PKCS12 may be replaced by the PKCS#12 APIs in the cryptography package.