main/postgresql17: new aport
It cannot be built against older libpq, so we have to build it as the
default version right away.

    ld: ../../../src/fe_utils/libpgfeutils.a(connect_utils.o): in function `disconnectDatabase':
      connect_utils.c:(.text+0x35d): undefined reference to `PQcancelCreate'
    ld: connect_utils.c:(.text+0x369): undefined reference to `PQcancelBlocking'
    ld: connect_utils.c:(.text+0x372): undefined reference to `PQcancelFinish'

Co-Authored-By: Jakub Jirutka <jakub@jirutka.cz>