main/wayland-protocols: rebuild against wayland 1.20
wayland has been upgraded to 1.24 in 038b6b0b8a (main/wayland: upgrade
to 1.20.0, 2021-12-09).

Firefox currently fails with:

  undefined reference to `wl_proxy_marshal_flags'

Apparently wayland-protocols needs to be rebuilt after upgrading
wayland.