main/py3-pbr: add missing dependency
Before this change:

    $ dabuild sh
    $ sudo apk add py3-pbr >/dev/null && pbr --version
    Traceback (most recent call last):
      File "/usr/bin/pbr", line 6, in <module>
        from pbr.cmd.main import main
      File "/usr/lib/python3.8/site-packages/pbr/cmd/main.py", line 20, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'

This change adds py3-setuptools as a runtime dependency because
pkg_resources is imported by a file imported by /usr/bin/pbr:

    $ grep 'import pkg_resources' /usr/lib/python3.8/site-packages/pbr/cmd/main.py
    import pkg_resources

pkg_resources is part of py3-setuptools:

    $ apk info -L py3-setuptools | grep pkg_resources/__init__.py
    usr/lib/python3.8/site-packages/pkg_resources/__init__.py

After this change:

    $ dabuild sh
    $ sudo apk add py3-pbr >/dev/null && pbr --version
    5.4.5