testing/croc: disable on mips/mips64 due to test failures
```
--- FAIL: TestHashFile (0.00s)
    utils_test.go:169:
        	Error Trace:	utils_test.go:169
        	Error:      	Not equal:
        	            	expected: "18c9673a4bb8325d323e7f24fda9ae1e"
        	            	actual  : "1860fd5aeb1ac95051d1cc57840037a1"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-18c9673a4bb8325d323e7f24fda9ae1e
        	            	+1860fd5aeb1ac95051d1cc57840037a1
        	Test:       	TestHashFile
46.114.39.143
172.16.19.3
FAIL
FAIL	github.com/schollz/croc/v8/src/utils	3.912s
FAIL
```