testing/elf_diff: add missing dependencies
Fixes

    ModuleNotFoundError: No module named 'yaml'
    ModuleNotFoundError: No module named 'git'
    ModuleNotFoundError: No module named 'anytree'
    ModuleNotFoundError: No module named 'jinja2'