community/alloy: temporarily disable on riscv64
Temporarily disable on riscv64 due to build error with nodejs 24.x.

```
$ react-scripts build
(node:6884) [DEP0176] DeprecationWarning: fs.F_OK is deprecated, use fs.constants.F_OK instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Creating an optimized production build...

[...]

 Fatal error in , line 0
 Check failed: (trampoline_pos - fixup_pos) <= kMaxBranchOffset.

FailureMessage Object: 0x3f91ffb168
----- Native stack trace -----

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>>> ERROR: alloy: build failed
```

See also:

https://github.com/nodejs/node/issues/60895
https://github.com/nodejs/node/pull/60962