community/jinja2-cli: fix compatibility with Python 3.12
Version 0.8.2 of jinja2-cli as the latest available upstream release doesn't
work with Python 3.12+. When invoked to generate a template, it fails with:

    Traceback (most recent call last):
      File "/usr/bin/jinja2", line 8, in <module>
        sys.exit(main())
                ^^^^^^
      File "[...]/jinja2cli/cli.py", line 449, in main
        sys.exit(cli(opts, args))
                ^^^^^^^^^^^^^^^
      File "[...]/jinja2cli/cli.py", line 304, in cli
        data = fn(data) or {}
              ^^^^^^^^
      File "[...]/jinja2cli/cli.py", line 126, in _parse_ini
        p.readfp(StringIO(data))
        ^^^^^^^^
    AttributeError: 'MyConfigParser' object has no attribute 'readfp'. Did you
    mean: 'read'?

Fix that by backporting the upstream patch from [0].

[0]: https://github.com/mattrobenolt/jinja2-cli/pull/132

(cherry picked from commit 2d4a4e61ddb566db48d05998fe89fd453793f1c5)