community/grpc: disable on mips64
grpc needs to be unbundled:

stacktrace.cc:(.text+0x2a8): undefined reference to `backtrace'
/usr/lib/gcc/mips64-alpine-linux-musl/10.2.1/../../../../mips64-alpine-linux-musl/bin/ld: third_party/abseil-cpp/absl/debugging/libabsl_stacktrace.a(stacktrace.cc.o): in function `_GLOBAL__sub_I_stacktrace.cc':