testing/tarantool: disable (dependencies no longer packaged)
Fails with:

	ERROR: unsatisfiable constraints:
	  py2-argparse (missing):
	    required by: .makedepends-tarantool-20200222.141459[py2-argparse]
	  py2-gevent (missing):
	    required by: .makedepends-tarantool-20200222.141459[py2-gevent]
	  py2-msgpack (missing):
	    required by: .makedepends-tarantool-20200222.141459[py2-msgpack]
	  py2-six (missing):
	    required by: .makedepends-tarantool-20200222.141459[py2-six]
	  py2-yaml (missing):
	    required by: .makedepends-tarantool-20200222.141459[py2-yaml]