unmaintained/js_of_ocaml: move from testing, fails to build
    Fatal error: the file '/usr/lib/ocaml/ppx_tools/rewriter' has not the right magic number: expected Caml1999X025, got Caml1999X011