community/deadbeef: disable on ppc64le
```
  CXX      game-music-emu-0.6pre/gme/Gbs_Core.lo
In file included from cgme.c:37:
/usr/include/sys/cdefs.h:1:2: warning: #warning usage of non-standard #include <sys/cdefs.h> is deprecated [-Wcpp]
 #warning usage of non-standard #include <sys/cdefs.h> is deprecated
  ^~~~~~~
In file included from game-music-emu-0.6pre/gme/Ay_Cpu.cpp:56:
game-music-emu-0.6pre/gme/Z80_Cpu_run.h:143:3: error: #error "Byte order of CPU must be known"
  #error "Byte order of CPU must be known"
   ^~~~~
In file included from game-music-emu-0.6pre/gme/Gbs_Cpu.cpp:133:
game-music-emu-0.6pre/gme/Gb_Cpu_run.h:136:4: error: #error "Byte order of CPU must be known"
   #error "Byte order of CPU must be known"
    ^~~~~
  CXX      game-music-emu-0.6pre/gme/Gme_File.lo
game-music-emu-0.6pre/gme/Z80_Cpu_run.h: In member function 'bool Ay_Core::run_cpu(Ay_Core::time_t)':
game-music-emu-0.6pre/gme/Z80_Cpu_run.h:480:10: error: 'R8' was not declared in this scope
   data = R8( opcode & 7, 0 );
          ^~
game-music-emu-0.6pre/gme/Z80_Cpu_run.h:480:10: note: suggested alternative: 'RL'
   data = R8( opcode & 7, 0 );
          ^~
          RL
game-music-emu-0.6pre/gme/Gb_Cpu_run.h: In member function 'void Gbs_Core::run_cpu()':
game-music-emu-0.6pre/gme/Gb_Cpu_run.h:302:10: error: 'R8' was not declared in this scope
   temp = R8( op & 7 );
          ^~
game-music-emu-0.6pre/gme/Gb_Cpu_run.h:323:20: error: 'R8' was not declared in this scope
   READ_FAST( addr, R8( op >> 3 & 7 ) );
                    ^~
game-music-emu-0.6pre/gme/Gbs_Cpu.cpp:115:2: note: in definition of macro 'READ_FAST'
  out = READ_CODE( addr );\
  ^~~
In file included from game-music-emu-0.6pre/gme/Gbs_Cpu.cpp:133:
game-music-emu-0.6pre/gme/Gb_Cpu_run.h:404:9: error: 'R8' was not declared in this scope
    op = R8( data & 7 );
         ^~
game-music-emu-0.6pre/gme/Gb_Cpu_run.h:601:8: error: 'R8' was not declared in this scope
   op = R8( op & 7 );
        ^~
make[2]: *** [Makefile:1675: game-music-emu-0.6pre/gme/Gbs_Cpu.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:1675: game-music-emu-0.6pre/gme/Ay_Cpu.lo] Error 1
make[2]: Leaving directory '/home/buildozer/aports/community/deadbeef/src/deadbeef-1.8.0/plugins/gme'
make[1]: *** [Makefile:815: all-recursive] Error 1
make[1]: Leaving directory '/home/buildozer/aports/community/deadbeef/src/deadbeef-1.8.0'
make: *** [Makefile:605: all] Error 2
>>> ERROR: deadbeef: build failed
```