community/awww: rename from swww, update source url, upgrade to 0.12.1
https://codeberg.org/LGFae/awww/releases/tag/v0.12.1
https://codeberg.org/LGFae/awww/releases/tag/v0.12.0

Previous upstream repo has been archived and development has moved to a
codeberg repo under a new name, awww. Rename aport, update project and
source url.

Upgrade resolves build error on the 3.24 builders.

```
error: failed to run custom build command for `swww-daemon v0.11.2 (/home/buildozer/aports/community/swww/src/swww-0.11.2/daemon)`

Caused by:
  process didn't exit successfully: `/home/buildozer/aports/community/swww/src/swww-0.11.2/target/release/build/swww-daemon-9f605f9a6241b3ed/build-script-build` (exit status: 101)

[...]

--- stderr

  thread 'main' (7043) panicked at /home/buildozer/aports/community/swww/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/waybackend-scanner-0.6.2/src/lib.rs:122:26:
  unrecognized attribute in interface: frozen
```