main/shorewall-shell: fix redirect excludes
Fixes this error:

Setting up Rules...
Bad argument `10.12.96.1'
Try `iptables -h' or 'iptables --help' for more information.
   ERROR: Command "/sbin/iptables -t nat -A D_96_dnat -p tcp -d ! 10.12.96.1 --dport 80 -j REDIRECT --to-port 8080" Failed

on rule:
REDIRECT:info D_96      8080    tcp     80 -    !10.12.96.1
(cherry picked from commit c2ad54cf99aadbc72adbdbafd03f615c4d0aaa30)