community/ruff: increase open file limit for tests
Tests fail with:

    Error: Failed to create directory watcher

    Caused by:
        No file descriptors available (os error 24)