testing/android-file-transfer: remove dependency on android-udev-rules
causes build failure

> (7/192) Installing android-udev-rules (20220903-r0)
> Executing android-udev-rules-20220903-r0.pre-install
> addgroup: group 'plugdev' in use
> ERROR: android-udev-rules-20220903-r0.pre-install: script exited with error 1