testing/simgear: disable due to FTBFS
error: unknown type name 'uint8_t'
error: conflicting types for 'SG_MD5Update'
error: conflicting types for 'SG_MD5Transform'
error: cannot convert 'boost::algorithm::split_iterator<const char*>' to 'PathSplitIterator' {aka 'int'} in initialization