community/blosc: fix build with gcc 15
Remove unused custom bool type to fix build error.

```
ninja: job failed: /usr/bin/cc -DUSING_CMAKE -I/home/buildozer/aports/community/blosc/src/c-blosc-1.21.6/build/blosc -I/home/buildozer/aports/community/blosc/src/c-blosc-1.21.6/blosc -Os -fstack-clash-protection -Wformat -Werror=format-security -fvisibility=hidden -Wall -Wwrite-strings -Wno-unused-function -MD -MT blosc/CMakeFiles/blosc_static.dir/shuffle.c.o -MF blosc/CMakeFiles/blosc_static.dir/shuffle.c.o.d -o blosc/CMakeFiles/blosc_static.dir/shuffle.c.o -c /home/buildozer/aports/community/blosc/src/c-blosc-1.21.6/blosc/shuffle.c
/home/buildozer/aports/community/blosc/src/c-blosc-1.21.6/blosc/shuffle.c:26:15: error: 'bool' cannot be defined via 'typedef'
   26 | typedef _Bool bool;
      |               ^~~~
/home/buildozer/aports/community/blosc/src/c-blosc-1.21.6/blosc/shuffle.c:26:15: note: 'bool' is a keyword with '-std=c23' onwards
/home/buildozer/aports/community/blosc/src/c-blosc-1.21.6/blosc/shuffle.c:26:1: warning: useless type name in empty declaration
   26 | typedef _Bool bool;
      | ^~~~~~~
```