community/libfyaml: fix building with appstream
This imports patches for the following build error.

* fix-c11-atomics.patch
  libfyaml-atomics.h:436:9: error: '__ptr' was not declared in this scope; did you mean 'ptr'

* fix-pkgconfig.patch
  ld: cannot find required: No such file or directory
  ld: cannot find none: No such file or directory

* fix-stray-if.patch
  ./configure: line 21827: syntax error: unexpected "fi"