testing/lomiri-trust-store: rebuild against gtest 1.6.0
This fixes the following issue on armv7, x86_64, and ppc64le:

ERROR: unable to select packages:
  so:libgmock.so.1.15.2 (no such package):
    required by: lomiri-trust-store-2.0.2-r6[so:libgmock.so.1.15.2]
  so:libgmock_main.so.1.15.2 (no such package):
    required by: lomiri-trust-store-2.0.2-r6[so:libgmock_main.so.1.15.2]
  so:libgtest.so.1.15.2 (no such package):
    required by: lomiri-trust-store-2.0.2-r6[so:libgtest.so.1.15.2]
  .makedepends-lomiri-20250217.201142:
    masked in: cache
    satisfies: world[.makedepends-lomiri=20250217.201142]