community/openjdk7: disable arm32-jit
Build on armhf fails:
```
gcc -DLINUX -D_GNU_SOURCE -DCC_INTERP -DZERO -DARM -DZERO_LIBARCH=\"arm\" -DPRODUCT -I. -I/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/share/vm/prims -I/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/share/vm -I/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/share/vm/precompiled -I/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/cpu/zero/vm -I/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/os_cpu/linux_zero/vm -I/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/os/linux/vm -I/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/os/posix/vm -I../generated -DHOTSPOT_RELEASE_VERSION="\"24.111-b01\"" -DHOTSPOT_BUILD_TARGET="\"product\"" -DHOTSPOT_BUILD_USER="\"buildozer\"" -DHOTSPOT_LIB_ARCH=\"arm\" -DHOTSPOT_VM_DISTRO="\"OpenJDK\"" -DDERIVATIVE_ID="\"IcedTea 2.6.7\"" -DDISTRIBUTION_ID="\"Custom build (Fri Sep  2 06:53:44 GMT 2016)\"" -c -Os -fomit-frame-pointer -pipe -fPIC -DTARGET_OS_FAMILY_linux -DTARGET_ARCH_zero -DTARGET_ARCH_MODEL_zero -DTARGET_OS_ARCH_linux_zero -DTARGET_OS_ARCH_MODEL_linux_zero -DTARGET_COMPILER_gcc -I/usr/lib/libffi-3.2.1/include   -std=gnu++98  -fno-rtti -fno-exceptions -D_REENTRANT -fcheck-new -fvisibility=hidden -fno-delete-null-pointer-checks -fno-lifetime-dse -D_LITTLE_ENDIAN -pipe -g -DTARGET_OS_FAMILY_linux -DTARGET_ARCH_zero -DTARGET_ARCH_MODEL_zero -DTARGET_OS_ARCH_linux_zero -DTARGET_OS_ARCH_MODEL_linux_zero -DTARGET_COMPILER_gcc -I/usr/lib/libffi-3.2.1/include   -std=gnu++98 -fpic -fno-rtti -fno-exceptions -D_REENTRANT -fcheck-new -fvisibility=hidden -fno-delete-null-pointer-checks -fno-lifetime-dse -D_LITTLE_ENDIAN -pipe -g -O3 -fno-strict-aliasing -DHOTSPOT_ASM -DVM_LITTLE_ENDIAN -DINCLUDE_TRACE=1  -Wpointer-arith -Wsign-compare   -Os -fomit-frame-pointer -pipe -fPIC -std=gnu++98 -Wno-error -fno-delete-null-pointer-checks -fno-lifetime-dse -o cppInterpreter_arm.o /home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/cpu/zero/vm/cppInterpreter_arm.S
/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/cpu/zero/vm/arm32JIT.cpp: In function 'void Thumb2_codegen(Thumb2_Info*, unsigned int)':
/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/cpu/zero/vm/arm32JIT.cpp:5720:7: error: duplicate case value
       case opc_fast_aldc_w:
       ^~~~
/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/cpu/zero/vm/arm32JIT.cpp:5719:7: error: previously used here
       case opc_return_register_finalizer:
       ^~~~
/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/cpu/zero/vm/arm32JIT.cpp:6985:7: error: duplicate case value
       case opc_return_register_finalizer: {
       ^~~~
/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/cpu/zero/vm/arm32JIT.cpp:6877:5: error: previously used here
     case opc_fast_aldc_w:
     ^~~~
/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/cpu/zero/vm/arm32JIT.cpp: In function 'void Thumb2_Initialize()':
/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/src/cpu/zero/vm/arm32JIT.cpp:8188:34: error: overloaded function with no contextual type information
   mov_imm(&codebuf, ARM_IP, (u32)fmod);
                                  ^~~~
make[7]: *** [/home/buildozer/aports/community/openjdk7/src/icedtea-2.6.7/openjdk-boot/hotspot/make/linux/makefiles/rules.make:150: arm32JIT.o] Error 1
```

http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2942
(cherry picked from commit 88031301dd3828f5975c59054151ab369831c252)