main/mesa: fix bad if-macro on ppc64le
A backported commit causes a build failure on ppc64le.

```
/lp_bld_misc.cpp
../src/gallium/auxiliary/gallivm/lp_bld_misc.cpp:708:28: error: #if with no expression
  708 | #if PIPE_ARCH_LITTLE_ENDIAN
```

Upstream issue: https://gitlab.freedesktop.org/mesa/mesa/issues/2131