community/ktistic: temporarily disable
Initially proceeded to check stage but has since failed to build.
Temporarily disable to unblock the x86_64 builder.

```
I: Installing spectator (0.12.2)
/usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lyaml ␛[33;1m(this usually means you need to install the development package for libyaml)␛[0m: No such file or directory
collect2: error: ld returned 1 exit status
␛[31;1mError: ␛[0m␛[1mexecution of command failed with exit status 1: cc "${@}" -o /home/buildozer/aports/community/ktistec/src/ktistec-3.1.0/server  -rdynamic -L/home/buildozer/aports/community/ktistec/src/crystal-1.16.3-x86_64-alpine-linux-musl/bin/../lib/crystal -lyaml -lgmp -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lsqlite3 -lxml2 -lpcre2-8 -lgc -lpthread -ldl␛[0m
>>> ERROR: ktistec: build failed
```