testing/mkdotenv: change into srcdir during build
Change into the `srcdir` in the make command within `build()` so that
the `Makefile` can be found.

```
>>> mkdotenv: Unpacking /var/cache/distfiles/edge/mkdotenv-0.4.9.tar.gz...
make: *** No targets specified and no makefile found.  Stop.
>>> ERROR: mkdotenv: build failed
```

The tarball checksum has changed but `diff` identified no changes between the
extracted directories. Temporarily rename the package filename to avoid
potential checksum mismatch with the cached version in distfiles.