community/py3-spsdk: fix tests with click 8.3.1
Fix test errors with click 8.3.1. The `mix_stderr` parameter was removed
from `CliRunner` in click 8.2.0.

Example error:

```
 _____________________________ test_spsdk_apps_help _____________________________

 cli_runner = <tests.cli_runner.CliRunner object at 0x7fa7acc8e120>

     def test_spsdk_apps_help(cli_runner: CliRunner):
         run_help(cli_runner, spsdk_apps.main, help_option=True)
 >       run_help(cli_runner, spsdk_apps.main, help_option=False)

 tests/apps/test_help.py:33:
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 tests/apps/test_help.py:27: in run_help
     result = cli_runner.invoke(command_group, ["--help"] if help_option else None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[...]

     def _build_error_message(self, result: Result, expected_code: int) -> str:
         """Build error message from the result."""
         error_msg = f"Expected code: {expected_code}, Actual code: {result.exit_code} \n"
         if result.exception:
             error_msg += f"{result.exception}\n"
 >       error_msg += result.output if self.mix_stderr else result.stderr
                                       ^^^^^^^^^^^^^^^
 E       AttributeError: 'CliRunner' object has no attribute 'mix_stderr'

 tests/cli_runner.py:35: AttributeError
```

```
FAILED tests/apps/test_help.py::test_spsdk_apps_help - AttributeError: 'CliRu...
FAILED tests/apps/test_help.py::test_spsdk_apps_subcommands_help_without_help_option
FAILED tests/dk6/test_dk6_tools.py::test_cli - AttributeError: 'CliRunner' ob...
FAILED tests/nxpmemcfg/test_nxpmemcfg.py::test_app_help - AttributeError: 'Cl...
```

Also update depends list, py3-commentjson was removed from dependencies
in 2.1.0.

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18025