testing/pinnacle: upgrade to 0.2.4
enable on all 64bit architecures, 32bit architectures blocked by:

error: cannot construct `timespec` with struct literal syntax due to private fields
    --> /builds/alpine/aports/testing/pinnacle/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-hal-27.0.4/src/vulkan/adapter.rs:2682:32
     |
2682 |             let mut timespec = libc::timespec {
     |                                ^^^^^^^^^^^^^^
     |
     = note: ...and other private field `__pad0` that was not provided
help: consider using the `Default` trait
     |
2682 -             let mut timespec = libc::timespec {
2683 -                 tv_sec: 0,
2684 -                 tv_nsec: 0,
2685 -             };
2682 +             let mut timespec = <libc::timespec as std::default::Default>::default();
     |