testing/opa: fix test with go 1.24.5
Fix test error with runtime/metrics.

```
--- FAIL: TestJSONSerialization (0.01s)
    prometheus_test.go:189: unexpected extra metrics, expected 117, got 118
    prometheus_test.go:200: unexpected metric: go_godebug_non_default_behavior_allowmultiplevcs_events_total (type: map[help:The number of non-default behaviors executed by the cmd/go package due to a non-default GODEBUG=allowmultiplevcs=... setting. Sourced from /godebug/non-default-behavior/allowmultiplevcs:events. metric:[map[counter:map[createdTimestamp:2025-07-10T02:11:01.527053306Z value:0]]] name:go_godebug_non_default_behavior_allowmultiplevcs_events_total type:COUNTER])
FAIL
FAIL	github.com/open-policy-agent/opa/internal/prometheus	0.017s
```