community/py3-ansible-compat: fix checksum
Update checksum to fix checksum mismatch error on the 3.24 builders.
Upstream re-tagged the release archive.

```
sha512sum: WARNING: 1 of 1 computed checksums did NOT match
Because the remote file above failed the sha512sum check it will be renamed.
Rebuilding will cause it to re-download which in some cases may fix the problem.
Renaming: ansible-compat-26.3.0.tar.gz to ansible-compat-26.3.0.tar.gz.fdc670d4
>>> ERROR: py3-ansible-compat: Use 'abuild checksum' to generate/update the checksum(s)
```

```
diff -rupN a/.git_archival.txt b/.git_archival.txt
--- a/.git_archival.txt 2026-03-31 15:45:51.000000000 +0000
+++ b/.git_archival.txt 2026-03-31 15:45:51.000000000 +0000
@@ -1,4 +1,4 @@
 node: 8c5aebe4397dd97f2304e04b30c3fce26c90a3f6
 node-date: 2026-03-31T16:45:51+01:00
 describe-name: v26.3.0
-ref-names: HEAD -> main, tag: v26.3.0
+ref-names: tag: v26.3.0
```