main/py-curl: Add libssl-dev as a make dependency
py-curl does not build on a clean environment due to lack of
libressl-dev package, that is not listed as a make-dependency.

This is the failure:

 In file included from src/docstrings.c:4:0:
 src/pycurl.h:170:31: fatal error: openssl/crypto.h: No such file or directory
  #   include <openssl/crypto.h>
                               ^
 compilation terminated.
 error: command 'gcc' failed with exit status 1
 >>> ERROR: py-curl: all failed