community/cjdns: upgrade to 22.1, fix build with rust >= 1.89
https://github.com/cjdelisle/cjdns/blob/master/CHANGELOG.md#version-221---seedy

Fix implicit autoref error with rust >= 1.89.

Disable on 32-bit arches due to assertion error and core dump.

```
error: implicit autoref creates a reference to the dereference of a raw pointer
   --> rust/cjdns_sys/src/rffi.rs:322:13
    |
322 |     let p = (*ca).0.public_key.raw();
    |             ^^--^^^^^^^^^^^^^^
    |               |
    |               this raw pointer has type `*const RTypes_CryptoAuth2_t`
    |
    = note: creating a reference requires the pointer target to be valid and imposes aliasing requirements
    = note: references are created through calls to explicit `Deref(Mut)::deref(_mut)` implementations
    = note: `#[deny(dangerous_implicit_autorefs)]` on by default
help: try using a raw pointer method instead; or if this reference is intentional, make it explicit
    |
322 |     let p = (&(*ca).0).public_key.raw();
    |             ++       +

warning: `cjdns_sys` (lib) generated 3 warnings
error: could not compile `cjdns_sys` (lib) due to 1 previous error; 3 warnings emitted
```

Error on 32-bit arches:

```
thread 'tokio-runtime-worker' (24142) panicked at rust/cjdns_sys/src/rffi/util.rs:32:5:
Assertion failure [RandomSeed.c:41] [(Identity_ptr->Identity_verifier == 0x5e3b9961bcd8a25aull)]
stack backtrace:
   0:   0x5a0c90 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2056bb43e64e80c6
   1:   0x571b68 - core::fmt::write::hcf3aaf1a68a0acbb
   2:   0x5a04ce - std::io::Write::write_fmt::he658b1b0974b62c5
   3:   0x5a0bb8 - std::sys::backtrace::BacktraceLock::print::h5db6ccc72c366154
   4:   0x5a0958 - std::panicking::default_hook::h1e01fb55ae54a2dd
Aborted (core dumped)
```