community/ruby-ox: disable on armhf and armv7 due to build failure
    gen_load.c:140:1: error: invalid storage class for function 'instruct'
      140 | instruct(PInfo pi, const char *target, Attr attrs, const char *content) {
          | ^~~~~~~~
    gen_load.c:159:1: error: invalid storage class for function 'nomode_instruct'
      159 | nomode_instruct(PInfo pi, const char *target, Attr attrs, const char *content) {
          | ^~~~~~~~~~~~~~~
    gen_load.c:194:1: error: invalid storage class for function 'add_doctype'
      194 | add_doctype(PInfo pi, const char *docType) {
          | ^~~~~~~~~~~
    gen_load.c:211:1: error: invalid storage class for function 'add_comment'
      211 | add_comment(PInfo pi, const char *comment) {
          | ^~~~~~~~~~~
    gen_load.c:228:1: error: invalid storage class for function 'add_cdata'
      228 | add_cdata(PInfo pi, const char *cdata, size_t len) {
          | ^~~~~~~~~
    gen_load.c:245:1: error: invalid storage class for function 'add_text'
      245 | add_text(PInfo pi, char *text, int closed) {
          | ^~~~~~~~
    gen_load.c:260:1: error: invalid storage class for function 'add_element'
      260 | add_element(PInfo pi, const char *ename, Attr attrs, int hasChildren) {
          | ^~~~~~~~~~~
    gen_load.c:337:1: error: invalid storage class for function 'end_element'
      337 | end_element(PInfo pi, const char *ename) {
          | ^~~~~~~~~~~
    gen_load.c:344:1: error: invalid storage class for function 'add_instruct'
      344 | add_instruct(PInfo pi, const char *name, Attr attrs, const char *content) {
          | ^~~~~~~~~~~~
    gen_load.c:414:1: error: expected declaration or statement at end of input
      414 | }
          | ^