community/evince: rebuild after libgspell update
Currently trying to install evince gives an error like:

ERROR: unable to select packages:
  so:libgspell-1.so.2 (no such package):
    required by: evince-libs-46.3.1-r1[so:libgspell-1.so.2]