testing/emscripten-fastcomp: fix so names conflict with llvm pkg
  ERROR: unsatisfiable constraints:
    emscripten-fastcomp-1.37.9-r0:
      conflicts: llvm-3.8.1-r2[so:BugpointPasses.so=0]
      satisfies: world[emscripten-fastcomp]
    llvm-3.8.1-r2:
      conflicts: emscripten-fastcomp-1.37.9-r0[so:BugpointPasses.so=0]
      satisfies: world[llvm]