main/linux-vanilla: Add missing build dependencies
flex and bison were causing the configure step to fail

libressl-dev is also required during the build

```
/home/alpine/project/testing/linux-vanilla/src/linux-4.17/scripts/extract-cert.c:21:25: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>
```