community/py3-webob: build with gpep517, fix running tests
Switch to gpep517 and fix check failure due to `tests_require` being
removed from setuptools.

```
Traceback (most recent call last):
  File "/home/buildozer/aports/community/py3-webob/src/WebOb-1.8.7/setup.py", line 26, in <module>
    setup(
  File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 186, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 1105, in run_command
    super().run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.12/site-packages/ptr/__init__.py", line 195, in run
    setattr(dist, attr, getattr(self.distribution, attr))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Distribution' object has no attribute 'tests_require'. Did you mean: 'extras_require'?
```