community/py3-makefun: remove py3-setuptools version constraint
Resolve build error due to the specified version of py3-setuptools being
unavailable.

```
ERROR: unable to select packages:
  py3-setuptools-77.0.3-r0:
    breaks: .makedepends-py3-makefun-20250502.071732[py3-setuptools<72]
    satisfies: py3-setuptools_scm-8.2.0-r0[py3-setuptools]
               py3-pytest-runner-6.0.1-r1[py3-setuptools]
```