testing/openimageio: disable on armhf due to failing build
[ 97%] Built target maketx
/home/buildozer/aports/testing/openimageio/src/oiio-Release-1.8.15/src/iv/ivgl.cpp: In member function 'virtual void IvGL::initializeGL()':
/home/buildozer/aports/testing/openimageio/src/oiio-Release-1.8.15/src/iv/ivgl.cpp:117:5: error: 'glLoadIdentity' was not declared in this scope
  117 |     glLoadIdentity();
      |     ^~~~~~~~~~~~~~
/home/buildozer/aports/testing/openimageio/src/oiio-Release-1.8.15/src/iv/ivgl.cpp:122:5: error: 'glScalef' was not declared in this scope; did you mean 'locale'?
  122 |     glScalef (dpr, dpr, 1.0f);
      |     ^~~~~~~~
      |     locale
/home/buildozer/aports/testing/openimageio/src/oiio-Release-1.8.15/src/iv/ivgl.cpp: In member function 'virtual void IvGL::create_textures()':
/home/buildozer/aports/testing/openimageio/src/oiio-Release-1.8.15/src/iv/ivgl.cpp:176:60: error: 'GL_CLAMP' was not declared in this scope
  176 |         glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP);