community/youtube-dl: depend on py3-setuptools
Otherwise youtube-dl will fail with the following error message:

	Traceback (most recent call last):
	  File "/usr/bin/youtube-dl", line 6, in <module>
	    from pkg_resources import load_entry_point
	ImportError: cannot import name 'load_entry_point'

See also: https://bugs.archlinux.org/task/37544