community/dunst: upgrade to 1.12.2
https://github.com/dunst-project/dunst/releases/tag/v1.12.2

Resolves a build error with libnotify >= 0.8.4.

```
dunstify.c: In function 'get_id':
dunstify.c:205:21: error: 'NotifyNotification' has no member named 'priv'
  205 |     knickers *kn = n->priv;
      |                     ^~
dunstify.c: In function 'put_id':
dunstify.c:213:21: error: 'NotifyNotification' has no member named 'priv'
  213 |     knickers *kn = n->priv;
      |                     ^~
```