community/repology-cli: add zlib-dev to makedepends
The `conftest` attempts to link against zlib and could not find it,
which caused the initial compiler check in `configure` to fail. Add
`zlib-dev` to makedepends.

```
checking for D compiler... not found
error: Please install a D compiler and re-run configure
```