main/mariadb: disable on armhf for now
mariadb does async functions using fibers. for x86 and x86_64 it
has asm implementation, but for other architectures it uses
{make,swap,get}context. musl does not support that, but ships the
ucontext.h which makes mariadb think it exists and the build fails
with:
../mysys/libmysys.a(my_context.c.o): In function `my_context_spawn_internal':
/home/buildozer/aports/main/mariadb/src/mariadb-10.1.12/mysys/my_context.c:63: undefined reference to `setcontext'
../mysys/libmysys.a(my_context.c.o): In function `my_context_continue':
/home/buildozer/aports/main/mariadb/src/mariadb-10.1.12/mysys/my_context.c:77: undefined reference to `swapcontext'
...

For now disable on armhf.

(cherry picked from commit ad7c54bd9b6d8e60e88a313a92c83d083f196db8)