community/gleam: upgrade to 1.15.2
1. https://github.com/gleam-lang/gleam/releases/tag/v1.15.2
2. fix error: error[E0609]: no field `st_atime` on type `&libc::stat`
Ref:
https://github.com/rust-lang/libc/issues/4939
https://github.com/rust-lang/libc/releases/tag/0.2.181