Revert "testing/virtualbox-additions-vanilla: replace the hardened"
This reverts commit 18e4a7f916db048f6a3418e41b757c977cc5d6a5.

This patch is broken (wrong checksums) and couples two unrelated
changes - rename of the abuild and version upgrade.

    >>> virtualbox-additions-vanilla: abuild 3.1.0-r4
    >>> virtualbox-additions-vanilla: Checking sanity of /home/buildozer/aports/testing/virtualbox-additions-vanilla/APKBUILD...
    >>> ERROR: virtualbox-additions-vanilla: vbox-kernel-module-src-5.2.6.tar.xz is missing in checksums