Use /var/lib/barman as home
This will create /var/lib/barman and set correct permissions.

The default config file states 'barman_home = /var/lib/barman'. If this
directory doesn't exist, there will be errors at runtime, for example:

  / # barman cron
  ERROR: [Errno 2] No such file or directory:
  '/var/lib/barman/.streaming-pg-cron.lock'