community/make-tweak: add missing dependency on py3-distro
Fixes:
ModuleNotFoundError: No module named 'distro'

$ grep -n 'distro' /usr/bin/mate-tweak
22:import distro
1262:        if distro.id() != 'ubuntu' and \