community/rng-tools: fix build on ppc64le - requires libgcrypt
    rngd_darn.c:28:2: error: #error power DARN support requires libgcrypt!
     #error power DARN support requires libgcrypt!
      ^~~~~
    rngd_darn.c:34:20: fatal error: gcrypt.h: No such file or directory
     #include <gcrypt.h>
                        ^