community/ccls: build with non-default clang
Building with default clang/llvm results in the error below. Rebuild with
clang/llvm19 for now.

```
ninja: job failed: /usr/bin/clang++  -I/home/buildozer/aports/community/ccls/src/ccls-0.20241108/src -isystem /home/buildozer/aports/community/ccls/src/ccls-0.20241108/third_party -isystem /usr/lib/llvm20/include -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -O3 -DNDEBUG -std=c++17 -Wall -Wno-sign-compare -MD -MT CMakeFiles/ccls.dir/src/clang_tu.cc.o -MF CMakeFiles/ccls.dir/src/clang_tu.cc.o.d -o CMakeFiles/ccls.dir/src/clang_tu.cc.o -c /home/buildozer/aports/community/ccls/src/ccls-0.20241108/src/clang_tu.cc
/home/buildozer/aports/community/ccls/src/ccls-0.20241108/src/clang_tu.cc:128:7: error: no matching function for call to 'createDiagnostics'
  128 |       CompilerInstance::createDiagnostics(new DiagnosticOptions,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/llvm20/include/clang/Frontend/CompilerInstance.h:687:8: note: candidate function not viable: no known conversion from 'DiagnosticOptions *' to 'llvm::vfs::FileSystem &' for 1st argument
  687 |   void createDiagnostics(llvm::vfs::FileSystem &VFS,
      |        ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/llvm20/include/clang/Frontend/CompilerInstance.h:710:3: note: candidate function not viable: no known conversion from 'DiagnosticOptions *' to 'llvm::vfs::FileSystem &' for 1st argument
  710 |   createDiagnostics(llvm::vfs::FileSystem &VFS, DiagnosticOptions *Opts,
      |   ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```