main/tiny-cloud: make the -alpine provides versioned
fixes: https://gitlab.alpinelinux.org/alpine/aports/-/issues/16600

    ERROR: unable to select packages:
      tiny-cloud-alpine (virtual):
        note: please select one of the 'provided by'
              packages explicitly
        provided by: tiny-cloud-nocloud
        required by: world[tiny-cloud-alpine]

(cherry picked from commit a76934339e2e3e3e6d0c01995753ca4a9da8d58f)