community/telegraf: fix tests
Align `go.mod` go version in the upstream go 1.26 patch for 1.37.0.

Fix `fmt` print verb in `procstat` plugin error messages.

Use `/tmp` directory for temporary sockets in tests due to socket path
length limit.

Example errors:

```
--- FAIL: TestListenData (0.85s)
    --- FAIL: TestListenData/unix_socket_with_gzip_encoding (-1.00s)
        socket_test.go:173:
              Error Trace:  github.com/influxdata/telegraf/plugins/common/socket/socket_test.go:173
              Error:        Received unexpected error:
                            listen unix /home/buildozer/aports/community/telegraf/tmp/TestListenDataunix_socket_with_gzip_encoding1344197689/001/sock: bind: invalid argument
              Test:         TestListenData/unix_socket_with_gzip_encoding
--- FAIL: TestListenConnection (0.83s)
    --- FAIL: TestListenConnection/unix_socket_with_gzip_encoding (0.00s)
        socket_test.go:377:
              Error Trace:  github.com/influxdata/telegraf/plugins/common/socket/socket_test.go:377
              Error:        Received unexpected error:
                            listen unix /home/buildozer/aports/community/telegraf/tmp/TestListenConnectionunix_socket_with_gzip_encoding3731380617/001/sock: bind: invalid argument
              Test:         TestListenConnection/unix_socket_with_gzip_encoding
FAIL
FAIL  github.com/influxdata/telegraf/plugins/common/socket  8.125s
```

```
--- FAIL: TestPowerdnsGeneratesMetrics (0.00s)
    powerdns_linux_test.go:42: Cannot initialize server on port
[...]
FAIL
FAIL  github.com/influxdata/telegraf/plugins/inputs/powerdns  0.152s
```