community/py3-pygithub: fix installer .whl filename
Fix packaging error due to changed .whl filename with setuptools >= 75.3.1.

```
FileNotFoundError: [Errno 2] No such file or directory: '.dist/PyGithub-2.5.0-py3-none-any.whl'
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/17110