community/gjs: bump pkgrel
Rebuild gjs against current mozjs, so armv7 builds against gjs don't
fail anymore:

  ninja: job failed: cc  -o src/gnome-shell-portal-helper src/gnome-shell-portal-helper.p/meson-generated_.._.._js_portal-resources.c.o src/gnome-shell-portal-helper.p/gnome-shell-portal-helper.c.o -flto=auto -Wl,--as-needed -Wl,--no-undefined -pie -Wl,--as-needed,-O1,--sort-common -Os -fstack-clash-protection -Wformat -Werror=format-security -g -Wl,--start-group /usr/lib/libgio-2.0.so /usr/lib/libgobject-2.0.so /usr/lib/libglib-2.0.so /usr/lib/libintl.so /usr/lib/libgjs.so -Wl,--end-group
  /usr/lib/gcc/armv7-alpine-linux-musleabihf/15.2.0/../../../../armv7-alpine-linux-musleabihf/bin/ld: /usr/lib/libgjs.so: undefined reference to `__aeabi_uldivmod@mozjs_140'
  /usr/lib/gcc/armv7-alpine-linux-musleabihf/15.2.0/../../../../armv7-alpine-linux-musleabihf/bin/ld: /usr/lib/libgjs.so: undefined reference to `__aeabi_uidivmod@mozjs_140'

Related: https://builds.sr.ht/~postmarketos/job/1775838#task-pmbootstrap_build-1973