community/kimageformats: disable support for exf for now
It's failing on the builders with a linker error (even though it
succeeded on CI), needs investigating:

ninja: job failed: : && /usr/bin/c++ -fPIC -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-operator-names -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Werror=init-self -Werror=undef -Wvla -Wdate-time -Wsuggest-override -Wlogical-op -pedantic -Wzero-as-null-pointer-constant -Wmissing-include-dirs -fdiagnostics-color=always -fexceptions -O2 -g -DNDEBUG  -Wl,--no-undefined -Wl,--fatal-warnings -Wl,--enable-new-dtags -Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs -shared  -o bin/imageformats/kimg_exr.so src/imageformats/CMakeFiles/kimg_exr.dir/kimg_exr_autogen/mocs_compilation.cpp.o src/imageformats/CMakeFiles/kimg_exr.dir/exr.cpp.o src/imageformats/CMakeFiles/kimg_exr.dir/scanlineconverter.cpp.o  /usr/lib/libQt6Gui.so.6.8.2  /usr/lib/libOpenEXR-3_3.so.32.3.3.2  /usr/lib/libGL.so  /usr/lib/libQt6Core.so.6.8.2  /usr/lib/libIlmThread-3_3.so.32.3.3.2  /usr/lib/libIex-3_3.so.32.3.3.2  /usr/lib/libOpenEXRCore-3_3.so.32.3.3.2  /usr/lib/libImath-3_2.a  -lm && :
/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/bin/ld: src/imageformats/CMakeFiles/kimg_exr.dir/exr.cpp.o: in function `EXRHandler::write(QImage const&)':
/home/buildozer/aports/community/kimageformats/src/kimageformats-6.13.0/src/imageformats/exr.cpp:561:(.text+0x3026): undefined reference to `Imf_3_3::Header::Header(int, int, float, Imath_3_2::Vec2<float> const&, float, Imf_3_3::LineOrder, Imf_3_3::Compression)'
collect2: error: ld returned 1 exit status