testing/wazero: fix test with go 1.25
Fix test error with go 1.25.

```
--- FAIL: TestAdjustClonedStack (0.00s)
    require.go:331: expected 824635488656, but was 824639052176
        /home/buildozer/aports/testing/wazero/src/wazero-1.9.0/internal/engine/wazevo/backend/isa/amd64/stack_test.go:68
FAIL
FAIL	github.com/tetratelabs/wazero/internal/engine/wazevo/backend/isa/amd64	0.027s
```