community/{mutter,gnome-shell}: re-enable on loongarch64
Re-enable the aports to resolve dependency error with gnome on the arch.

```
ERROR: unable to select packages:
  gnome-shell (no such package):
    required by: gdm-48.0-r2[gnome-shell]
                 .makedepends-gnome-20250916.222507[gnome-shell]
  .makedepends-gnome-20250916.222507:
    masked in: cache
    satisfies: world[.makedepends-gnome=20250916.222507]
>>> ERROR: gnome: builddeps failed
```