testing/creduce: disable due to build error
link failure:

> ScratchBuffer.cpp:(.text._ZN5clang13ScratchBuffer18AllocScratchBufferEj+0x4c):
> undefined reference to
> `llvm::WritableMemoryBuffer::getNewMemBuffer(unsigned long,
> llvm::Twine const&)'