testing/tarantool: disable on aarch64, armhf (build only on x86_64)
Fails to build on aarch64:

  cd /home/buildozer/aports/testing/tarantool/src/tarantool-1.7.4.335/test/unit && /usr/bin/cmake -E cmake_link_script CMakeFiles/coio.test.dir/link.txt --verbose=1
  /usr/bin/c++  -Os -fexceptions -funwind-tables -fno-common -fopenmp -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-unused-parameter -Wno-unused -Wno-tautological-compare -O3 -DNDEBUG  -rdynamic CMakeFiles/coio.test.dir/coio.cc.o CMakeFiles/coio.test.dir/__/__/src/iobuf.cc.o  -o coio.test ../../src/libcore.a ../../libeio.a ../../src/lib/bit/libbit.a ../../src/liburi.a libunit.a ../../src/lib/salad/libsalad.a ../../src/lib/small/libsmall.a -lpthread ../../libev.a -lm -Wl,-Bstatic -lcoro -Wl,-Bdynamic
  ../../src/libcore.a(fiber.c.o): In function `fiber_schedule_wakeup':
  fiber.c:(.text+0xb0): undefined reference to `coro_transfer'
  ../../src/libcore.a(fiber.c.o): In function `fiber_loop':
  fiber.c:(.text+0x658): undefined reference to `coro_transfer'
  ../../src/libcore.a(fiber.c.o): In function `fiber_call':
  fiber.c:(.text+0xf80): undefined reference to `coro_transfer'
  ../../src/libcore.a(fiber.c.o): In function `fiber_start':
  fiber.c:(.text+0x1038): undefined reference to `coro_transfer'
  ../../src/libcore.a(fiber.c.o): In function `fiber_reschedule':
  fiber.c:(.text+0x1368): undefined reference to `coro_transfer'
  ../../src/libcore.a(fiber.c.o):fiber.c:(.text+0x1560): more undefined references to `coro_transfer' follow
  collect2: error: ld returned 1 exit status
  make[2]: *** [test/unit/CMakeFiles/coio.test.dir/build.make:133: test/unit/coio.test] Error 1